### ISSUE TITLE
ie9 support?

### ISSUE THREAD

**Issue by djindjic** [aurelia/dependency-injection#10]
just want to ask do you plant to supprort ie9 for di?

**Comment by EisenbergEffect** [comment]
Aurelia doesn't support non-Evergreen browsers. Practically that means at least IE11, maybe IE10, but no guarantees on 10 at this point. What part is failing?

**Comment by djindjic** [comment]
I have [this](https://github.com/djindjic/metabolicjs/blob/master/test/carb.spec.js#L87) test case fails on ie9 at travis build over sauce labs [here](https://travis-ci.org/djindjic/metabolicjs/builds/47523967#L351)

**Comment by djindjic** [comment]
hm, I seems like travis link to specific line doesn't work, but you can try to scroll down to the bottom.

**Comment by EisenbergEffect** [comment]
That's odd. Have you tried running the official test suite?

On Mon, Jan 19, 2015 at 9:20 AM, Aleksandar Djindjic <
notifications@github.com> wrote:

> I have this
> <https://github.com/djindjic/metabolicjs/blob/master/test/carb.spec.js#L87>
> test case fails on ie9 at travis build over sauce labs here
> <https://travis-ci.org/djindjic/metabolicjs/builds/47523967#L351>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/dependency-injection/issues/10#issuecomment-70498712>
> .
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by djindjic** [comment]
no I haven't tried to setup di fork to sauce but I'm pretty sure it would fail because of all other test cases succeeds on chrome and ff and my sample is very simple. it just looks odd :D
