### ISSUE TITLE
Injecting event-aggregator not working anymore

### ISSUE THREAD

**Issue by jc1001** [aurelia/dependency-injection#105]
Hi there,

After upgrading to Aurelia RC1, my existing code that injected an event-aggregator stopped working (it worked when I was using the Aurelia beta).  I managed to reproduce the issue using the esnext-skeleton project by doing the following:

- Setup the skeleton project as per the instructions in the readme file.

- Run gulp watch and browse to the site - all good.

- Change the app.js file with the following code (using the event-aggregator info in the cheatsheet):
```
import {inject} from 'aurelia-framework';
import {EventAggregator} from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class App {
  ...
   constructor(eventAggregator) {
     alert("constructed");
   }  
}
```
When browsing to the site now, it is looking for aurelia-event-aggregator.js on an invalid url.
![invalid url](https://cloud.githubusercontent.com/assets/15125812/16454084/8055ea32-3e0f-11e6-9e52-9cb4c3bf0045.png)

Here is the modified file (literally all that I've modified in the skeleton project):
[app.zip](https://github.com/aurelia/dependency-injection/files/339380/app.zip)

I've tried exactly the same thing by injecting the fetch-client (HttpClient) and that is working 100%.  It only seems to be unhappy with the aggregator.

If you require anything else from me, please let me know.

**Comment by EisenbergEffect** [comment]
Nothing has changed with respect to this, as far as we know. Assuming you are using system.js and jspm, please make sure there is a top level dependency in your config.js file. It sounds like that may be missing in your setup. You can ensure this by running `jspm install aurelia-event-aggregator`. Also, check to make sure you don't have any forks with `jspm inspect --forks`

Please let me know.

**Comment by jc1001** [comment]
Thank you for the quick response.  `jspm-inspect --forks` returns the following:
![jspmforks](https://cloud.githubusercontent.com/assets/15125812/16456215/77c57dda-3e17-11e6-9931-7b43499e580f.png)

Ran `jspm install aurelia-event-aggregator` as suggested (on the esnext skeleton).  I can now see the top level dependency in package.json and config.js.  When running it now, it stops on app.js and shows the following error in the console window (of the browser):
![console](https://cloud.githubusercontent.com/assets/15125812/16456438/250ace46-3e18-11e6-8c3d-b1d9fc27df51.png)

If I remove the aggregator code (in app.js), all is well again.

**Comment by EisenbergEffect** [comment]
Can you get a stack trace on that?

**Comment by jc1001** [comment]
No sorry, when clicking on it, it shows a messagebox with text "The specified line was not found".  I'll try and change system.js to not use the minified version.

**Comment by jc1001** [comment]
Still no luck - the url that it is trying to browse to is:
view-source:http://localhost:9000/jspm_packages/system.js%20line%201544%20%3E%20eval
(Line 1544).  I'll try another browser (this was Firefox)

**Comment by EisenbergEffect** [comment]
Ok, there's something wrong with our setup. I'm just not sure what yet.
(The Aurelia HUB runs on the Aurelia RC and makes use of the EventAggregator throughout.)

**Comment by jc1001** [comment]
Ah, ok, blonde moment.  While trying different things with app.js, I didn't change everything back to normal (thank you Chrome stack trace...).  It is working now.  The problem seems to have been the top-level dependency.  Thank you very much for your trouble.  I'm hoping to eventually move to the Aurelia CLI and get rid of the jspm dependency.

**Comment by EisenbergEffect** [comment]
No problem at all. Glad you got it sorted :)
