### ISSUE TITLE
factory and options decorators are missing from declarations file

### ISSUE THREAD

**Issue by david-driscoll** [aurelia/dependency-injection#120]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.2.2

* **NPM Version:**
3.5.1

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
N/A

* **Language:**
TypeScript 2.0 (though applies to 1.8?)

**Current behavior:**

**Expected/desired behavior:**

* **What is the expected behavior?**
`factory` and `options` decorators are missing from [aurelia-dependency-injection.d.ts](https://github.com/aurelia/dependency-injection/blob/924bf5d5f1be1eca4397472be0a4c23333328837/dist/aurelia-dependency-injection.d.ts)

* **What is the motivation / use case for changing the behavior?**
`factory` and `options` decorators should not be missing as they exist in the source.

    * [`factory`](https://github.com/aurelia/dependency-injection/blob/924bf5d5f1be1eca4397472be0a4c23333328837/src/resolvers.js#L367-L373)
    * [`optional`](https://github.com/aurelia/dependency-injection/blob/924bf5d5f1be1eca4397472be0a4c23333328837/src/resolvers.js#L343-L354)

**Comment by SPARTAN563** [comment]
We're currently having a bugfix release held up on this, would really appreciate it being fixed ASAP.

**Comment by EisenbergEffect** [comment]
This seems to be fixed.

**Comment by david-driscoll** [comment]
@EisenbergEffect They still appear to be missing from the `d.ts` file.
https://github.com/aurelia/dependency-injection/blob/ae2fdcc578ff6fc35dc2a22b02f6f4a1f5c937d8/dist/aurelia-dependency-injection.d.ts#L254-L268

**Comment by EisenbergEffect** [comment]
I am confused. Aren't you highlighting them in the d.ts file right there?

**Comment by david-driscoll** [comment]
`factory` and `optional` are missing, the others are there.

**Comment by david-driscoll** [comment]
Sorry, I was in the wrong part of the file.

`optional` now correctly exists, `factory` is still missing.

It's declared @ https://github.com/aurelia/dependency-injection/blob/ae2fdcc578ff6fc35dc2a22b02f6f4a1f5c937d8/src/invokers.js#L13-L22

**Comment by EisenbergEffect** [comment]
`optional` is present in the latest release. For some reason `factory` is not. I'm not sure how that would happen. That's very odd.

**Comment by EisenbergEffect** [comment]
In see the problem. This is an issue where a duplicate name crept in somehow. I'll need to think about how we are going to solve this and if we can do it without making a breaking change.

**Comment by EisenbergEffect** [comment]
@SPARTAN563 Can you describe the details of your situation? I need to know in order to guide me on how to fix the issue. The problem is that we've got two different decorators called `factory`. I need to pick the right one for backwards compat.

**Comment by SPARTAN563** [comment]
At the moment we don't have this deployed to production, so go ahead and do whatever you need to do.

The use case is that we have a couple of classes which need to be instantiated multiple times with context specific values as well as DI services.

The following is an example of how this is done (rather than the actual code being held up by this). If you are interested in discussing better ways of accomplishing this (as opposed to the `@skipParams` decorator, I'd be very interested in doing so, as it is a relatively common issue from what I've heard when discussing Aurelia's DI framework in more complex scenarios.

```typescript
interface PersonFactory {
  new (id: number): Person;
}

@autoinject
@skipParams(1) //Custom decorator which skips the last N constructor params for DI
class Person {
  constructor(protected personAPI: PersonAPI, public id: number) {

  }
}

class PeopleProvider {
  constructor(
    private @factory(Person) personFactory: PersonFactory,
    private personAPI: PersonAPI
  ) {

  }

  getPeople(): Promise<Person[]> {
    return this.personAPI.list()
      .then(people => people.map(p => new this.personFactory(p.id))
  }
}
```

**Comment by EisenbergEffect** [comment]
Ok. We will get this fixed and released this week.
