### ISSUE TITLE
Incorrect for-loop in @autoinject

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/dependency-injection#121]
**I'm submitting a bug report**

* **Library Version:**
1.0.0 and current code on GitHub

The code below is the *current* implementation of the `@autoinject` decorator.
Looking at the `for`-loop, the intention here clearly was to automatically add the types for any parameters that are not already explicitly added to the `target.inject` array - that seems like a very reasonable behavior, and in fact one that is critical to work I'm currently doing.

Unfortunately, there's a bug in that `for`-loop - it should be:
```typescript
      for (let i = 0; i < autoInject.length; i++) {
```

```typescript
/**
* Decorator: Directs the TypeScript transpiler to write-out type metadata for the decorated class.
*/
export function autoinject(potentialTarget?: any): any {
  let deco = function(target) {
    let previousInject = target.inject;
    let autoInject: any = metadata.getOwn(metadata.paramTypes, target) || _emptyParameters;
    if (!previousInject) {
      target.inject = autoInject;
    } else {
      for (let i = 0; i++; i < autoInject.length) {
        if (!previousInject[i]) {
          previousInject[i] = autoInject[i];
        }
      }
    }
  };

  return potentialTarget ? deco(potentialTarget) : deco;
}
```
**Current behavior:**
*No* parameter types are automatically added, if *any* types have already been added.

**Expected/desired behavior:**
Any *Missing* parameter types should be automatically added.

**Comment by Sayan751** [comment]
Apart from the `for`-loop, I am little bit confused with the if-else block. Does this mean that it will consider only the `inject`s from the `super` class, considering the `class` is in an inheritance chain, and not the ones which is injected at this class level?

**Comment by oneillci** [comment]
:+1: I have also noticed this issue in upgrading from beta to release.
On derived classes, the `@autoinject` attribute only injects the dependencies that are specified in the base class constructor. Any additional dependencies in the derived class are `undefined`.

I have resorted to using `@autoinject` on my base classes and any derived classes where I require additional dependencies I have now back to using `@inject`

**Comment by ariovistus** [comment]
If the for loop were to be fixed as recommended, the code would still not work for inheritance hierarchies. For
```
@autoinject
class Base {
   constructor(a: A) {
   }
}
@autoinject
class Derived1 extends Base {
  constructor(b: B, a: A) {
     super(a);
  }
}
@autoinject
class Derived2 extends Base {
  constructor(c: C, b: B, a: A) {
    super(a);
  }
}
```

the for loop would overwrite Base's inject with Derived1 and Derived2's in some order, which would cause injection to fail for all three.

I guess autoinject is not meant to work with inheritance hierarchies?

**Comment by henning-krause** [comment]
Well, it did work in the beta of Aurelia. I'm still stuck on the beta bits because of this issue.

**Comment by EisenbergEffect** [comment]
If someone would like to submit a PR to fix this issue, we can get it in and release pretty quickly. This is a great opportunity to contribute.
