### ISSUE TITLE
Combining @inject and @autoinject results in undefined dependencies

### ISSUE THREAD

**Issue by stefan505** [aurelia/dependency-injection#123]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
4.5 LTS

* **NPM Version:**
3.8.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.45

* **Browser:**
all

* **Language:**
TypeScript 2.0 RC

**Current behavior:**
When combining `@inject` and `@autoinject` results dependencies to be undefined.

**Expected/desired behavior:**
The below example shows the dependencies for a class:

```
@inject(NewInstance.of(ValidationController))
@autoinject()
export class UserSetup implements Callable
{
    constructor(
        private _taskQueue: TaskQueue,
        private _i18n: I18N,
        private _observer: ObserverLocator,
        public controller: ValidationController)
    {
    ...
```

In runtime, `_taskQueue` is the only instantiated member, but its not an instance of TaskQueue, instead its an instance of ValidationController. All the other dependencies are undefined, including `controller`.

* **What is the expected behavior?**
All instances should be resolved correctly.

* **What is the motivation / use case for changing the behavior?**
This use to work previously.

**Comment by StrahilKazlachev** [comment]
As far as I remember `@inject` and `@autoinject` should not be used together.

**Comment by stefan505** [comment]
> As far as I remember @inject and @autoinject should not be used together.

This working fine up until very recently. I can get around it, but just wanted to clarify first.

**Comment by EisenbergEffect** [comment]
Using `autoinject` and `inject` together is not supported.
