### ISSUE TITLE
[Feature] Manual inject alternative

### ISSUE THREAD

**Issue by khenderick** [aurelia/dependency-injection#125]
**I'm submitting a feature request**

* **Library Version:**
1.0.0

* **Language:**
ESNext

**Current behavior:**

I'm using aurelia-i18next so I have a page like this:

```
import {inject} from "aurelia-framework";
import {BindingSignaler} from "aurelia-templating-resources";
import {I18N, BaseI18N} from "aurelia-i18n";
import {EventAggregator} from "aurelia-event-aggregator";
import {API} from "../components/api";
import {OutputFactory} from "../containers/output";

@inject(API, BindingSignaler, I18N, Element, EventAggregator, OutputFactory)
export class Outputs extends BaseI18N {
    constructor(api, signaler, i18n, element, ea, outputFactory) {
        super(i18n, element, ea);
        this.api = api;
        ...
    }
}
```

A certain set of my pages has similar functionality, so I want to create some ```export class ModulePage extends BaseI18N``` so the above page could extend ```ModulePage```.

However, as I might have e.g. 10 pages extending ```ModulePage```, they all need to inject the classics like ```I18N```, ```Element``` and ```EventAggregator```, just because down the line, they all extend from ```BaseI18N```. The ```@inject(...)``` line gets longer and longer, and it doesn't enhance readability.

**Expected/desired behavior:**

Assume I have some ```manualInject(...)``` or something, I could make something like this:

```
import {manualInject} from "aurelia-framework";
import {I18N, BaseI18N} from "aurelia-i18n";
import {EventAggregator} from "aurelia-event-aggregator";
import {BindingSignaler} from "aurelia-templating-resources";
import {API} from "../components/api";

export class BasePage extends BaseI18N {
    constructor() {
        super(
            manualInject(I18N), 
            manualInject(Element), 
            manualInject(EventAggregator)
        );
        this.api = manualInject(API);
        this.signaler = manualInject('BindingSignaler');
    }
}
```

```
import {manualInject} from "aurelia-framework";
import {OutputFactory} from "../containers/output";
import {BasePage} from "./basepage";

export class Outputs extends BasePage {
    constructor() {
        super();
        this.outputFactory = manualInject(OutputFactory);
        ...
        // In this class, things like this.api are also available.
    }
}
```

This makes the code much cleaner imo. In the above example, technically, I wouldn't even need the OutputFactory anymore, since I have to use this to make sure I can generate an Output instance with a given identifier and still inject the API. This would allow something like this:

```
...
export class Output {
     constructor(id) {
         this.api = manualInject(API);
         this.id = id;
         this.name = undefined;
     }
     load() {
          this.name = this.api.loadOutputName(this.id); // This is a simplified example
     }
}
```

**Comment by jdanyow** [comment]
I think `container.get(...)` is what you're looking for:

```js
@inject(Container)
export class Foo {
  constructor(container) {
    super(container.get(Foo), container.get(Bar), container.get(Baz));
  }
}
```

Word of caution:  this is an anti-pattern. It violates the [dependency inversion principle](https://en.wikipedia.org/wiki/Dependency_injection)

**Comment by khenderick** [comment]
It's still using the ```@inject(...)``` causing the fact that other code that needs some Foo instance cannot just create a ```new Foo(1234);``` (assuming Foo would need such identifier). I would need to be able to just import that container. But I assume I could make a plain simple singleton instance, inject the container into it and then use this ```SomeSingleton.container.get(Bar)``` to solve this

However, I'm not sure how it violates the dependency inversion principle (but that will most likely my lack of knowledge) since in your example (where Foo would extend e.g. ```SubFoo``` or whatever), dependencies are still externally managed; in testing I would assume that I still can alter or influence what ```container``` would return. When I would for example use ```container.get(API)```, in testing I could still change ```API``` to be some mocked version, so ```container.get(API)``` would return this mocked API.

**Comment by Thanood** [comment]
Do you have to `@inject`, though? There's a `Container.instance` property but I'm not sure if that's supposed to be used. 😃

**Comment by jdanyow** [comment]
@khenderick this violates the dependency inversion principle because it manually retrieves it's dependencies instead of advertising them via `@inject`:

```js
@inject(Container)
export class Foo {
  constructor(container) {
    super(container.get(Bar), container.get(Baz));
  }
}
```

@Thanood that would work, most of the time. If your class was a view model, and your dependency is `Element` or something else specific to the custom element instance, it won't work because `Container.instance` is the top-level, "root" container.  Custom elements/attributes are constructed with a child container instance that has been pre-configured with contextual items like `Element`.

I strongly recommend not using `Container.instance` and the patterns discussed here.

**Comment by jdanyow** [comment]
For the `new Foo(1234)` case- check out the `Factory` resolver: http://stackoverflow.com/questions/34793723/assisted-injection-in-aurelia

**Comment by khenderick** [comment]
```
@inject(Foo, Bar)
export class Abc {
  constructor(foo, bar) {
    this.foo = foo;
    this.bar = bar;
  }
}
```

This means sth like "Dear ```@inject()``` (aka, dear dependency-injection), please provide me with your instances of ```Foo``` and ```Bar``` and pass them into my constructor. I'll assign them to internal properties".

```
export class Abc {
  constructor() {
    this.foo = manualInject(Foo);
    this.bar = manualInject(Bar);
  }
}
```

This means sth like "Dear ```manualInject()``` (aka, dear dependency-injection), please provide me with your instances of ```Foo``` and ```Bar```. I'll immediately assign them to internal properties".

I don't see any difference; it's still a dependency injection system that provides me with the instances itself, right? I mean, in the end, using ```@inject()```, it's the final class that will have a list of all injected instances and they will be passed through down the line. And when you want to e.g. change ```API``` with some mocked version, I assume your test would start with making sure that the dependency injection will provide an instance of some ```MockAPI``` instead of ```API``` when running the tests. So no need to update any code. Not when using ```@inject()```, not when using ```manualInject()```.

**Comment by khenderick** [comment]
The only difference I see is that with ```@inject()``` when passing the dependencies from constructor to constructor, a class might actually instead of passing on an instance to it's ```super```, create some new or other instance and pass that along. While with ```manualInject()```, it will always be the dependency injection which is in charge of the instance that will eventually end up where it belongs.

**Comment by Thanood** [comment]
@jdanyow Thanks for clarifying.. Then I need to find another way to inject things in my strange setup.. :wink:

@khenderick Property injection has been discussed: https://github.com/aurelia/dependency-injection/pull/85
Seems there's a plugin for that: https://www.npmjs.com/package/aurelia-property-injection

**Comment by jdanyow** [comment]
This is a really really really common mistake with DI. Everyone, myself included has gotten this wrong one time or another.

This:
```js
@inject(Foo, Bar)
export class Abc {
  ...
```
Means *To whom it may concern, I depend on Foo and Bar*.

This is very flexible, especially in JavaScript:
* you can use the class without the container (in tests)
* you can supply mocks to the class without configuring a container
* you can use the class with other container implementations
* different container instances can instantiate your class (this is how `@inject(Element)` works in Aurelia... a child container is constructing your view model class).

On the other hand, this:

```js
export class Abc {
  constructor() {
    this.foo = manualInject(Foo);
    this.bar = manualInject(Bar);
  }
}
```

Is a black box. It's incompatible with `@inject(Element)` and the rest of the items I mentioned above.

**Comment by khenderick** [comment]
@Thanood, this is interesting and more or less looks exactly as the thing I'm requesting here.

@jdanyow, I understand your point (and especially the issue with ```Element```). However, since in the PR referenced by @Thanood had quite some positive input from the Aurelia team, I would think it's implementation is at least a lot better than what I was suggesting here. Or does that plugin also face the same issues as you describe here (especially the issue with ```Element```)?

**Comment by EisenbergEffect** [comment]
If you have classes, with many dependencies, then that can be a sign that you need to refactor in some way. I tend to avoid base classes and prefer compositional patterns.

If you can't get away from all the dependencies, you could create a custom decorator that automatically applied the standard injected dependencies.
