### ISSUE TITLE
Aurelia DI configuration class a la Spring @configuration

### ISSUE THREAD

**Issue by dryajov** [aurelia/dependency-injection#127]
I'm trying to figure out how to create a configuration class similar to what you would do with spring in Aurelia. The use case is to basically have consumed modules that provide functionality such as persistence to manage their own configuration (creating connections, registering dependencies, etc...).

In spring, you can have something like this (pseudocode, hasn't been tested):

```javascript
    @Configuration
    class Config {
        @Bean
        public Connection createConnection(string cnt) {
          // TODO: create connection
        }
    }
```

The above code would execute the `createConnection` method and register a connection with the container, and also pass the `cnt` connection string variable when calling the method. 

I believe I can do something like the following:

```javascript
    export class Dependencies {
        public configure(container: Container): void {
            let cnt: string = container.get('cnt');
            container.registerSingleton(Connection, () => {
               // TODO: create connection
            })
        }
    }
```

And then call this somewhere else like so:

```javascript
    class App {
       constructor(dependencies: Dependencies) {
           dependencies.configure(this.container, this.cnt);
       }
    }
```

The problem with this approach, is that configuration becomes explicit, and you have to know what the configuring class is named, what methods to call, as well as when to call it, since you want your connection string to be registered before creating a connection. 

IMHO, having an explicit configuration step makes thing less tightly coupled. Also, having a way of providing dependencies by way of a factory method also makes configuration easier and more 'ergonomic'. 

In summary, my two questions are:

 1. Is it possible to have an explicit configuration `@configuration` step, like `@singleton` or `@transient`?
 2. How do I register dependencies through a factory method/function, preferably using a decorator?

PS:

This was asked on stackoverflow, but hasn't been answered yet - http://stackoverflow.com/questions/39777074/aurelia-di-configuration-class-a-la-spring-configuration

I believe that the answer to this questions is that's currently not possible. I've got an accompanying PR coming shortly that implements this functionality. But any insights on alternatives would be appreciated.

EDIT:

To give more context, we're using this as a standalone module in a node backend app, so far it's working as expected, but some ability to allow submodules to configure them selfs is the thing that is lacking, hence this issue.

EDIT2: 

Another issue is, I've yet not seen a way of using child containers with decorator registration (`@singleton`, `@transient`), is there any documentation/example regarding how that works?

**Comment by EisenbergEffect** [comment]
Internally, the Container represents everything in terms of Resolver instances. You can actually create your own and register them with the Container using `registerResolver`. There is also another method that lets you register custom functions called `registerHandler`. Have you looked at either of these to handle your use case?

**Comment by dryajov** [comment]
Hmm... I've seen resolvers being used like this: 

```javascript
@autoinject
class App {
  private connection: Connection;
  constructor(@lazy(Connection) connectionFactory: Connection) {
    this.connection = connectionFactory(); // calls a factory to create the connection
  }
}
```

But I want to use the following syntax:

```javascript
@config
class Config {
  @singleton
  public createConnection(): Connection {
   // return a connection
  }
}

@autoinject
class App {
  constructor(private connection: Connection) {
    this.connection.performAwesomeQuery(); // use connection
  }
}
```

**Comment by EisenbergEffect** [comment]
Those are using resolvers, but you can also create our own to perform custom resolution. Take a look in the DI repo, in the resolvers.js fie to see an example of how things like singleton are built. You would only need to create config resolver that did what you wanted.

**Comment by dryajov** [comment]
OK, I have a rough implementation of the above mentioned syntax and going to create a PR for it shortly. I was not able to get `@singleton` decorators to work on methods only on classes, without modifying the registration a bit. It ended up being a somewhat convoluted and probably ultimately wrong, but it seems to work at least. Thanks for the quick turnaround.

**Comment by EisenbergEffect** [comment]
I don't think we would accept a PR to add this to the core. We are trying to keep that as small as we can. However, I think it would be a great contribution to the documentation or a blog post. I'd be happy to work with you as an editor if you wanted to be featured on the Aurelia official blog doing an article on IoC extensibility for example.

**Comment by dryajov** [comment]
Not sure how this could be implemented without touching the core. What are the criteria under which you accept PR to the core?

**Comment by EisenbergEffect** [comment]
For something like DI, it's pretty tight because changes there affect absolutely everything. Mostly we would accept PRs there that create extensibility points to enable more scenarios without affecting performance or breaking existing apis.

**Comment by CasiOo** [comment]
You could of course write a provider to get the dependency with any special setup it needs. But that's not what you're looking for?
```
@inject(ConnectionProvider)
class App {
    constructor(connectionProvider) {
        this.connection = connectionProvider.get();
    }
}
```
So your goal is to inject the dependency, without having to specify the resolver, and with some custom configuration?

Injecting `@inject(Connection)` should call your custom resolver, which will configure the Connection, but without having to implement and register a bunch of different resolvers for each type?

I might be totally wrong about this, but I just scratched something down in notepad++ (untested).

Somewhere in main.js
```
var applicationModule = container.get(ApplicationModule);
applicationModule.registerHandlers(container);
```

And your custom module
```
import { ConnectionConfig, Connection } from './connection';
import { PayPalCreditCardProcessor } from './paypal-credit-card-processor';

@inject(ConnectionConfig)
class ApplicationModule {
    
    constructor(connectionConfig) {
        this.connectionConfig = connectionConfig;
    }
    
    registerHandlers(container) {
        container.registerHandler(Connection, this.createConnection.bind(this));
        container.registerHandler(PayPalCreditCardProcessor, this.createPayPalCreditCardProcessor.bind(this));
        // Alias for injecting a PayPalCreditCardProcessor
        container.registerAlias(createPayPalCreditCardProcessor, 'PayPal');
    }
    
    createConnection(container, key, strategyResolver) {
        var connectionString = this.connectionConfig.connectionString;
        return new Connection(connectionString);
    }
    
    createPayPalCreditCardProcessor(container, key, strategyResolver) {
        return new PayPalCreditCardProcessor({
            endPoint: 'https://paypal.com'
        });
    }
}
```

Have I misunderstood how handlers work and what they are? I hope not haha.

I don't know if it's possible to register multiple types for a single resolver instance, otherwise that might be a solution as well.

**Comment by dryajov** [comment]
@CasiOo thanks for the examples. I think this is close to what I outlined as a possible way of doing this in my original question. Where I have a `Dependencies` class with an explicit configure/register method that gets explicitly called by the main app, which is fine and servers the purpose, however this creates a bit of a tight coupling between child and parent modules, where the parent has to know which module exposes a `Dependencies` class and which method to call on that class. Hence my proposal of allowing an addition `@config` phase, that runs automatically at some early point during the container instantiation and a allows the class to get/add things to the container. This is in addition to allowing `@singleton` and `@transient` registrations to be applied to the config (or any other) class methods, which allows using factory methods to register dependencies with the container - instead of calling `container.registerSingleton(MyType)` I can do:

```javascript
@config
class Config {
  constructor(private dep1: Dep1, private dep2: Dep2){
  }

  @singleton
  public getDep3(): Dep3 {
    return new Dep3(this.dep1, this.dep2);
  }
}
```

I want to point out, that this is mostly syntactic sugar on top of already existing functionality - this isn't fundamentally changing what you can do with the container, other than streamlining it for certain use cases than otherwise would end up being add hoc.

**Comment by dryajov** [comment]
@EisenbergEffect I'd happily implement this as an add on, but I'm not sure what the extensibility points would be. We're basically talking about modifying existing registration hooks and adding a new one (@config). I'm aware of aurelia-property-injection and would be OK implementing this as a stand alone plugin similar to that, but it doesn't seem like it would be possible to mix and match multiple plugins. It looks like aurelia-property-injection simply wraps aurelia-dependency-injection, and there is no way of extending aurelia's DI without doing just that, wrap it. I might not have the complete picture, so let me know if I'm missing something. I'd be glad to help either way.

**Comment by dryajov** [comment]
@CasiOo @EisenbergEffect #128 - merge request for that _tries_ to implement the proposed functionality.

**Comment by dryajov** [comment]
@EisenbergEffect Can we reopen this issue, seems like it's a valid discussion.

**Comment by EisenbergEffect** [comment]
I would prefer to discuss in the context of the actual PR.

**Comment by dryajov** [comment]
This functionality is now implemented in [aurelia-factory-methods](https://github.com/dryajov/aurelia-factory-methods).
