### ISSUE TITLE
allow testing language specific functionality

### ISSUE THREAD

**Issue by dryajov** [aurelia/dependency-injection#133]
**I'm submitting a feature request**
- **Library Version:**
  1.1.0

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11.6 
- **Node Version:**
  v6.5.0
  
  
- **NPM Version:**
  3.10.7
  
  
- **JSPM**
  JSPM 0.16.45
  
  
- **Language:**
  TypeScript 2.0.2

**Current behavior:**
The current unit tests don't seem to test decorators with the implicit invocation syntax`@`. Furthermore, for typescript (and possibly other supported languages), there is no way to test some language specific decorator functionality. For example, typescript allows using method level decorators, which are invoked with a different set of parameters than when used on a class level, same goes for property level decorators.

**Expected/desired behavior:**

- **What is the expected behavior?**
  Allow testing language specific syntax/functionality.
- **What is the motivation / use case for changing the behavior?**
  Since multiple languages are supported, it would be desirable to enable testing some language specific functionality. 

I understand the motivation of keeping the core as clean and language agnostic as possible, however, I think it's still useful to add some language specific unit tests. One solution might be using test projects for language specific tests. I understand this might be unorthodox, however it enables a) keeping the core clean from language specific settings/tests and b) still test some level of language specific functionality.

**Comment by EisenbergEffect** [comment]
We won't be able to address this in this version. For vNext, we're moving to TypeScript and will be updating to the new decorators spec. The new DI is already implemented in the experiment repo. We're only waiting on the TS team to update their decorators implementation.
