### ISSUE TITLE
Provide type for resolvers

### ISSUE THREAD

**Issue by Gheoan** [aurelia/dependency-injection#134]
**I'm submitting a feature request**

* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Language:**
TypeScript 2.0

**Current behavior:**
```ts
class DependsOnMyClass {
  static inject = [Factory.of(MyClass)];
  constructor(myClassFactory: Factory) {
    myClassFactory(config); // Cannot invoke an expression whose type lacks a call signature.
  }
}
```
`myClassFactory`'s type is actually `(...rest: any[]) => MyClass`.

**Expected/desired behavior:**

* **What is the expected behavior?**

I would like to import a generic type from DI for resolvers. 
```ts
import { factoryResolver } from 'aurelia-framework';
class DependsOnMyClass {
  static inject = [Factory.of(MyClass)];
  constructor(myClassFactory: factoryResolver<MyClass>) {
    myClassFactory(config); // Cannot invoke an expression whose type lacks a call signature.
  }
}
```
I am looking for suggestions on how to name these types.
```ts
export interface factoryResolver<T> {
  (...rest: any[]): T;
}
```

* **What is the motivation / use case for changing the behavior?**
Reusing of types.

**Comment by EisenbergEffect** [comment]
They are just functions.

**Comment by EisenbergEffect** [comment]
I would just type them on a case by case unless you have the same case repeatedly, then you could use the interface. It's up to you though.

**Comment by n2liquid** [comment]
I'm sorry to post on an old issue, but it took me a while to understand the wisdom in Eisenberg's words ("They are just functions"), and this might help someone who (like me) stumbles upon this issue:

```
import { factoryResolver } from 'aurelia-framework';
class DependsOnMyClass {
  static inject = [Factory.of(MyClass)];
  constructor(myClassFactory: Function) {
    myClassFactory(config); // Works just fine, no type errors here.
  }
}
```
