### ISSUE TITLE
autoinject cannot be combined with inject

### ISSUE THREAD

**Issue by 7Pass** [aurelia/dependency-injection#135]
**I'm submitting a bug report**
- **Library Version:**
  1.2.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.9.0
- **NPM Version:**
  3.10.8
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.22
- **Browser:**
  Chrome 55
- **Language:**
  TypeScript 2.0.3

**Current behavior:**
Aurelia injects incorrect dependencies when `@inject` is used in constructor together with `@autoinject`.

**Expected/desired behavior:**
`@inject` should work in combination with `@autoinject`, especially in case of Element, which needs to have `@inject(Element)`.

I've try reverting back to 1.1.0 and it's working again. I suspect that the error was caused by recent change to https://github.com/aurelia/dependency-injection/blob/master/src/injection.js#L18

**Comment by 7Pass** [comment]
For example, with the following TypeScript code:
```
@autoinject
export class Test {
    constructor(
        private service: MyService,
        @inject(Element) element: Element,
    } { }
}
```

Version 1.1.0 correctly inject `[MyService, Element]`, while version 1.2.0 incorrectly inject `[MyService, Object, Element]`.

**Comment by EisenbergEffect** [comment]
If that worked, it was accidental and probably indeterminate. These two were never intended to be used together.

**Comment by 7Pass** [comment]
I'd love to have that working again. Most of the time, everything can be `autoinject`ed, except for Element, which needs `@inject(Element)`. Without being able to use `autoinject` together with `inject`, the constructor will be loaded with `@inject` as soon as Element is needed.

However, I read from the Hub documentation that `autoinject` does not really needed, if any other attribute is used so that TypeScript will output decorators. Does that mean I can just remove `@autoinject` and that will work correctly again?

**Comment by EisenbergEffect** [comment]
Give it a try :)

**Comment by 7Pass** [comment]
So my findings:
* `@lazy` still need to have `@autoinject`, otherwise, the other dependencies won't get injected correctly.
* `@inject` does not play nice with `@autoinject`. Remove `@autoinject` allows `@inject` to work.
* When there're both `@inject` and `@lazy`, remove `@autoinject`.

**Comment by 7Pass** [comment]
Sorry, I think I'm lost. When tried with my actual project:
* `@autonject` with `@lazy`: `@lazy(HttpClient)` injects `function() {}`.
* `@lazy` without `@autoinject`: no inject happens.

I'll try to setup a repo with the issue and update this issue when it's ready.

**Comment by 7Pass** [comment]
I'm sorry that I don't know how to create unit tests, can anyone help to create test for the following cases:

```
import {autoinject} from "aurelia-framework";
class DependencyA { }
class DependencyB { }

@autoinject
class TestBase {
  constructor(private a: DependencyA) { }
}

@autoinject
class TestChild extends TestBase {
  constructor(
    b: DependencyB,
    a: DependencyA,
  } { }
}
```
Expected: instance of `TestBase` gets `a` of type `DependencyA`. Bug: `TestBase` gets `a` with value of `DependencyB`.

```
import {lazy} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";
import {EventAggregator, Subscription} from "aurelia-event-aggregator";

export class MyService {
  constructor(
    private events: EventAggregator,
    @lazy(HttpClient) private lazyHttp: () => HttpClient
  } { }
}
```
Expected: `MyService` gets `events` of type `EventAggregator`. Bug: `MyService` get `events` of type `Object`.

**Comment by PWKad** [comment]
Does not feel like this should be supported, too much magic for my liking.  How would you, for instance, know which order that they should be injected?

```es6
import {inject, autoinject} from 'aurelia-dependency-injection';
import {ExampleTwo} from './example-two';
import {ExampleThree} from './example-three';

@inject(Element)
@autoinject
class MyExample {
  static = [ExampleTwo];
  constructor(exampleTwo, element, exampleThree: ExampleThree) {}
}
```

Those things are going against each other, just seems kind of odd to support those things together IMHO.

**Comment by ZoolWay** [comment]
I agree that it does not feel like making sense. Either specify all injection or have all resolved automatically.
Also I want to add that I never had a problem injecting `Element` with `@autoinject` - it works as it should.

**Comment by 7Pass** [comment]
@ZoolWay is that something new? Problem with `Element` is a known issue that bugs me so much, see https://github.com/aurelia/dependency-injection/issues/77

**Comment by ZoolWay** [comment]
@7Pass hmm, strange. I never had the problem that. Using `@autoinject` with `Element` since 6/10/2016 as I see in my history. So not sure why Rob says it cannot work. But I am not using in-browser-transpiling and I am targetting ES6 - maybe that is the reason.

**Comment by AdamWillden** [comment]
FWIW `@autoinject()` with `Element` works for me too. 

I'm with @PWKad, at first I thought this to be a good idea but now I just don't see how it could work.

----

I never use the class decorator style `@inject(One, Two, Three)` now. For me, the moment that `@autoinject` is no longer an option (i.e. I need `@factory`, or `@newInstance`, etc) I just use `@inject` as a parameter decorator instead:

```ts
export class DmaMiniStatus {
  constructor(
    @inject(AwaitAction) public dmaLoadingAction: AwaitAction,
    @inject(AwaitAction) public loggersLoadingAction: AwaitAction,
    @inject(DistrictMeteringAreaRepository) private dmaRepository: DistrictMeteringAreaRepository,
    @inject(LoggerRepository) private loggerRepository: LoggerRepository,
    @newInstance(DistrictMeteringAreaContainer) private dmaContainer: DistrictMeteringAreaContainer,
  ) {
// ...
```

Until I found this thread some time ago, I didn't realise that using `@inject` as a parameter decorator was a possibility, so thanks.

**Comment by 7Pass** [comment]
Closing issue since it's by design.
