### ISSUE TITLE
autoinject is changing inject of parent class and child classes of parent class

### ISSUE THREAD

**Issue by kdeberni** [aurelia/dependency-injection#136]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
4.6.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.0-beta

* **Browser:**
all

* **Language:**
TypeScript 1.8

**Current behavior:**

Case:
```typescript
@autoinject
class Parent {
constructor(logger: Logger) {}
}

@autoinject
class ChildA extends Parent {
  constructor(logger: Logger, serviceA: ServiceA) {
    super(logger);
  }
}

@autoinject
class ChildB extends Parent {
  constructor(logger: Logger, serviceB: ServiceB) {
    super(logger);
  }
}
```
In this case when class ChildA is created then ServiceB is injected to constructor parametr serviceA.
The reason of this is because autoinject function changes the inject of parent class.

**What is the expected behavior?**

ServiceA should be injected in constructor of ChildA class.

I forked the project and add a test for autoinject which does not pass. I also "fixed" the autoinject function but I am not sure what was the idea behind previousInject checking and if my fix is correct. I mean after fix my autoinject test passes but I am not sure if the fix does not corrupt the main idea. 
Here is the code of fixed function:
```javascript
export function autoinject(potentialTarget?: any): any {
  let deco = function(target) {
    let previousInject = target.inject ? target.inject.slice() : null; //my change
    let autoInject: any = metadata.getOwn(metadata.paramTypes, target) || _emptyParameters;
    if (!previousInject) {
      target.inject = autoInject;
    } else {
      for (let i = 0; i < autoInject.length; i++) {
        //check if previously injected.
        if (previousInject[i] && previousInject[i] !== autoInject[i]) {
          const prevIndex = previousInject.indexOf(autoInject[i]);
          if (prevIndex > -1) {
            previousInject.splice(prevIndex, 1);
          }
          previousInject.splice((prevIndex > -1 && prevIndex < i) ? i - 1 : i, 0, autoInject[i]);
        } else if (!previousInject[i]) {//else add
          previousInject[i] = autoInject[i];
        }
      }
      target.inject = previousInject; //my change - added line
    }
  };

  return potentialTarget ? deco(potentialTarget) : deco;
}
```
If this is correct I can make a PR.

**Comment by EisenbergEffect** [comment]
I humbly disagree. The behavior you suggest would be confusing. It means injecting something different into ChildB for the sake of ChildA. And what if there's an inheriticane relationship between the two and it's actually ok to substitute? We aren't going to change that. We inject whatever the instantiated class declares: since ChildB declares Logger and ServiceB, that is what it gets. I strongly advise against any architecture that attempts to work as you have above. It greatly obscures intent and is very confusing.

**Comment by kdeberni** [comment]
I am not sure if I understood everything. ChildA is asking for ServiceA and Logger and it is getting ServiceB and Logger. Isn't that wrong?

**Comment by EisenbergEffect** [comment]
Wait...are you saying that when you try to create ChildA directly, you are getting the deps of ChildB? I may have misunderstood you. Can you help me understand by clarifying a bit more?

**Comment by kdeberni** [comment]
Exactly as you say.
When ChildB is created everything is OK. However, when ChildA is created it gets deps of class ChildB.

**Comment by EisenbergEffect** [comment]
Ok. I was confused originally. Can you submit the PR? I'll review it and we can make any changes there.
