### ISSUE TITLE
@inject(NewInstance.of(MyClass)) doesn't work with Container.registerInstance/Handler.

### ISSUE THREAD

**Issue by RichTeaTime** [aurelia/dependency-injection#137]
I'm submitting a bug report.
Library Version: 1.0.5
Operating System: Windows 8.1
Browser: IE 11/Firefox/Chrome
Language: Typescript 2.0

**Current behavior:**

When using
`Container.registerHandler(MyClass, c => new MyMock());`

I am currently able to have my mocked instance injected into components using either

```
@autoinject
constructor(my:MyClass) {
  console.log(my);
}
```

or

```
@inject(MyClass)
constructor(my) {
  console.log(my);
}
```

result:
`my mock class`

However, when I use the NewInstance function, e.g.

```
@inject(NewInstance.of(MyClass))
constructor(my) {
  console.log(my);
}
```

result:
`my real class`

This appears to be caused by a difference in the way that the two dependencies are resolved. For the regular `@inject`, `Container.get` is used, and this queries `this._resolvers.get(key);`
For the `NewInstance.of`, `Container.invoke` is used, and this does not query `this._resolvers`.

**Expected/desired behavior:**

```
@inject(NewInstance.of(MyClass))
constructor(my) {
  console.log(my);
}
```

result:
`my mock class`

Gist of correct, expected behavior with @inject - https://gist.run/?id=6e639dbe06c172345a9ea498ed3e17bd
Gist, adding the NewInstance.of in component.js - https://gist.run/?id=f786c93f86ba8b22a323bfe50e176210
- **What is the motivation / use case for changing the behavior?**
  `@inject` should work correctly with `registerHandler` regardless of whether a new instance of that injected class is created via the `NewInstance.of` method. The `NewInstance` class should re-call `registerHandler` to create a new instance.

**Comment by EisenbergEffect** [comment]
This sounds like a legitimate bug. Thanks for the repro.

**Comment by RichTeaTime** [comment]
No problem. I'm not clear what the expected behavior is for container.registerInstance though? A deep copy? (like jQuery's $.extend(obj, true))

As an aside, I assume the only way to get the NewInstance'd reference to a sub-component of the one injected into, is to pass it as an attribute.bind? I can't see a way to do it via DI?

**Comment by enrico-padovani** [comment]
I've got the update and with v 1.1.0 used to work but with 1.2.0 don't. This brakes all of my form validation and HttpClient settings. Any news? For now I've rolled back to 1.1.0.

Cheers :)

**Comment by MaximBalaganskiy** [comment]
Not sure if it's related but I used to be able to do this
```
export class Login {
	constructor(@newInstance() private validationController: au.ValidationController) {}
}
```
Now it does not work - injected instance is not registered for the current scope, therefore validation does not see it.

**Comment by heruan** [comment]
This is pretty serious, updating `dependency-injection` broke all `registerHandler`s. Seems like having `container.registerHandler("my-key", handler)` is no more inherited by child containers.

For example, I register a handler for a customer `ValidationRenderer` in the `configure` function of a plugin, but then when using the `validation-renderer` custom attribute with the handler key, resolvers for the current container are empty and it throws a `TypeError`.

@EisenbergEffect any change to get this fixed soon?

**Comment by heruan** [comment]
Seems like something failing here: [src/container.js#L357](https://github.com/aurelia/dependency-injection/blob/1.2.1/src/container.js#L357)
```javascript
if (resolver === undefined) {
      if (this.parent === null) {
        return this.autoRegister(key).get(this, key);
      }

      let registration = metadata.get(metadata.registration, key);

      /** TypeError here! **/

      if (registration === undefined) {
        return this.parent._get(key);
      }

      return registration.registerResolver(this, key, key).get(this, key);
    }
```
with this `TypeError`:
```
app.bundle.js:112 ERROR [app-router] TypeError
    at Object.getOwnMetadata (app.bundle.js:59)
    at Object.getOwn (app.bundle.js:64)
    at Object.get (app.bundle.js:64)
    at Container.t.Container.Container.get (app.bundle.js:110)
    at ValidationRendererCustomAttribute.bind (app.bundle.js:119)
    at Controller.t.Controller.Controller.bind (app.bundle.js:117)
    at View.t.View.View.bind (app.bundle.js:116)
    at With.t.With.With.valueChanged (app.bundle.js:119)
    at With.t.With.With.bind (app.bundle.js:119)
    at Controller.t.Controller.Controller.bind (app.bundle.js:117)
```
when `key` is a string (at least in my scenario).

**Comment by jdanyow** [comment]
@heruan https://github.com/aurelia/metadata/pull/48

**Comment by heruan** [comment]
Thank you @jdanyow I really hope this to be released soon!

**Comment by EisenbergEffect** [comment]
Most likely releasing tomorrow.

**Comment by enrico-padovani** [comment]
Hi folks,

Is there any progress on this?

**Comment by bulkan** [comment]
Hi all,

I just hit this issue as well. 

Can't seem to mock an injectable that uses `NewInstance.of`.

Is there any more updates on this issue or a workaround ?

Cheers

**Comment by bulkan** [comment]
I've had an attempt at fixing this bug and I've written this failing test case for `container.spec.js`.

```
it('can register handler when using NewInstance.of', function() {
    class Model {
        constructor() {
            this.name = 'real-model';
        }
    }

    class App {
        static inject() { return [NewInstance.of(Model)];}
        constructor(model) {
            this.model = model;
        }
    }

    class FakeModel {
        constructor() {
            this.name = 'fake-model';
        }
    }

    let container = new Container();
    container.registerHandler(Model, () => new FakeModel() );

    let app = container.get(App);
    expect(app.model.name).toEqual('fake-model');
});
```

I believe I've narrowed it down to how `NewInstance.get` when it calls `container.invoke` it can't find a handler so it creates a new one and uses that handler to create a new instance which is the original class...

I'm at a loss to where to go from here and provide a fix.

**Comment by bulkan** [comment]
For the benefit of others who end up on this issue.

I've found a workaround which involves not using `NewInstance.of` but instead creating a Factory with the help of `Factory.of`. 

Using `Factory` has the benefit of not worrying about the dependencies of the class we will instantiate new models of.

```
import { Factory } from 'aurelia-framework';

@inject(SomeService)
class MyModel {
 constructor(someService) {
   this.someService = someService;
 }
}

@inject(Factory.of(MyModel))
class MyModelFactory {
  construction(createMyModelInstance) {
    this.createMyModelInstance = createMyModelInstance;
  }
}

@inject(MyModelFactory)
export class MyService {
  construction(myModelFactory) {
    this.myModel = myModelFactory.createMyModelInstance();
  }
}
```

Now in a test I can mock out `MyModelFactory`


```
import {Container} from 'aurelia-testing';

let container = new Container();
container.registerInstance(MyModelFactory, {
   createMyModelInstance: () => return {}
});
```
