### ISSUE TITLE
Help Please: Custom Elements within a view accessing to the view's view-model.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/dependency-injection#139]
If I have a View Model (ie. not a custom-element) called Fred, like this:

    @useView( "mysampleview.html" )
    export class Fred
    {
    }

then I am of the understanding that the view-model of a _custom element_ residing within the template of that view (eg. in mysampleview.html), is able to inject the parent view-model, eg.
 
    @customElement( "mailing-address" )
    @inject( Fred )
    export class FancyMailingAddress
    {
       constructor( parent: Fred )
       {
       }
    }

Please correct me if my understanding is wrong on this count.

My specific situation is like above, but *all* of my View Models are derived from a base class, eg:

    @useView( "mysampleview.html" )
    export class Fred extends CommonViewModel
    {
    }

And I want my custom element to @inject "CommonViewModel", because it will not necessarily know which specific View is present.

This does not seem to work, and I cannot find any way to make it work. I have tried @inject'ing Container and then having the base class *constructor* of CommonViewModel perform container.registerInstance( CommonViewModel, this ), but what seems to happen is that when my custom element @injects CommonViewModel, it seems to get the previously-created view, not the current-view-being-created.

It's not really practical for me to "pass-down" CommonViewModel to custom-elements via binding expressions, since the custom elements needing the CommonViewModel could be many levels deep into the DOM.

My CommonViewModel class provides "services" but they are not global services, they are specific to that instance of the View (View Model). In effect my CommonViewModel is being used for managing resources (of different kinds) in a loose-coupled fashion. 

On possible solution has just occurred to me, however. If I were to create a new class "CommonViewModelResources", and I then @inject that into each of my views, does that mean if a Custom Element also @inject'ed the same object then they would get the same object that the View received. Like this:

    @useView( "mysampleview.html" )
    @inject( CommonViewModelResources )
    export class Fred extends CommonViewModel
    {
       constructor( resources: CommonViewModelResources ) ...
    }

Ideally, however (because it would involve less code change for me), I would prefer to just be able to gain access to CommonViewModel from my descendant custom elements.

**Comment by jdanyow** [comment]
I think you're on the right track with the `@inject(CommonViewModelResources)` approach. This will be more extendable. It will be easy to preserve separation of concerns- you can add deps to non-common items without polluting the common stuff: `@inject(CommonViewModelResources, NotCommonStuff, OtherUniqueStuff)`. With the `extends CommonViewModel` approach you might quickly run into issues.

Answering the question: 

Out of the box I think you could do something like this:

```js
import {View} from 'aurelia-templating';
@inject(Parent.of(View))
export class ChildViewModel {
  constructor(parentView: View) {
    this.parentView = parentView;
  }

  bind() {
    const parentViewModel: CommonViewModel = this.parentView.bindingContext;
  }
}
```

Another approach you could try would be to create a custom registration decorator to enable using `@inject(CommonViewModel)` in your child view models:

```js
@registrationKey(CommonViewModel)  // <--- create this decorator, examples in: https://github.com/aurelia/dependency-injection/blob/master/src/registrations.js
export class Fred extends CommonViewModel {
}
```

I haven't tried either of these approaches. There are probably other ways of doing this- I'm sure @EisenbergEffect will have some thoughts.

**Comment by EisenbergEffect** [comment]
I think the best approach, if you want to continue with this architecture, is to create a custom registration as @jdanyow suggests. However, there are other approaches you might take. For example, since the services seem to be scoped based on DOM structure, you might just consider creating a wrapper service that publishes events via the DOM. Then the upstream components can subscribe to those and respond. Another idea is to use the event aggregator, with object instances as messages. The messages could carry with them their "execution context" allowing a global subscriber to properly handle the situation. I'm not sure if this second idea would work but I think the DOM-based idea should.

**Comment by kevmeister68** [comment]
Sorry for the delay in getting back to this. I've had a few days of annual leave. Many thanks for the feedback.

Part of my problem was a misunderstanding of how the Container behaved. So I re-read the Dependency Injection docs and quickly realised that I should I have been performing registerTransient rather than registerInstance, so the "getting previous object" that I spoke of was not really getting the "previous" object it was getting the "first object registered".

I have looked at the registration stuff -- for me the biggest benefit of this decorator approach is [potentially] side-stepping the need to manually @inject Container into my derived classes, to push down to the base classes so I can do registerTransient( ) or something on them.

Can you confirm that I will indeed get that benefit? That is, Aurelia will hand my decorator a Container regardless as part of its instantiation and setup of the view model?

**Comment by EisenbergEffect** [comment]
Yes (if I follow you). The two most important things you can leverage are Registrations and Resolvers. Everything inside of the Container is handled by a Resolver. A Registration is just one way to get a Resolver into the Container.

You can see our Registrations here: https://github.com/aurelia/dependency-injection/blob/master/src/registrations.js

You can see our Resolvers here: https://github.com/aurelia/dependency-injection/blob/master/src/resolvers.js
