### ISSUE TITLE
Breaks under minification

### ISSUE THREAD

**Issue by Alxandr** [aurelia/dependency-injection#14]
The following (from `util.js`) breaks if minified:

```js
if (!(function f() {}).name)
```

When minified, the `f` get's removed (meaning the name is empty, thus the test succeeds, and it progresses to run `Object.defineProperty(Function.prototype, "name"` which crashes due to it already existing.

**Comment by EisenbergEffect** [comment]
That's a bummer. Any recommendation on this? I guess I could extract the function and "call" it...then perform the check. Thoughts?

**Comment by Alxandr** [comment]
I'm thinking something more among the lines of `Object.getOwnPropertyDescriptor(Function.prototype, "name")`

**Comment by Alxandr** [comment]
Can confirm that simply replacing it with with

```js
if (!Object.getOwnPropertyDescriptor(Function.prototype, "name"))
```

works in my browser. Not tested browsers where you actually need the shim though.

**Comment by matjaz** [comment]
what about using `f` inside.

`!(function f() {!f}).name`

**Comment by Alxandr** [comment]
Ok, so any minifier worth it's money will rename `test` to something else. So you just rebroke it.

**Comment by EisenbergEffect** [comment]
LOL You're right. That was really dumb. Let me just fix that real quick...

**Comment by EisenbergEffect** [comment]
All fixed. Let's just keep that little one between you and me ;)
