### ISSUE TITLE
di in webworker

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/dependency-injection#143]
how do I get a instance of the dependency injector in a web worker.
I want to instantiate a class that has dependency injection on it.
As far as I can guess, you need to instantiate this object through the di or the dependency injection on that class does not happen.

I want to create a instance of this in the webworker

```
import {inject} from "aurelia-framework";
import {FileUtility} from './file-utility';

@inject(FileUtility)
export class Utility {
    constructor(fileUtility) {
        this.fileUtility = fileUtility;

        console.log(`utility constructor`);
        console.log(this.fileUtility);
    }
}
```

I tried getting a instance of di like this
```
        System.import("aurelia-dependency-injection").then(module => {
            this.container = module.Container.instance;
        });
```
but instance is always undefined.

All i basically want to do is instantiate a object in a web worker and have the dependencies resolve.

**Comment by StrahilKazlachev** [comment]
`Container.instance` is set when you call [makeGlobal()](https://github.com/aurelia/dependency-injection/blob/1.3.0/src/container.js#L195) on an instance. Just do `new Container()`.

**Comment by caperavensoftware** [comment]
Are there any examples where aurelia objects are resolved or aurelia used in web workers, specially around using the di ?

**Comment by jdanyow** [comment]
You can't get the main thread's container instance in a worker thread.

On the worker thread, do something like:

```js
import {Container} from 'aurelia-dependency-injection';
const rootContainer = new Container();

// this is optional. Only use if you want to be able to access this container via the `Container.instance` static property.
rootContainer.makeGlobal();

**Comment by caperavensoftware** [comment]
Thanks guys. I was hoping I could get the main thread's container but i understand there are limitations to webworkers and passing objects through the threads.
Thank you for our help.
