### ISSUE TITLE
Factor.of does not work with registerXXX(stringLiteral, Class)

### ISSUE THREAD

**Issue by samhatoum** [aurelia/dependency-injection#146]
**I'm submitting a bug report**
**aurelia-dependency-injection v1.3.0**
**Operating System: OSX 10.x**
**Node Version: 4.8.0**
**NPM Version: 4.3.0**
**Language: ESNext (with Babel + Reflect shims)**

**Current behavior:**

I have a service:
```javascript
class MyDomainService {
  constructor(configuration = {thing: 'nothing'}) {
    this.thing = configuration.thing;
  }
  doSomething() {
    console.log(`doing ${this.thing}`);
  }
}
```

and I'm injecting the service as such:
```javascript
@inject(Factory.of(MyDomainService))
class ApplicationService {
  constructor(myDomainServiceFactory) {
    this.domainService = myDomainServiceFactory({thing: 'a real thing'});
  }
  aCommand() {
    this.domainService.doSomething();
  }
}
```

And I use the standalone container like this:
```
const container = new Container();
const applicationService = container.get(ApplicationService);
applicationService.aCommand();
``` 
And everything works as expected. ☀️ 

*However...*

If I use a String literal in the injector like this:

```javascript
@inject(Factory.of('IDomainService'))
```

and use the `container.registerSingleton` like this:

```
container.registerSingleton('IDomainService', MyDomainService);`
```

Then I see stack trace with the message `target is not a function: IMyDomainService` 🌧 

**Expected/desired behavior:**
I should be able to use String literals with `Factory.of`

**What is the motivation / use case for changing the behavior?**
This issue does not occur when I'm not using the `Factory.of` method and I would expect the container to behave the same when using the `registerXXX` methods.

**Comment by samhatoum** [comment]
[Here is the code that doesn't work](https://github.com/xolvio/qualityfaster/blob/spike/aurelia-dependency-injection/src/server/entry.js#L40-L47).

To run locally:
```bash
# it's a Meteor app so you need to install Meteor
curl https://install.meteor.com/ | sh
git clone https://github.com/xolvio/qualityfaster
git checkout spike/aurelia-dependency-injection
npm install && npm start
```

Then edit the file `src/server/entry.js`

**Comment by Sanjo** [comment]
I will work on this issue tomorrow.

**Comment by Sanjo** [comment]
I've made the necessary changes to make this use case work here: https://github.com/Sanjo/dependency-injection/commit/2676bc96f72af3281a1801f6eb68ec57a95a54cd. Let me know if you are interested in merging that in. Then I will create a pull request.

My impression is that the [Container Registration API](http://aurelia.io/hub.html#/doc/article/aurelia/dependency-injection/latest/dependency-injection-basics/5) and the [Resolvers](http://aurelia.io/hub.html#/doc/article/aurelia/dependency-injection/latest/dependency-injection-basics/6) weren't really designed to be used together.

An alternative approach is to register a factory for the class and don't use Factory.of: https://github.com/Sanjo/qualityfaster/commit/9160ce89b308c3d94ce76600e694e0e2320c2649

**Comment by ahedreville** [comment]
Hi when this enhancement will be avalaible?

**Comment by doktordirk** [comment]
is this issue valid? combining registerSingleton (aka single instance) and Factory.of with injects a constructor (aka not a single instance), don't go together imho. should work with registerHandler though.
