### ISSUE TITLE
Why getting a string from container results in the string itself?

### ISSUE THREAD

**Issue by fracz** [aurelia/dependency-injection#147]
After authentication, I register the user instance in the container:

```
container.registerInstance("CURRENT_USER", user);
```

In every other place that I need the current user instance, I inject it with `@Inject("USER")` and it works great.

However, I would expect the cointainer to inject nothing (i.e. `undefined`) if the user instance has not been registered yet.

However, it injects a `CURRENT_USER` string.

```
let wat = container.get("if your happy and you know it clap your hands");
// wat is a string "if your happy and you know it clap your hands"
```

What is the rationale for such behavior?

**Comment by jdanyow** [comment]
when the key used to lookup something in the container is not found, the container will create a new instance of the key, register it, and return it (assuming the key is a constructor function). If the key is a primitive, same thing, minus the new instance part.

This is different than something like unity, which would throw an exception when the registration is not found. Totally by-design though.

**Comment by jdanyow** [comment]
I should mention- here's the pattern I've been using for your scenario. It's simplified things a lot for my use cases. ymmv.

user.js
```js
export class User {
  name = 'anonymous';
  anonymous = true;
  ... other props ...
}
```

some-ui-component.js
```js
@inject(User)
export class SomeUIComponent {
  ...
}
```

login-form.js
```js
@inject(LoginService, User)
export class LoginForm {
  name = '';
  password = '';

  ...
  ...

  submit() {
    this.service.login(name, password)
      .then(profile => {
        this.user.anonymous = false;
        this.user.name = profile.name;
        ... other props ...
      });
  }
}
```

Using this technique, everything takes a dependency on the `User` singleton. The instance has two states: `anonymous === true` and `anonymous === false`.
