### ISSUE TITLE
@operator parameter decorator lacks key (forces incorrect typings)

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/dependency-injection#149]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.5.0

* **NPM Version:**
4.2.0

* **JSPM OR Webpack AND Version**
0.17.0-beta.41

* **Browser:**
all

* **Language:**
TypeScript 2.2

**Current behavior:**
`@optional` decorator may only take a boolean, not a key [as per docs](https://github.com/aurelia/dependency-injection/blob/master/doc/article/en-US/dependency-injection-basics.md).

**Expected/desired behavior:**

* **What is the expected behavior?**

We can specify the key the decorator uses for the container `@optional(keyOrCheckParent, checkParent)`

* **What is the motivation / use case for changing the behavior?**

1. Behaviour is not in line with other parameter decorators. 
2. Should be possible to make it a non-breaking change.
3. Better utilise TypeSrcipt type-checks:
  ```ts
  constructor(
    @optional(true) foo: Foo,
  ) {
    this.bar = foo.baz; // no error reported by TS though could be null due to @optional
  }
  ```
  Can become:
  ```ts
  constructor(
    @optional(Foo, true) foo: Foo | null,
  ) {
    this.bar = foo.baz; // TS reports error
  }
  ```

----

Hopefully I've not misunderstood this. It's my understanding that due to the inability to specify the key the `@optional` decorator must be inferring the type from the constructor definition. Is that right?

**Comment by EisenbergEffect** [comment]
There does appear to be something wrong with this particular decorator.

**Comment by EisenbergEffect** [comment]
I apologize, the error is in the documentation. You would use it like this:

```javascript
constructor(@optional() foo: Foo | null) {
  
}
```

You would get a null though if there was no existing instance in the container or its parent chain. You only need to pass the boolean if it's `false` to not check the parent hierarchy. It does not take a `key`.

**Comment by EisenbergEffect** [comment]
However, that does depend on how TS is encoding the parameter types. If it encodes just Foo, then it should work. If it encodes something else, then that would be a problem.
