### ISSUE TITLE
traceur-compiler returns annotation parameters as arrays

### ISSUE THREAD

**Issue by matjaz** [aurelia/dependency-injection#15]
See comment here: https://github.com/google/traceur-compiler/blob/28be0752241477c7d47214c6e9955e965a3243a5/src/codegeneration/AnnotationsTransformer.js#L95

Which is consumed in DI module
https://github.com/aurelia/dependency-injection/blob/68f8745ca0a642115cd16cb99e327f6516291d75/src/container.js#L33

A simple change to line 33 fixes this:
`keys[i] = parameters[i].is || parameters[i][0];`

**Comment by EisenbergEffect** [comment]
Yes. They aren't following their own spec at this point. However, I'd be willing to make this change if....you would sign our CLA and send me a pull request. Would you do that?
