### ISSUE TITLE
How do I use System.import in an Aurelia app?

### ISSUE THREAD

**Issue by djensen47** [aurelia/dependency-injection#151]
I was looking at the answer to #73 and one suggestion was to use `System.import` so I tried it in my main.js and it failed with `System is not defined`. 

Next, I attempted to tweak babel settings, install a babel plugin, install systemjs but nothing seemed to work.

**Comment by Thanood** [comment]
It depends on the loader you're acually using.
Aurelia has an abstracted loader. I think it should be safe to use that.
Docs: http://aurelia.io/hub.html#/doc/api/aurelia/loader/1.0.0/class/Loader

```js
import {inject, Loader} from 'aurelia-framework';

@inject(Loader)
export class MyClass {
  constructor(loader) {
    this.loader = loader;
  }

  myMethod() {
    this.loader.loadModule('module-id').then((module) => { doSomethingWith(modules); });
  }
}
```

(disclaimer: "hand-written", may contain errors 😏 )

**Comment by djensen47** [comment]
This worked great for me. Thanks @Thanood!
