### ISSUE TITLE
Resolving dependencies of dependencies does not work within a child container

### ISSUE THREAD

**Issue by omniscient** [aurelia/dependency-injection#152]
**I'm submitting a bug report**

* **Library Version:**
1.3.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.10.0

* **NPM Version:**
4.1.2

* **Browser:**
N/A - Server-side

* **Language:**
TypeScript 2.4.2

**Current behavior:**
When calling invoke on child containers, the container hierarchy is not respected when resolving the dependency tree. Check this example where we create a child container and then try to invoke the resolution of a Controller which also has dependencies that needs to be resolved within our child container:

Given these 2 classes:
```
@inject('context', Executer)
export class Controller {
  constructor(
    private context: Context,
    private executer: Executer
  ) {
  }
}

@inject('context')
export class Executer {
  constructor(
    private context: Context) { }
}
```
If I execute this code:
```
const childContainer = this.container.createChild();
childContainer.registerInstance('context', context);
const controller = childContainer.invoke(Controller);
```

If you look in the Controller class, the context is of the right type and ready to be used. Now if you look in the Executer class inside the Controller, the context variable is not initialized at all and contains "context" instead of the right expected instance.

**Expected/desired behavior:**
I would expect that the Executer class gets an instance of the Context class I registered in the child container.

* **What is the motivation / use case for changing the behavior?**
Using aurelia containers as the IOC for a api backend end.

**Comment by jdanyow** [comment]
I can reproduce this.

https://gist.run/?id=eec0513a83f70980d57cc0ccc84ce85e

```js
@inject('context')
export class Executer {
  constructor(context) { 
    this.context = context;
  }
}

@inject('context', Executer)
export class Controller {
  constructor(context, executer) {
    console.assert(context.database === 'good');
    console.assert(executer.context.database === 'good'); // this fails. executer.context.database === 'bad'
  }
}

const container = new Container();
container.registerInstance('context', { database: 'bad' });
const childContainer = container.createChild();
childContainer.registerInstance('context', { database: 'good' });
const controller = childContainer.invoke(Controller);
```

**Comment by EisenbergEffect** [comment]
It's expected. Unregistered types are resolved from the root container as singletons by default. An instance at a higher level of the container hierarchy cannot have a dependency on an instance from a lower level. To reach the desired behavior, you have to manually register the Controller type in the child container as well.

**Comment by jdanyow** [comment]
This appears to be working-as-designed although it is weird in comparison to other DI containers. When the child container attempts to resolve `Executer`, it finds that it's not registered in the child container so it asks the parent container to resolve it:

https://github.com/aurelia/dependency-injection/blob/01b2988aeece6b2a248e051bbf05a52752cf64d0/src/container.js#L375-L377

The parent container doesn't have an `Executer` so it will auto-register one (eg instantiate one). This is why the `Executer` instance gets the parent container's `context`.

A workaround is to decorate `Executer` with the `@transient()` decorator from `aurelia-dependency-injection`.

**Comment by jdanyow** [comment]
lol @EisenbergEffect I didn't see your comment until after I submitted mine

**Comment by omniscient** [comment]
I guess the experience with MS Unity caught me off guard on this one... Thanks for the hints; I went with the @transient() decorator. Sorry for the false alarm, I really thought I was onto something ;)
