### ISSUE TITLE
get rid of aurelia-pal dependency

### ISSUE THREAD

**Issue by stalniy** [aurelia/dependency-injection#154]
**I'm submitting a feature request**

* **Library Version:**
1.3.2

**Please tell us about your environment:**
* **Operating System:**
Ubuntu

* **Node Version:**
6.11.2

* **NPM Version:**
3.10.10

* **Browser:**
Node.js

* **Language:**
ESNext

**Current behavior:**
It looks a bit strange that Dependency Injection container depends on `aurelia-pal` package which is about platform abstract layer. So, to minimize amount of dependencies I'd suggest to throw Injector specific error, so people who uses this injection library not in browser and not in Aurelia env don't see `aurelia-pal` as dependency. Also this may lead to unexpected errors in nodejs env in future

**Expected/desired behavior:**
`aurelia-pal` is not a dependency of DI module. It uses only `AggregateError` which I guess could be DI specific `Error` instance.

* **What is the motivation / use case for changing the behavior?**
The library is awesome and I'd like to use it in node.js env with expressjs and other frameworks. But I want to be sure that the library is self-contained and its dependencies will not cause issues in future.

**Comment by Alexander-Taran** [comment]
Not happening so far.
There is pal-nodejs though
Now if you can provide a pull request that'd made this dependency optional
Like if there is AggregateError  throw it and otherwise just throw..
That'd be a great starting point

**Comment by EisenbergEffect** [comment]
Works fine in node.js and we don't want to make a breaking change at this point. We're doing something better for vNext, where the issue should be solved.
