### ISSUE TITLE
Optional resolver doesn't work as expected

### ISSUE THREAD

**Issue by Todberg** [aurelia/dependency-injection#155]
**I'm submitting a bug report**

* **Library Version:**
1.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 7 x64

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Chrome 61.0.3163.91

* **Language:**
TypeScript 2.5.2

**Current behavior:**
Consider the custom attribute, `BarCustomAttribute`.

```TypeScript
export class BarCustomAttribute { }
```
Another custom attribute, `FooCustomAttribute`, then injects `BarCustomAttribute` with the `@optional(false)` parameter decorator:

```TypeScript
import { autoinject, optional } from "aurelia-framework";
import { BarCustomAttribute } from "./bar-custom-attribute";

@autoinject
export class FooCustomAttribute {
    private readonly barCustomAttribute: BarCustomAttribute;

    public constructor(@optional(false) barCustomAttribute: BarCustomAttribute) {
        this.barCustomAttribute = barCustomAttribute;
    }
}
```

A consumer then uses `foo` on an element:
```html
<div foo></div>
```
At run-time, an instance of `BarCustomAttribute` is then injected into the instance of `FooCustomAttribute`.

**Expected/desired behavior:**
A value of null should be injected in the constructor of `FooCustomAttribute`.

**Comment by Alexander-Taran** [comment]
can you provide a small repro?

**Comment by EisenbergEffect** [comment]
No response from OP in over 6mo, so closing as not an issue.
