### ISSUE TITLE
di, nodejs

### ISSUE THREAD

**Issue by pragmaproducts** [aurelia/dependency-injection#158]
Can one use the di in a nodejs environment?
It seems that the normal usage scenario does not seem to work as the container instance in undefined.

Is there by any chance a example of using the di in nodejs?

**Comment by Alexander-Taran** [comment]
have a look at this article http://aurelia.io/docs/testing/components#testing-custom-component-with-a-real-view-model
testing works in the context of nodejs
and there are examples of using DI

**Comment by Alexander-Taran** [comment]
@pragmaproducts have you been able to check out my suggestion?

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP()
 if(!response) {
    closeQuestion(id)
 }
}
```

**Comment by EisenbergEffect** [comment]
Closing. DI can definitely be used in node.js. We use it inside our CLI :)
