### ISSUE TITLE
Missing property in d.ts?

### ISSUE THREAD

**Issue by gama410** [aurelia/dependency-injection#163]
**I'm submitting a bug report**

* **Library Version:**
1.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
6.0.1

* **Browser:**
irrelevant

* **Language:**
TypeScript 2.6.1

**Current behavior:**
I'm not sure this is really a bug actually. Maybe it should be tagged as a question. 
I'm currently retrieving the parent page (from which a navigation has been initiated) from the navigation instruction passed to my child route in its activate method.
In the navigation instruction, I can get the container (through instruction.router.container) which itself contains a **viewModel** property which is my parent's viewModel.
My small problem is that this property is not defined in the Container d.ts interface so typescript echoes an error if I don't cast the Container as 'any' in my code.
Now, I see that this property is indeed not set in aurelia-dependency-injection but rather in aurelia-router and I suppose it is a remnant of the fact that all developments were done in JS instead of TS in the beginning. Wouldn't it be possible to add this property to the d.ts so it would provide a coherent interface?
Or maybe this property is not meant to be used at all?

**Expected/desired behavior:**

I would expect the viewModel property to be defined in the Container d.ts interface

* **What is the motivation / use case for changing the behavior?**
For consistency's sake...

**Comment by doktordirk** [comment]
the dependency injection and the container is agnostic towards other parts of aurelia. So, if some typecasting could be improved it'll have to be in aurelia-router

**Comment by doktordirk** [comment]
you can raise that issue over at templating and/or templating-router which add that property. i guess they should introduce a `export type ViewContainer = Container & {viewModel: itstype};` or something

**Comment by StrahilKazlachev** [comment]
Most such dynamic additions are not meant to be public APIs.

**Comment by gama410** [comment]
Thanks for your insight!
