### ISSUE TITLE
Arrays and the DI Container

### ISSUE THREAD

**Issue by SebGX** [aurelia/dependency-injection#164]
Perhaps it's a misunderstanding on my part being new to Aurelia or perhaps it's an issue; however, I'm struggling to find any documentation that explains how I would get an array of instances from the DI container. Here's what I mean:

```typescript
export class CalendarDay {
  dayOfMonth: number = -1;
}

@inject(Array<CalendarDay>())
export class CalendarWeek {
  days[]: CalendarDay[] = null;

  constructor(days: CalendarDay[]) {
    this.days = days;
  }
}
```

**Comment by SebGX** [comment]
I managed to find a different way of handling the challenge. Add the following line to main.ts at the top of `configure()`:
```typescript
// Configure defaults for dependency injection.
aurelia.container.registerTransient(Array);
```

Then add the following to CalendarWeek:

```typescript
@inject(Array)
export class CalendarWeek {
  days[]: CalendarDay[] = null;

  constructor(days: CalendarDay[]) {
    this.days = days;
  }
}
```

While not a perfect solution, it at least declares the explicit dependencies within constructors.

**Comment by doktordirk** [comment]
the question is, why? DI is for IoC and managing dependencies. Your example would be easier as like
```js 
export class CalendarWeek {
  public days[]: CalendarDay[] = [];
  constructor() { }
}
```

**Comment by SebGX** [comment]
Thanks for the reply. I'm new to all of this having been a dev a very long time ago and perhaps I'm getting myself confused on related but different concepts. My thinking--and I'm open to correction--is that a DI container addresses a number of items, namely IoC and explicit dependencies. By keeping everything registered with the DI, I've one source for new instances as I need them.

I had implemented calendar week the way you suggest; however, I found that my dependencies became implicit as a result, which is why I'm looking for the ability to inject an array.

What do you think?

**Comment by SebGX** [comment]
I thought I'd share my overall solution for comment:

> main.ts
```typescript
/**
 * The application's entry point. The Aurelia framework invokes the configure() method at stat-up.
 * @param aurelia The active singleton instance representing the Aurelia framework used to configure the framework for the application.
 */
export function configure(aurelia: Aurelia): void {
  // Configure defaults for dependency injection.
  aurelia.container.registerTransient(Array);
  aurelia.use
  .standardConfiguration()
  .feature('some-feature');
}
```

> calendar-day.ts (part of some-feature)
```typescript
/**
 * Class representing a calendar day.
 */
export class CalendarDay {
  /**
   * The numberic day of the month represented by an instance of calendar day.
   */
  dayOfMonth: number = -1;
}
```

> calendar-week.ts (part of some-feature)
```typescript
@inject(Array)
/**
 * Class representing a calendar week.
 */
export class CalendarWeek {
  /**
   * The array of calendar days within an instance of calendar week.
   */
  calendarDays: CalendarDay[] = [];

  /**
   * Constructs a new CalendarWeek.
   * @param calendarDays An array of calendar days.
   */
  constructor(calendarDays: CalendarDay[]) {
    this.calendarDays = calendarDays;
  }
}
```

> index.ts (part of some-feature)
```typescript
/**
 * Configures the feature.
 * @param config The active singleton instance representing the FrameworkConfiguration used to configure the feature for use with the application.
 */
export function configure(config: FrameworkConfiguration): void {
  config.container.registerTransient(CalendarDay);
  config.container.registerTransient(CalendarWeek);
}
```

> Whenever I need to instantiate a new calendar day or week, the following code is used. Provided that my constructor has received an array of either, I've honoured the principle of explicit dependencies.
```typescript
let day: CalendarDay = Container.instance.get(CalendarDay);
let week: CalendarWeek = Container.instance.get(CalendarWeek);
```

**Comment by doktordirk** [comment]
for explicit vs implicit dependencies i found: https://www.c-sharpcorner.com/article/dependency-injection-part-3/

accordingly:

bad:  (pseudocodish)
```js
export class CalendarWeek {
  // explicit dependency
  CalendarDay  = class {
     dayOfMonth: number = -1;
   }

  days[]: this.CalendarDay[] = [];
}
```

fine: the dependency `CalendarDay` is external, can be in a different file, accessible for everyone ...
```js
export class CalendarDay {
  dayOfMonth: number = -1;
}

export class CalendarWeek {
  days[]: CalendarDay[] = [];
}
...
let cw = new CalendarWeek();
```

from stackoverflow
> The best definition I've found so far is one by James Shore:
> 
> "Dependency Injection" is a 25-dollar term for a 5-cent concept. [...]
>  Dependency injection means giving an object its instance variables. [...].

so for an example of a date class you might want access to the date service in several other classes. you can inject then the CalendarDay singleton with the current date. eg:

 ```js
@inject(CalendarDay) //<-- registers/creates singleton by default if not created yet and injects it
class App{
  contructor(date: Calendarday) {
    this.date = date;
  }

  init() {
    this.date.dayOfMonth =5;
  }
}

// some other class which needs that date singleton instance/service. 
@inject(CalendarDay) //<-- get the previously registered singleton/instance
class User {
  contructor(date: Calendarday) {
    this.date = date;
  }

  printDate() {
    console.log(this.date.dayOfWeek);
  }
}
```


PS: Usually one would not use global Container. That beats the purpose. In case a container instance is needed, you can inject it as well.
 ```js
@inject(Container) //<-- gets or creates a container instance
class App{
  contructor(date: Container) {
    let date = new  Calendarday();
    date.dayOfWeek =5;
    container.registerInstance(date, 'today'); //here we register a self made instance instead of letting the DI creating one when needed
  }
}

@inject('today') //<-- get the previously registered instance
class User {
  contructor(date: Calendarday) {
    this.date = date;
  }
}
 ```

**Comment by SebGX** [comment]
Perhaps we got off on the wrong foot here. I referenced Spring and Unity to show that my request is not outside the realm of use cases for DI containers. Moreover, I believe that my understanding of the principles at play along with the DI pattern are substantiated by the following commonly cited sources:
- Explicit Dependencies Principle: http://deviq.com/explicit-dependencies-principle/
- Dependency Inversion Principle: http://deviq.com/dependency-inversion-principle
- Dependency Injection Practice: http://deviq.com/dependency-injection/

My requirement is to build a datepicker based on days and weeks, hence my solution. Given the principles and the practice--which the Aurelia DI Container appears to honour--I'm struggling to reconcile the guidance being provided. It would seem logical that one of two outcomes should result here:
- We update the docs to reflect that injecting arrays as parameters is done as I've suggested--not ideal.
- We log a feature request to extend the DI container--probably the better solution.

What do you think?

**Comment by SebGX** [comment]
Probably worth noting that the ideal for me would be something that looks like the following:

```typescript
@inject(Array.of(SomeClassA))
export class SomeClassB {
  _someAs: SomeClassA[] = null;

  constructor(someAs: SomeClassA[]) {
    this._someAs = someAs;
  }
}
```

That way the `SomeClassA` definition gets scooped up as normal by the framework but injected in a pretty way where DI strategies can be run neatly. Using `Array.of()` is not only pretty, it hands the DI container something predictable that it can act on in the background.

**Comment by doktordirk** [comment]
hmm, i see now. i didn't see that you indeed wanted an array of instances at first.

**Comment by SebGX** [comment]
My bad, I'm in the weeds with the detail :)

**Comment by SebGX** [comment]
When I put this out, I wasn't sure it was an issue; was engaging first before raising. Happy to reframe the thread once we've reached a consensus.

In terms of `Array.of()`, I'm referring to the standard JS Array.of(), which we could use as a resolver. Maybe that's not clean (that's a determination I can't make), but it looks pretty :)

Yes, you're correct 'Key<T>` representing `Array<T>` would be great.

**Comment by doktordirk** [comment]
something like: works in js at least
```js
@resolver()
export class DIArray {
  _key: any;

  constructor(key: any) {
    this._key = key;
  }

  get(container: Container): any {
    if (!container.hasResolver(name)) {
      container.registerSingleton(name, Array);
    }
    
    return container.get(name);
  }

  static of(key: any): DIArray {
    if (typeof key === 'function') {
      return new DIArray( '__DIArray__' + key.prototype.constructor.name);
    } else if (typeof key === 'string') {
      return new DIArray(key);
    }

    throw new Error('must be string or function'); 
  }
}

@inject(DIArray.of(MyClass)) 
class XY {
 constructor(arr) {
   this.arr=arry;
 }
}
```

**Comment by SebGX** [comment]
Thanks for the code sample, it explains why `Array.of()` won't work but I think I can do an `InstanceArray.of()` in order to meet my needs. I'll have a crack at it with reference to your sample and the Aurelia Framework source for resolvers. If I'm successful, I'll share the code.

**Comment by doktordirk** [comment]
do that. and damm, InstanceArray is a good choice. i'm just so bad with inventing names :(

anyways, hang on with a parameter decorator until the current bug with those is fixed #162. 
Just the resolver is fine. though you will get the 'slice' error i think.

**Comment by SebGX** [comment]
Thanks for the help thus far, I found a sneaky way of getting what we need and making it clean. Let me know if you like the below:

```typescript
import { Container, resolver } from "aurelia-framework";

@resolver()
/**
 * Provides the ability to inject a new instance array of a given type. The returned instance array is transient and is not registered on the container.
 */
export class InstanceArray {
  /**
   * The key for which to resolve matches.
   */
  _key: any;

  /**
   * Creates a new instance of the InstanceArray resolver.
   * @param key The key for which to resolve matches.
   */
  constructor(key: any) {
    this._key = key;
  }

  /**
   * Called by the container to instantiate the instance array. The instance array is transient and is not registered on the container.
   * @param container The container to resolve from.
   * @return Returns an instance array.
   */
  get(container: Container): any[] {
    let injectable = typeof(container.get(this._key));
    if (Boolean(injectable)) {
      return [];
    } else {
      return undefined;
    }
  }

  /**
  * Creates an InstanceArray Resolver for the supplied key.
  * @param key The key for which to resolve matches.
  * @return Returns an instance of InstanceArray for the key.
  */
  static of(key: any): InstanceArray {
    return new InstanceArray(key);
  }
}
```

To use:

```typescript
@inject(InstanceArray.of(SomeClassA))
export class SomeClassB {
  _someAs: SomeClassA[] = null;

  constructor(someAs: SomeClassA[]) {
    this._someAs = someAs;
  }
}
```

**Comment by SebGX** [comment]
My only issue with the above is the check to see if the type in question has been registered with the container. There must be a better way than getting an instance, but I don't know how.

**Comment by doktordirk** [comment]
what this does do atm is:
 when SomeClassA has been registered previously somewhere (i predict there problems with the execution order),  inject a new empty array, if not inject undefined.

interesting, what do you need that for? 

though InstanceArray seems misleading now. what's the instance there? that name seems more appropriate to my sample idea, where the arrays are a singletons for each type and can be shared amount classes

**Comment by SebGX** [comment]
I may have confused my naming--it's late here in South Africa. As far as I understand, the DI container understands two types of lifetimes in general: singleton and transient. When something is transient, it can be registered with the DI container or not. Both are considered instances. For my purposes, I'm dealing with transients that should not clutter the DI container. All I need is that the DI container gives my constructors arrays.

Because we can assign an empty array to any typed array, the resolver only needs to return an empty array to satisfy the need. The only reason we're checking to ensure that the type is registered with the DI container is for stability... we should not be injecting arrays where the type hasn't been previously registered with the DI container. Am I making sense?

**Comment by SebGX** [comment]
PS: It's also worth noting that I'd made a mistake in an earlier comment with using the Aurelia DI container directly--you correctly pointed that out. To create individual elements for the array in compliance with standards, the Aurelia Framework provides the `Factory.of()` pattern to inject an appropriate factory.

**Comment by EisenbergEffect** [comment]
If you want an array, you would use `All.of(...)`. See docs here: https://aurelia.io/docs/fundamentals/dependency-injection#resolvers This assumes you have registered one or more singletons into the container. If so, it will provide you all of them. The idea is that when you have a plugin architecture, you will want to resolve all things that have been registered with the plugin point's interface. That's the intent of this feature and the best use case for arrays with DI. I wouldn't advise using it for anything else...it seems that would just be injecting an empty array anyway. You can always register a custom resolver if you need to do something special. It maps a key (which can be anything you want) to a function that produces the output you want.

**Comment by SebGX** [comment]
Hi Rob,

Thanks for the reply. I think there's some confusion here. I'm not trying to put a set of transient instances on the DI; the DI isn't meant for that. What I need is an array object for my transient instances, that's all. So an empty array is perfect. To get it to fit with TypeScript, I use the InstanceArray.of resolver I created so that my constructor gets the properly typed array object. As far as I know, that's the right way to use a DI to get collaborating objects, including arrays. If I wanted to put the array instance on the DI, I'd have to add a key and register the instance as I'm sure you know.

Once I have my array object, I need to be able to create new transient instances to populate the array. So naturally, I use the Factory.of resolver that comes with the framework. To my understanding, not only is the solution correct in terms of the dependency inversion / explicit dependencies principles, it conforms to the DI pattern and complies with type safety all while working within the bounds of the Aurelia framework.

If I've named the custom resolver incorrectly and it should be called TransientArray.of--which may in fact be more correct and removes some confusion--I'm happy to take the guidance and modify. I've been a little confused about language because ultimately everything is an instance and the DI understands three categories: singleton instances, registered instances, and transient instances.

Would love to hear your thoughts.

Warm regards,
Seb

**Comment by doktordirk** [comment]
just this morning I watch a talk that mentioned Cargo cult programming, and for me this reminded me of that since `new Array` kinda would do the same with just 10chars. 
From wikipedia
> Cargo cult programming can also refer to the practice of applying a design pattern or coding style blindly without understanding the reasons behind that design principle. Examples are adding unnecessary comments to self-explanatory code, overzealous **adherence to the conventions of a specific programming  paradigm** , or adding deletion code for objects that garbage collection would have collected automatically.

naturally i still might not have gotten the point at all and be completely wrong

**Comment by SebGX** [comment]
That's not very constructive. While I'm not averse to being characterised, you've yet to explain what I've misunderstood to any extent let alone misunderstood to the extent that constitutes blindly and overzealously applying the principles and pattern in question. All you've done is throw out a baseless insult and then tried to give yourself an out at the end. Nice.

**Comment by SebGX** [comment]
Cool, thanks for the reply. I take your point on avoiding over-engineering something. Let me explain how I arrived at the solution.

If I consider that my constructors receive every instance of the collaborating objects defined within my app, it makes sense that I don't violate the convention. While I understand that the shortcut you suggest saves some time, it looks like technical debt to me. It looks like technical debt for two reasons: (I) if I had a collection object, I'd inject it; and (ii) if I don't declare my arrays of collaborating objects in my constructors, I'm failing to declare some of my dependencies. If by contrast I stick to the principle and convention, I derive benefits.

When I look at my auto-generated docs, I can see at a glance what I'm using along with special cases such as arrays and factories. Impact analysis is a breeze. Moreover, code review is simplified because I'm not worrying about special cases where the principles are violated and the conventions are not followed.

In terms of effort, while the solution adds some code, it adds only as much overhead as for other objects injected by the DI, which is therefore no impact.

Bearing in mind that my strength lies in architecture, a no impact solution that keeps things ordered and predictable is always my first choice.

If I'm mistaken here, please explain why and I'll gladly (and gratefully) accept the guidance.
