### ISSUE TITLE
1.4.0 release and typings.

### ISSUE THREAD

**Issue by pete-hotchkiss** [aurelia/dependency-injection#167]
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

* **Node Version:**
8.11.0

* **NPM Version:**
5.6.0

* **Browser:**
all

* **Language:**
TypeScript 

**Current behavior:**
running typings install fails with the error
```
Unable to read typings for "aurelia-dependency-injection". The author of "aurelia-dialog" needs to check the entry paths in "typings.json" are up to date
```

**Expected/desired behavior:**
As previous - successful installation of tpyings file(s)

**Comment by EisenbergEffect** [comment]
Released 1.4.1. Please give that a try.

**Comment by pete-hotchkiss** [comment]
youre a star - thanks

**Comment by EisenbergEffect** [comment]
Closing as fixed. Apologies for the inconvenience.
