### ISSUE TITLE
throw when key is undefined or null

### ISSUE THREAD

**Issue by jdanyow** [aurelia/dependency-injection#17]
should `registerInstance` et al. throw when the key argument is undefined or null?

scenario:

```javascript
import {Foo} from 'aurelia-binding';  // aurelia-binding doesn't export "Foo"

aurelia.withInstance(Foo, new FancyFoo());  // no error
```

Noticed this because of my bug here:  https://github.com/aurelia/binding/pull/21

Let me know- will put together a PR.

**Comment by EisenbergEffect** [comment]
Yeah...probably should.
