### ISSUE TITLE
Injecting a string resolves an empty string instead of undefined

### ISSUE THREAD

**Issue by arnederuwe** [aurelia/dependency-injection#170]
**I'm submitting a bug report**

* **Library Version:**
1.4.1

* **Browser:**
all

* **Language:**
all

**Current behavior:**
When injecting a string in the following example, the str value injected is an empty string
```
import {inject} from 'aurelia-dependency-injection'
import { HttpClient} from 'aurelia-fetch-client'

@inject(String, HttpClient)
export class App { 
  constructor(str, client){
    alert(str);
    alert(client);
  }
}
```

**Expected/desired behavior:**

* **What is the expected behavior?**
The str value should be undefined as there is no resolver defined for a string.

* **What is the motivation / use case for changing the behavior?**
https://github.com/RSuter/NSwag generates client code which injects a string for resolving a base url and calls a base url resolver function if the injected url is undefined. The resolver function is never called because of this behavior.

**Comment by bigopon** [comment]
@arnederuwe  This is expected behavior. When a constructor is registered to be injected, it will be instantiated and value of `new String()` call is an empty string.

For NSwag, what you need to do is to register the service client in your `main.ts`:

```ts
export function configure(aurelia: Aurelia) {
  aurelia
    .use
    .instance(
      MyGeneratedServiceClass,
      new MyGeneratedServiceClass('http://path/to/my/base/url', aurelia.container.get(HttpClient)
    );
}
```

**Comment by arnederuwe** [comment]
Thanks for clarifying, I am doing something similar as you are describing to circumvent it:
```
export function configure(config: FrameworkConfiguration) {
	config.container.registerSingleton(
		ImageClient,
		() => new ImageClient(null, config.container.get(HttpClient))
	);
	config.container.registerSingleton(
		ContainerClient,
		() => new ContainerClient(null, config.container.get(HttpClient))
	);
	config.container.registerSingleton(
		CustomerClient,
		() => new CustomerClient(null, config.container.get(HttpClient))
	);
	config.container.registerSingleton(
		TenantInfoTokenClient,
		() => new TenantInfoTokenClient(null, config.container.get(HttpClient))
	);
}
```
Problem is I'm having a lot of clients, and this code isn't really DRY :) that's why I wanted to use nswag's url resolver function, but that only get's triggered when an undefined is passed to the client. I'll file an issue with NSwag, as there really is no clean way to utilize their resolver function because of this.

**Comment by bigopon** [comment]
@arnederuwe Please link the issue in this, thanks! 😄
