### ISSUE TITLE
No access to global Container when used in node npm module

### ISSUE THREAD

**Issue by weagle08** [aurelia/dependency-injection#174]
**I'm submitting a bug report**

* **Library Version:**
1.4.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.*

* **NPM Version:**
6.2.0

* **JSPM OR Webpack AND Version**
None - server side NodeJS

* **Browser:**
None - server side NodeJS

* **Language:**
Typescript 3.2.2

**Current behavior:**
I have used aurelia DI and other aurelia modules on several server side projects, but this is the first where I'm attempting to integrate into an aurelia module. It seems that doing Container.instance is undefined in the module even though container.makeGlobal() has previously been called in the main application.

**Expected/desired behavior:**
* **What is the expected behavior?**
Container.instance I thought was global once instance.makeGlobal() has been called and should be available in imported modules which are in the same process. Does Node affect this by how modules are loaded?

* **What is the motivation / use case for changing the behavior?**
To have node modules which rely on aurelia's nice and simple DI scheme to be able to access global container.

Module I'm trying to incorporate using the global container: [express-audi-decorators](https://github.com/weagle08/express-audi-decorators). The error is in the [registerController()](https://github.com/weagle08/express-audi-decorators/blob/master/src/express.ts#L366) method
Yes I know i can pass in an instance of the container into the registerController() call, but was hoping to not have to... would like to know if it is a bug in makeGlobal() or an issue with how NodeJS loads modules.

This same code works great when included in a project, it's just when installed as a module that I get this issue.

Thanks

**Comment by EisenbergEffect** [comment]
@weagle08 I'm skeptical that this is an issue inside of Aurelia. The `makeGlobal` API is pretty simple and straight forward in implementation. When I've seen things like this before, it's been due to different versions of modules being loaded. So, maybe the plugin has its own node_modules folder and is loading DI from there so that two instances are in memory with one globalized but the other not.

**Comment by weagle08** [comment]
I'll keep checking, but in the debugger there are no other globals that would override Container. Thanks for the feedback.

**Comment by weagle08** [comment]
Also, there is no other DI as I wrote all the code and am familiar w/ the libraries being used. If you want a reproduction project I can attach one if one of the Aurelia guys want to take a look.

**Comment by EisenbergEffect** [comment]
If you can attach a project with some basic instructions for me, that would greatly help.

**Comment by weagle08** [comment]
It appears you are right. When creating the bare minimum project to reproduce it runs fine so some other module is interfering. I'll start adding items back in slowly and keep an eye out for what breaks it.

Thanks,

Ben
