### ISSUE TITLE
1.4.2 release typings

### ISSUE THREAD

**Issue by alebrozzoamz** [aurelia/dependency-injection#178]
**I'm submitting a bug report**

* **Library Version:**
1.4.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.13.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
JSPM (not sure of version, it says "local jspm install"

* **Browser:**
all

* **Language:**
TypeScript 2.x

**Current behavior:**
running typings install fails with the error

Unable to read typings for "aurelia-dependency-injection". The author of "aurelia-dialog" needs to check the entry paths in "typings.json" are up to date
Expected/desired behavior:
As previous - successful installation of tpyings file(s)

* **What is the motivation / use case for changing the behavior?**
This was working fine at least a couple of days ago. Probably a similar reason for [Issue 167](https://github.com/aurelia/dependency-injection/issues/167)

**Comment by StrahilKazlachev** [comment]
Didi you try doing a clean install?

**Comment by SamDeBlock** [comment]
We are experiencing a similar issue. We have "aurelia-dependency-injection": "github:aurelia/dependency-injection", in our typings.json file.  
But  #177 removed the dist folder from master which causes https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404, expected it to equal 200

**Comment by Kla3mus** [comment]
Same problem on our end..

typings ERR! message Unable to read typings for "aurelia-dependency-injection". The author of "aurelia-dialog" needs to check the entry paths in "typings.json" are up to date
typings ERR! caused by https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404, expected it to equal 200

**Comment by Kla3mus** [comment]
So. A weird thing is going on now, because of this issue.

In my typings.json file i have this:
`"aurelia-dependency-injection": "github:aurelia/dependency-injection#6577553ed869a81fe69f92395765b27615ff7d58",`
 (an old version, i know), and when I run the build, it still tries to get the most recent one. It says this:

> typings WARN badlocation "github:aurelia/dependency-injection" is mutable and may change, consider specifying a commit hash
and the goes on to say what i posted here earlier...

> typings ERR! message Unable to read typings for "aurelia-dependency-injection". The author of "aurelia-dialog" needs to check the entry paths in "typings.json" are up to date
> typings ERR! caused by https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404, expected it to equal 200

Anyone know what i'm missing? Have specified the commit hash for all of my typings, but this one, (and metadata, pal and templating is still throwing this `badlocation`, and it's currently only the dependency-injection library that fails.. )

**Comment by SamDeBlock** [comment]
@Kla3mus aurelia-dialog doesn't specify a version in its [typings.json] (https://github.com/aurelia/dialog/blob/master/typings.json) eitherm which is why it fails retrieving the typings from master for aurelia-dependency-injection.

**Comment by Kla3mus** [comment]
> @Kla3mus aurelia-dialog doesn't specify a version in its [typings.json] (https://github.com/aurelia/dialog/blob/master/typings.json) eitherm which is why it fails retrieving the typings from master for aurelia-dependency-injection.

Right. Any idea how to get around this? - I suppose i could clone a version, set the version and use that package.. But when i say it, i feel like there should be an easier alternative..

**Comment by henrikroschmann** [comment]
Also, have the issue on our build server. 
_https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404_

**Comment by SamDeBlock** [comment]
We've temporarily disabled typings install in our build

**Comment by SamDeBlock** [comment]
@DrSammyD was this 'dist' remove during #171 intended?

**Comment by DrSammyD** [comment]
@SamDeBlock. I copied over the aurelia-validation project build process, and that included the .gitignore. I've added a PR to remove dist from the git ignore. I am however surprised that these typings are part of your build process since a new version with the change hasn't been released.

Anyway, here's a link to the pr. https://github.com/aurelia/dependency-injection/pull/179

**Comment by fkleuver** [comment]
Does JSPM work with npm?

**Comment by EDasilvaCorreia** [comment]
Hi all, same issue here builds are failing with _typings ERR! caused by https://raw.githubusercontent.com/aurelia/dependency-injection/master/dist/aurelia-dependency-injection.d.ts/index.d.ts responded with 404, expected it to equal 200_

**Comment by joelowrance** [comment]
@EDasilvaCorreia I forked the aurelia-dialog package and updated it's `typings.json` to point to a specifc commit

`"aurelia-dependency-injection": "github:aurelia/dependency-injection#587de79125fb8e7cca54a5d4785ccebf28c90954",
`

Then updated typings.json in my project for these two items (specific commit hash for the DI package, and pointed to the forked dialog repo).
```
    "aurelia-dependency-injection": "github:aurelia/dependency-injection#587de79125fb8e7cca54a5d4785ccebf28c90954",
    "aurelia-dialog": "github:joelowrance/dialog",
```

On my project we seem to see a similar error like this with one of the Aurelia packages every few months.

**Comment by StrahilKazlachev** [comment]
If anyone is sure that just by updating the dialog package this will be solved *completely* - not leaving some more exotic builds broken, it i quite easy to update and release dialog.

**Comment by alebrozzoamz** [comment]
With the merge of #179 our build is now working, albeit with the following warnings when transpiling:

```
/typings/modules/aurelia-dialog/index.d.ts(2556,11): error TS2536: Type 'number' cannot be used to index type 'TArgs'.
/typings/modules/aurelia-dialog/index.d.ts(2577,1): error TS2668: 'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible.
```

I'll close this issue and check if it's something in our side but it seems more related to the generic types included in the PR. Also the CI check of the PR is failing so it may be related to that.

Thank you @DrSammyD

**Comment by henrikroschmann** [comment]
I would like to reopen this issue. It is not resolved the build does not work. 
Also if you check the pull req there are errors.

**Comment by joelowrance** [comment]
I am also still seeing this issue.

```
typings\modules\aurelia-dialog\index.d.ts(2577,1): error TS2668: 'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible.
typings\modules\aurelia-dialog\index.d.ts(2632,170): error TS2536: Type 'number' cannot be used to index type 'TArgs'.
typings\modules\aurelia-dialog\index.d.ts(2638,122): error TS2536: Type 'number' cannot be used to index type 'TArgs'.
typings\modules\aurelia-validation\index.d.ts(496,9): error TS2707: Generic type 'Lazy<TBase, TImpl, TArgs>' requires between 1 and 3
type arguments.
```

**Comment by tcs-devel** [comment]
Same here. We meanwhile forked the aurelia-dialog repo and referenced a specific commit (pre-changes) in aurelia/dependency-injection in typings.json to get the build working again as this issue is/was blocking a planned release on our side.

**Comment by fkleuver** [comment]
So we are unable to make any changes, cleanups or improvement to any of our build/release processes. In fact we may need to revert everything to how it was just after initial beta, just to get everything to work again.
I'm baffled though. What is the nice thing about directly pointing to master branch in your npm package and using `typings`, 2-3 years after it stopped being the recommended way of doing that?

**Comment by joelowrance** [comment]
@fkleuver  For me, it's not that there is a "nice thing" about any specific tooling, it's that it has been working for the past 18 months and now it's broken.  The [`skeleton-typescript` ](https://github.com/aurelia/skeleton-navigation) project that many of us started with still uses this same combination of `jspm` and `typings`. 

Is there is a way to migrate from this approach towards the current best practice?

**Comment by fkleuver** [comment]
@joelowrance Alright, fair enough. We do consider stability to be one of our primary concerns. It's a matter of respecting developers of commercial projects, who often don't have time to deal with this fluff.

I feel we should have spent some time sooner on phasing out and helping people to migrate away from this jspm setup. It's an extremely unfortunate remnant of Aurelia's release timing right before ES modules were standardized and now we're kind of stuck with it.

So, it's a double-edged sword - to modernize/automate our CI/CD (and ensure longterm stability for vCurrent) we need to get rid of a bit of legacy, but doing so in itself breaks it for some people.

Anyway. It really depends on what dependencies and settings you have. 
If you could make a minimal "repro" or sample of the kind of setup you have, we can try to help. If a few people do this, we may be able to come up with a good set of general instructions for others and even try to incorporate some automated migration with vNext AOT. We don't have particularly much insight in all the ways people are using Aurelia, so we could use a hand there.

In general, though, moving your `jspm` dependencies to the regular npm `dependencies` field (or merging if they're duplicate) and removing `typings.json` plus its associated tooling (if any), should get you close. Typings generally work out of the box nowadays.
Then, you'd either pick `aurelia-cli` or webpack to continue, and I think for jspm users the `aurelia-cli` route will give the least friction.

**Comment by joelowrance** [comment]
@fkleuver Thanks for the response.   I will work on getting a small repo put together that at the very least uses a majority of the plugins we have added.

**Comment by joelowrance** [comment]
@fkleuver I have created a small repo that uses the dialog, kendo and moment.js.   There are a few other plugins we use in our real app but these seem like a good sample.  Repo is at https://github.com/joelowrance/au-convert

**Comment by fkleuver** [comment]
@joelowrance Thanks for this, I will take a look at it in the coming days. Question, I see wallaby.js in there, is that working / are you using it? (reason I ask is because I don't have a license for that anymore, so before I get a new license I first want to check if it's actually something that needs to be fixed too)

**Comment by joelowrance** [comment]
@fkleuver I am not using it.
