### ISSUE TITLE
error TS1110: Type expected

### ISSUE THREAD

**Issue by ben-girardet** [aurelia/dependency-injection#187]
**I'm submitting a bug report**

* **Library Version:**
1.5.0 and 1.5.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x and Linux Ubuntu

* **Node Version:**
10.14.2

* **NPM Version:**
6.6.0

* **JSPM OR Webpack AND Version**
Webpack

* **Browser:**
not relevant, bug is in building process of other library dependent of this one

* **Language:**
TypeScript 3.6.4 (also tested with older versions of TS)

**Current behavior:**
[Since the new typing definition](https://github.com/aurelia/dependency-injection/releases/tag/1.5.0), we encountered issues trying to build plugins and projects that depend on aurelia-dependency-injection. For exemple, trying to build aurelia-ux project, we get the error: 

```
../../node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts(67,5): error TS1110: Type expected.
[3] ../../node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts(67,5): error TS1110: Type expected.
[4] ../../node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts(67,5): error TS1110: Type expected.
```

**Expected/desired behavior:**
No error when building projects that depend on aurelia-dependency-injection

* **What is the motivation / use case for changing the behavior?**
I'm stuck in several projects due to this bug. I can force projects that have direct dependency to stick with 1.4.2 but it becomes complicated when I work on projects that have dependency to aurelia-dependency-injection through other dependencies...

See Aurelia Discourse discussion here: https://discourse.aurelia.io/t/contributing-to-aurelia-ux/3023

**Comment by EisenbergEffect** [comment]
@DrSammyD Would you be able to help us resolve this?

**Comment by DrSammyD** [comment]
I'll take a look tonight.

**Comment by bigopon** [comment]
Probably this line https://github.com/aurelia/dependency-injection/blob/98c00441a4a9fe5224e8bd6ecd9fbcac4072643d/src/resolvers.ts#L79 caused it. It seems to be an issue with TS, since VsCode does not reports error but tsc fails.

For now, I think we should change it to something like this:
```ts

export interface StrategyState<
  TBase,
  TImpl extends Impl<TBase> = Impl<TBase>,
  TArgs extends Args<TBase> = Args<TBase>
  > {
  /**
   * For typings purposes, this is done as { get: StrategyFunctor } | TImpl
   * But it should be understood, and used as [{ get: StrategyFunctor }, ...TImp[]]
   */
  [Strategy.array]: ({
    get: (
      container: Container,
      key: PrimitiveOrDependencyCtor<TBase, TImpl, TArgs>
    ) => TImpl
  } | TImpl)[];
  [Strategy.alias]: any;
}
```

**Comment by DrSammyD** [comment]
Did typescript break this? How was it ever building?

**Comment by bigopon** [comment]
@DrSammyD hmm, i'm not sure. Maybe it nevered actually built with `tsc`?

**Comment by DrSammyD** [comment]
I mean, it must have or the this wouldn't have passed [PR checks](https://github.com/aurelia/dependency-injection/pull/186/checks) and this...

https://github.com/aurelia/dependency-injection/blob/98c00441a4a9fe5224e8bd6ecd9fbcac4072643d/dist/aurelia-dependency-injection.d.ts#L65-L68

... wouldn't have ever been generated when compiling with typescript
https://github.com/aurelia/dependency-injection/blob/98c00441a4a9fe5224e8bd6ecd9fbcac4072643d/package.json#L35
https://github.com/aurelia/dependency-injection/blob/98c00441a4a9fe5224e8bd6ecd9fbcac4072643d/package.json#L103
