### ISSUE TITLE
Building project in babel-loader fails on const enum because of --isolatedModules flag

### ISSUE THREAD

**Issue by groenlid** [aurelia/dependency-injection#188]
**I'm submitting a feature request**

* **Library Version:**
1.5.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.15.1

* **Node Version:**
12.13.0

* **NPM Version:**
6.12.0

* **JSPM OR Webpack AND Version**
webpack 4.29.5

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
TypeScript 3.6.4

**Current behavior:**
When we try to build our aurelia app written in typescript through babel-loader, we are getting an error on this package which says:
````
node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:61:3 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

61  [Strategy.instance]: TImpl;
     ~~~~~~~~

node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:62:3 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

62  [Strategy.singleton]: DependencyCtorOrFunctor<TBase, TImpl, TArgs>;
     ~~~~~~~~

node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:63:3 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

63  [Strategy.transient]: DependencyCtorOrFunctor<TBase, TImpl, TArgs>;
     ~~~~~~~~

node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:64:3 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

64  [Strategy.function]: StrategyFunctor<TBase, TImpl, TArgs>;
     ~~~~~~~~

node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:65:3 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

65  [Strategy.array]: [{
     ~~~~~~~~

node_modules/aurelia-dependency-injection/dist/aurelia-dependency-injection.d.ts:68:3 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

68  [Strategy.alias]: any;
     ~~~~~~~~
````
**Expected/desired behavior:**

* **What is the expected behavior?**
* **What is the motivation / use case for changing the behavior?**
Being able to build the project through babel-loader with typescript presets.

**Comment by EisenbergEffect** [comment]
@DrSammyD This may be another side-effect of the TS conversion. When you submit the other PR, can you just remove the const from this enum for now?
