### ISSUE TITLE
Dependency injection fails if using push state

### ISSUE THREAD

**Issue by sunjay** [aurelia/dependency-injection#23]
Everything works file as long as I only keep one level in my URLs. As soon as I go deeper into something like this:
http://localhost:9000/-JkGelqaJ0h6t81nsrAQ/add/

I can no longer refresh the page without getting a bunch of errors.

I changed to using the history API (push state) instead of URL hashes as per the instructions here: http://aurelia.io/docs.html#configuring-push-state

You will notice in this error that Aurelia is using the add/ "directory" as its base URL for trying to access dependencies.

    GET http://localhost:9000/-JkGelqaJ0h6t81nsrAQ/add/jspm_packages/github/aurelia/bootstrapper@0.9.5.js 404 (Not Found)
    es6-module-loader.src.js:139Potentially unhandled rejection [3] Error loading "github:aurelia/bootstrapper@0.9.5" at http://localhost:9000/-JkGelqaJ0h6t81nsrAQ/add/jspm_packages/github/aurelia/bootstrapper@0.9.5.js
    Not Found: http://localhost:9000/-JkGelqaJ0h6t81nsrAQ/add/jspm_packages/github/aurelia/bootstrapper@0.9.5.js (WARNING: non-Error used)

Here's my config.js, I'm guessing that something needs to be adjusted there.

    System.config({
      "paths": {
        "*": "*.js",
        "github:*": "jspm_packages/github/*.js",
        "npm:*": "jspm_packages/npm/*.js",
        "aurelia-skeleton-navigation/*": "lib/*.js",
        "budget/*": "lib/*.js"
      },
      "baseUrl": "dist"
    });

    System.config({
      "map": {
        "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.9.5",
        "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
        "aurelia-framework": "github:aurelia/framework@0.8.8",
        "aurelia-http-client": "github:aurelia/http-client@0.5.5",
        "aurelia-router": "github:aurelia/router@0.5.8",
        "bootstrap": "github:twbs/bootstrap@3.3.2",
        "firebase": "npm:firebase@2.2.1",
        "font-awesome": "npm:font-awesome@4.3.0",
        "github:aurelia/binding@0.3.7": {
          "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
          "aurelia-metadata": "github:aurelia/metadata@0.3.3",
          "aurelia-task-queue": "github:aurelia/task-queue@0.2.5"
        },
        "github:aurelia/bootstrapper@0.9.5": {
          "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.2.4",
          "aurelia-framework": "github:aurelia/framework@0.8.8",
          "aurelia-history": "github:aurelia/history@0.2.4",
          "aurelia-history-browser": "github:aurelia/history-browser@0.2.5",
          "aurelia-loader-default": "github:aurelia/loader-default@0.4.3",
          "aurelia-logging-console": "github:aurelia/logging-console@0.2.4",
          "aurelia-router": "github:aurelia/router@0.5.8",
          "aurelia-templating": "github:aurelia/templating@0.8.14",
          "aurelia-templating-binding": "github:aurelia/templating-binding@0.8.7",
          "aurelia-templating-resources": "github:aurelia/templating-resources@0.8.10",
          "aurelia-templating-router": "github:aurelia/templating-router@0.9.4"
        },
        "github:aurelia/dependency-injection@0.4.5": {
          "aurelia-metadata": "github:aurelia/metadata@0.3.3",
          "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/framework@0.8.8": {
          "aurelia-binding": "github:aurelia/binding@0.3.7",
          "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
          "aurelia-loader": "github:aurelia/loader@0.3.5",
          "aurelia-logging": "github:aurelia/logging@0.2.5",
          "aurelia-metadata": "github:aurelia/metadata@0.3.3",
          "aurelia-task-queue": "github:aurelia/task-queue@0.2.5",
          "aurelia-templating": "github:aurelia/templating@0.8.14"
        },
        "github:aurelia/history-browser@0.2.5": {
          "aurelia-history": "github:aurelia/history@0.2.4",
          "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/http-client@0.5.5": {
          "aurelia-path": "github:aurelia/path@0.4.5",
          "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/loader-default@0.4.3": {
          "aurelia-loader": "github:aurelia/loader@0.3.5",
          "aurelia-metadata": "github:aurelia/metadata@0.3.3",
          "aurelia-path": "github:aurelia/path@0.4.5"
        },
        "github:aurelia/loader@0.3.5": {
          "aurelia-html-template-element": "github:aurelia/html-template-element@0.1.3",
          "core-js": "npm:core-js@0.4.10",
          "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.5.5"
        },
        "github:aurelia/router@0.5.8": {
          "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
          "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.2.4",
          "aurelia-history": "github:aurelia/history@0.2.4",
          "aurelia-path": "github:aurelia/path@0.4.5",
          "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.2.4",
          "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/templating-binding@0.8.7": {
          "aurelia-binding": "github:aurelia/binding@0.3.7",
          "aurelia-templating": "github:aurelia/templating@0.8.14"
        },
        "github:aurelia/templating-resources@0.8.10": {
          "aurelia-binding": "github:aurelia/binding@0.3.7",
          "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
          "aurelia-logging": "github:aurelia/logging@0.2.5",
          "aurelia-templating": "github:aurelia/templating@0.8.14",
          "core-js": "npm:core-js@0.4.10"
        },
        "github:aurelia/templating-router@0.9.4": {
          "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
          "aurelia-metadata": "github:aurelia/metadata@0.3.3",
          "aurelia-path": "github:aurelia/path@0.4.5",
          "aurelia-router": "github:aurelia/router@0.5.8",
          "aurelia-templating": "github:aurelia/templating@0.8.14"
        },
        "github:aurelia/templating@0.8.14": {
          "aurelia-binding": "github:aurelia/binding@0.3.7",
          "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
          "aurelia-html-template-element": "github:aurelia/html-template-element@0.1.3",
          "aurelia-loader": "github:aurelia/loader@0.3.5",
          "aurelia-logging": "github:aurelia/logging@0.2.5",
          "aurelia-metadata": "github:aurelia/metadata@0.3.3",
          "aurelia-path": "github:aurelia/path@0.4.5",
          "aurelia-task-queue": "github:aurelia/task-queue@0.2.5",
          "core-js": "npm:core-js@0.4.10"
        },
        "github:jspm/nodelibs-assert@0.1.0": {
          "assert": "npm:assert@1.3.0"
        },
        "github:jspm/nodelibs-buffer@0.1.0": {
          "buffer": "npm:buffer@3.0.3"
        },
        "github:jspm/nodelibs-constants@0.1.0": {
          "constants-browserify": "npm:constants-browserify@0.0.1"
        },
        "github:jspm/nodelibs-crypto@0.1.0": {
          "crypto-browserify": "npm:crypto-browserify@3.9.13"
        },
        "github:jspm/nodelibs-events@0.1.0": {
          "events-browserify": "npm:events-browserify@0.0.1"
        },
        "github:jspm/nodelibs-http@1.7.0": {
          "Base64": "npm:Base64@0.2.1",
          "events": "github:jspm/nodelibs-events@0.1.0",
          "inherits": "npm:inherits@2.0.1",
          "stream": "github:jspm/nodelibs-stream@0.1.0",
          "url": "github:jspm/nodelibs-url@0.1.0",
          "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "github:jspm/nodelibs-https@0.1.0": {
          "https-browserify": "npm:https-browserify@0.0.0"
        },
        "github:jspm/nodelibs-os@0.1.0": {
          "os-browserify": "npm:os-browserify@0.1.2"
        },
        "github:jspm/nodelibs-path@0.1.0": {
          "path-browserify": "npm:path-browserify@0.0.0"
        },
        "github:jspm/nodelibs-process@0.1.1": {
          "process": "npm:process@0.10.0"
        },
        "github:jspm/nodelibs-stream@0.1.0": {
          "stream-browserify": "npm:stream-browserify@1.0.0"
        },
        "github:jspm/nodelibs-url@0.1.0": {
          "url": "npm:url@0.10.3"
        },
        "github:jspm/nodelibs-util@0.1.0": {
          "util": "npm:util@0.10.3"
        },
        "github:jspm/nodelibs-vm@0.1.0": {
          "vm-browserify": "npm:vm-browserify@0.0.4"
        },
        "github:systemjs/plugin-css@0.1.6": {
          "clean-css": "npm:clean-css@3.0.10",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "path": "github:jspm/nodelibs-path@0.1.0"
        },
        "github:twbs/bootstrap@3.3.2": {
          "css": "github:systemjs/plugin-css@0.1.6",
          "jquery": "github:components/jquery@2.1.3"
        },
        "npm:amdefine@0.1.0": {
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "module": "github:jspm/nodelibs-module@0.1.0",
          "path": "github:jspm/nodelibs-path@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:asn1.js-rfc3280@1.0.0": {
          "asn1.js": "npm:asn1.js@1.0.3"
        },
        "npm:asn1.js@1.0.3": {
          "assert": "github:jspm/nodelibs-assert@0.1.0",
          "bn.js": "npm:bn.js@1.3.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "inherits": "npm:inherits@2.0.1",
          "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
          "vm": "github:jspm/nodelibs-vm@0.1.0"
        },
        "npm:assert@1.3.0": {
          "util": "npm:util@0.10.3"
        },
        "npm:browserify-aes@1.0.0": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "create-hash": "npm:create-hash@1.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "inherits": "npm:inherits@2.0.1",
          "stream": "github:jspm/nodelibs-stream@0.1.0",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:browserify-rsa@1.1.1": {
          "bn.js": "npm:bn.js@1.3.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "constants": "github:jspm/nodelibs-constants@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0"
        },
        "npm:browserify-rsa@2.0.0": {
          "bn.js": "npm:bn.js@1.3.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "constants": "github:jspm/nodelibs-constants@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "randombytes": "npm:randombytes@2.0.1"
        },
        "npm:browserify-sign@2.8.0": {
          "bn.js": "npm:bn.js@1.3.0",
          "browserify-rsa": "npm:browserify-rsa@1.1.1",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "elliptic": "npm:elliptic@1.0.1",
          "inherits": "npm:inherits@2.0.1",
          "parse-asn1": "npm:parse-asn1@2.0.0",
          "stream": "github:jspm/nodelibs-stream@0.1.0"
        },
        "npm:buffer@3.0.3": {
          "base64-js": "npm:base64-js@0.0.8",
          "ieee754": "npm:ieee754@1.1.4",
          "is-array": "npm:is-array@1.0.1"
        },
        "npm:clean-css@3.0.10": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "commander": "npm:commander@2.5.1",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "http": "github:jspm/nodelibs-http@1.7.0",
          "https": "github:jspm/nodelibs-https@0.1.0",
          "os": "github:jspm/nodelibs-os@0.1.0",
          "path": "github:jspm/nodelibs-path@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "source-map": "npm:source-map@0.1.43",
          "url": "github:jspm/nodelibs-url@0.1.0",
          "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:commander@2.5.1": {
          "child_process": "github:jspm/nodelibs-child_process@0.1.0",
          "events": "github:jspm/nodelibs-events@0.1.0",
          "path": "github:jspm/nodelibs-path@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:constants-browserify@0.0.1": {
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:core-js@0.4.10": {
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:core-util-is@1.0.1": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0"
        },
        "npm:create-ecdh@2.0.0": {
          "bn.js": "npm:bn.js@1.3.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "elliptic": "npm:elliptic@1.0.1"
        },
        "npm:create-hash@1.1.0": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "inherits": "npm:inherits@2.0.1",
          "ripemd160": "npm:ripemd160@1.0.0",
          "sha.js": "npm:sha.js@2.3.6",
          "stream": "github:jspm/nodelibs-stream@0.1.0"
        },
        "npm:create-hmac@1.1.3": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "create-hash": "npm:create-hash@1.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "inherits": "npm:inherits@2.0.1",
          "stream": "github:jspm/nodelibs-stream@0.1.0"
        },
        "npm:crypto-browserify@3.9.13": {
          "browserify-aes": "npm:browserify-aes@1.0.0",
          "browserify-sign": "npm:browserify-sign@2.8.0",
          "create-ecdh": "npm:create-ecdh@2.0.0",
          "create-hash": "npm:create-hash@1.1.0",
          "create-hmac": "npm:create-hmac@1.1.3",
          "diffie-hellman": "npm:diffie-hellman@3.0.1",
          "inherits": "npm:inherits@2.0.1",
          "pbkdf2-compat": "npm:pbkdf2-compat@3.0.2",
          "public-encrypt": "npm:public-encrypt@2.0.0",
          "randombytes": "npm:randombytes@2.0.1"
        },
        "npm:diffie-hellman@3.0.1": {
          "bn.js": "npm:bn.js@1.3.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "miller-rabin": "npm:miller-rabin@1.1.5",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "randombytes": "npm:randombytes@2.0.1",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:elliptic@1.0.1": {
          "bn.js": "npm:bn.js@1.3.0",
          "brorand": "npm:brorand@1.0.5",
          "hash.js": "npm:hash.js@1.0.2",
          "inherits": "npm:inherits@2.0.1",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:events-browserify@0.0.1": {
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:faye-websocket@0.9.3": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "http": "github:jspm/nodelibs-http@1.7.0",
          "https": "github:jspm/nodelibs-https@0.1.0",
          "net": "github:jspm/nodelibs-net@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "stream": "github:jspm/nodelibs-stream@0.1.0",
          "tls": "github:jspm/nodelibs-tls@0.1.0",
          "url": "github:jspm/nodelibs-url@0.1.0",
          "util": "github:jspm/nodelibs-util@0.1.0",
          "websocket-driver": "npm:websocket-driver@0.5.3"
        },
        "npm:firebase@2.2.1": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "faye-websocket": "npm:faye-websocket@0.9.3",
          "http": "github:jspm/nodelibs-http@1.7.0",
          "https": "github:jspm/nodelibs-https@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:hash.js@1.0.2": {
          "inherits": "npm:inherits@2.0.1"
        },
        "npm:https-browserify@0.0.0": {
          "http": "github:jspm/nodelibs-http@1.7.0"
        },
        "npm:inherits@2.0.1": {
          "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:miller-rabin@1.1.5": {
          "bn.js": "npm:bn.js@1.3.0",
          "brorand": "npm:brorand@1.0.5"
        },
        "npm:os-browserify@0.1.2": {
          "os": "github:jspm/nodelibs-os@0.1.0"
        },
        "npm:parse-asn1@2.0.0": {
          "asn1.js": "npm:asn1.js@1.0.3",
          "asn1.js-rfc3280": "npm:asn1.js-rfc3280@1.0.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "pemstrip": "npm:pemstrip@0.0.1",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:parse-asn1@3.0.0": {
          "asn1.js": "npm:asn1.js@1.0.3",
          "browserify-aes": "npm:browserify-aes@1.0.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "create-hash": "npm:create-hash@1.1.0",
          "pbkdf2-compat": "npm:pbkdf2-compat@3.0.2",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:path-browserify@0.0.0": {
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:pbkdf2-compat@3.0.2": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "child_process": "github:jspm/nodelibs-child_process@0.1.0",
          "create-hmac": "npm:create-hmac@1.1.3",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "path": "github:jspm/nodelibs-path@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
        "npm:public-encrypt@2.0.0": {
          "bn.js": "npm:bn.js@1.3.0",
          "browserify-rsa": "npm:browserify-rsa@2.0.0",
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "create-hash": "npm:create-hash@1.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "parse-asn1": "npm:parse-asn1@3.0.0",
          "randombytes": "npm:randombytes@2.0.1"
        },
        "npm:punycode@1.3.2": {
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:randombytes@2.0.1": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:readable-stream@1.1.13": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "core-util-is": "npm:core-util-is@1.0.1",
          "events": "github:jspm/nodelibs-events@0.1.0",
          "inherits": "npm:inherits@2.0.1",
          "isarray": "npm:isarray@0.0.1",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "stream": "npm:stream-browserify@1.0.0",
          "stream-browserify": "npm:stream-browserify@1.0.0",
          "string_decoder": "npm:string_decoder@0.10.31",
          "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:ripemd160@1.0.0": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:sha.js@2.3.6": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "inherits": "npm:inherits@2.0.1",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:source-map@0.1.43": {
          "amdefine": "npm:amdefine@0.1.0",
          "fs": "github:jspm/nodelibs-fs@0.1.1",
          "path": "github:jspm/nodelibs-path@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:stream-browserify@1.0.0": {
          "events": "github:jspm/nodelibs-events@0.1.0",
          "inherits": "npm:inherits@2.0.1",
          "readable-stream": "npm:readable-stream@1.1.13"
        },
        "npm:string_decoder@0.10.31": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0"
        },
        "npm:url@0.10.3": {
          "assert": "github:jspm/nodelibs-assert@0.1.0",
          "punycode": "npm:punycode@1.3.2",
          "querystring": "npm:querystring@0.2.0",
          "util": "github:jspm/nodelibs-util@0.1.0"
        },
        "npm:util@0.10.3": {
          "inherits": "npm:inherits@2.0.1",
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:vm-browserify@0.0.4": {
          "indexof": "npm:indexof@0.0.1"
        },
        "npm:websocket-driver@0.5.3": {
          "buffer": "github:jspm/nodelibs-buffer@0.1.0",
          "crypto": "github:jspm/nodelibs-crypto@0.1.0",
          "events": "github:jspm/nodelibs-events@0.1.0",
          "net": "github:jspm/nodelibs-net@0.1.0",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "stream": "github:jspm/nodelibs-stream@0.1.0",
          "url": "github:jspm/nodelibs-url@0.1.0",
          "util": "github:jspm/nodelibs-util@0.1.0",
          "websocket-extensions": "npm:websocket-extensions@0.1.1"
        },
        "npm:websocket-extensions@0.1.1": {
          "process": "github:jspm/nodelibs-process@0.1.1"
        }
      }
    });

Part of fixing this issue should be adjusting the documentation to tell people to do whatever they need to to fix this (if it is in fact a configuration problem).

**Comment by sunjay** [comment]
This actually completely breaks all functionality. I can't even load view models because everything is being resolved based on that "sub-directory". 

Please give me a way to fix this.

**Comment by Vheissu** [comment]
Same issue as you. The only way you can fix it is to put forward slashes infront of all of your paths where packages are resolved.

**Change from:**

```
"paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "aurelia-skeleton-navigation/*": "lib/*.js",
    "budget/*": "lib/*.js"
  },
```

**Change to**

```
"paths": {
    "*": "/*.js",
    "github:*": "/jspm_packages/github/*.js",
    "npm:*": "/jspm_packages/npm/*.js",
    "aurelia-skeleton-navigation/*": "/lib/*.js",
    "budget/*": "/lib/*.js"
  },
```

This isn't the best fix though as anytime you update your jspm packages, add new ones or remove them the paths will get reset. So if you run any of those commands you have to put the forward slashes in.

**Comment by sunjay** [comment]
@Vheissu Thanks. That mostly worked, though now Aurelia is complaining that it can't load my main file.

    GET http://localhost:9000/-JkGelqaJ0h6t81nsrAQ/add/dist/app.html

**Comment by Vheissu** [comment]
@sunjay No worries. In your index.html file where you are including everything, try adding a base tag to set the base URL. I have mine set to ```<base href="/">``` just above the title tag. I find it forces template files, etc to include from the root directory onwards.

**Comment by sunjay** [comment]
Is this a bug in Aurelia? Or is it a bug in jspm? Rather than just finding work arounds, I'd really like to find the root and report it to the right people. Is there something I can adjust in my configuration files that will fix this?

Aurelia's documentation should be updated to include the solution to this issue so that future people who set this up don't run into the same problems.

**Comment by EisenbergEffect** [comment]
Has nothing to do with Aurelia per se. What you need to do is add a `base` element in your index.html head. This will tell the browser what to base all links on. It gets confused when using push state without this. We've added a note about this to the docs being published soon.

**Comment by sunjay** [comment]
Thanks!

**Comment by pmarchezz** [comment]
I just ran into this problem and was able to reproduce using the skeleton navigation app as minimal example. Steps I used to reproduce:
* cloned `aurelia/skeleton-navigation` to a test folder, ran `npm install && jspm install`
* changed `index.html`adding `<base href="/">`before the title tag
* added `config.options.pushState = true;` in `app.js`
* installed `connect-history-api-fallback` and updated `serve` task as explained in the docs
* ran `gulp watch`, navigated to `localhost:9000/child-router/child-router`; refreshed the page

I got a 404 for aurelia-bootstrapper: `GET http://localhost:9000/child-router/jspm_packages/github/aurelia/bootstrapper@0.10.0.js 404 (Not Found)`, and the page obviously breaks.

Is this really fixed with a base tag? Am I running into a different issue?

**Comment by pmarchezz** [comment]
This issue needs to be reopened, in my opinion. A base tag doesn't fix the problem for me, and [this stackoverflow question](http://stackoverflow.com/questions/29244863/aurelia-routing-configuration-issue) seems to suggest I'm not the only one (the author accepted the answer, but commented that it stil doesn't work correctly). I also tried [this](http://ilikekillnerds.com/2015/03/getting-aurelia-to-work-with-html5-pushstate/) without any success. Should I open another issue in a different report (where?) to track this problem? If not, how can I solve the issue?

**Comment by mttmccb** [comment]
I'm having the same problem, nothing seems to resolve it, I think I've tried every combination of 'solution'

**Comment by EisenbergEffect** [comment]
It's not an Aurelia issue, but related to how the browser resolves urls when in push state mode. In all cases I have seen, setting a base tag in the head of the index.html solves this problem (along with proper server configuration). We would need a lot more information in order to diagnose what is happening if that isn't solving the problem. Have you both tried that? If that didn't work, can you provide some more information about what you are seeing with errors, etc.?

**Comment by mttmccb** [comment]
I'll setup a test repo and detail the steps after I get back from work. However I don't get any error messages, it just hangs.

**Comment by mttmccb** [comment]
Here's the [repo](https://github.com/mttmccb/skeleton-navigation-0.13.0-with-PushState) ... I've just taken the latest release version of the skeleton app and made the changes. I did try a few different urls (http://localhost, http://localhost:9000, http://localhost:9000/) in the base tag with the same response, also adding baseURL into config again with various combinations of URLs.

When I gulp watch and open the browser I don't get any error messages and eventually I get a timeout. Not sure if I'm missing step or my setup is different. npm version looks like this

```
{ npm: '2.9.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

**Comment by EisenbergEffect** [comment]
If you are using gulp-watch, it's not going to work correctly. You need to set up you server for push-state as well. There's a section in our docs on that, but it's different depending on your server-side technology. Have you confirmed that that is set up correctly. It can be a bit tricky because it needs to serve the index.html for every request...except requests for templates, js and css.

**Comment by mttmccb** [comment]
I'm using gulp watch on my local machine as I understood the `connect-history-api-fallback` middleware would handle the redirects (along with the code changes) but it just hangs. I'm trying to use an API that uses OAuth with implicit grant so my return url would be something like http://localhost/handle_oauth?token=asdaas.... but I can't get the point where it handles any route with push state turned on.

I've reviewed the BrowserSync docs and turned up the logLevel but it didn't provide any insight.

On the dev side it's on Azure so I'm using IIS to do the redirects and it works there.

I'll think I'll look at an alternative to middleware or server.

**Comment by mttmccb** [comment]
I've used this rather ugly serve task to resolve the problem

```
var fs = require("fs"),
        path = require("path"),
        url = require("url"),
        gulp = require("gulp"),
        browserSync = require("browser-sync");

// The default file if the file/path is not found
var defaultFile = "index.html";

// I had to resolve to the previous folder, because this task lives inside a ./tasks folder
// If that's not your case, just use `__dirname`
var folder = path.resolve(__dirname, "../../");

gulp.task("serve", ['build'],  function() {

    browserSync({
    open: false,
    port: 9000,
        server: {
            baseDir: '.',
            middleware: function(req, res, next) {
                var fileName = url.parse(req.url);
                fileName = fileName.href.split(fileName.search).join("");
                var fileExists = fs.existsSync(folder + fileName);
                if (!fileExists && fileName.indexOf("browser-sync-client") < 0) {
                    req.url = "/" + defaultFile;
                }
                return next();
            }
        }
    });

});
```
