### ISSUE TITLE
Indicate the name of the module if DI fails to find key

### ISSUE THREAD

**Issue by PWKad** [aurelia/dependency-injection#24]
Ex
`
static inject() { return [WorngSpelling]; }
`
Returns a null / undefined error in container.js, the error should include the (incorrect) name of the failed module to load or at least the module that the load failure occurred in (currently the router swallows the stack)

**Comment by EisenbergEffect** [comment]
I think it's a router bug. The container throws better errors, at least in the version I published this morning.

**Comment by EisenbergEffect** [comment]
Closing. I think this is fixed in the latest.
