### ISSUE TITLE
Dependency injection as standalone library

### ISSUE THREAD

**Issue by b091** [aurelia/dependency-injection#26]
Hi,

we are writing a library in TypeScript 1.5.
We would like to achieve dependency injection using ES7 proposal decorators.
Instead of writing it ourselves we found your DI component (aurelia-dependency-injection) and tried to use it in our enviroment.
We're faceing some problems. Did you predicted usage of aurelia-dependency-injection without entire aurelia framework?
If so, how can we do it?.. How to create objects without passing arguments to constructor?

index.html
```html
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>
  System.import('jquery');
  System.import('scripts/Application');
</script>
```

scripts/SampleTest.ts
```typescript
export class SampleTest {
  testName = 'Jon Doe test';
  constructor() {
    console.log('HEY 1', this);
  }
}
```

scripts/Application.ts
```typescript
import {inject} from 'aurelia-dependency-injection';
import {SampleTest} from 'scripts/SampleTest';

@inject(SampleTest)
export class Application {
  constructor(simpletest) {
    console.log(this, simpletest); // result is: Application {},  undefined
  }
}

new Application(); // Is there other way to do this (initialize the app)?
```

**Comment by EisenbergEffect** [comment]
You need to use the DI container to get the instance.

```
import {Container} from 'aurelia-dependency-injection';

var container = new Container(); //this would be your global container for the app, created at startup
var app = container.get(Application);
```

The container has to be used as the source of the instance.

**Comment by b091** [comment]
Thank You. It works like a charm :dancers:

**Comment by EisenbergEffect** [comment]
Note, that our next release will make this even better. There's an optional compilation flag for TS 1.5 that enables it to preserve some runtime type information, so we are going to support that metadata in our DI implementation. After the next release, you will be able to do this:

```javascript
import {inject} from 'aurelia-dependency-injection';
import {SampleTest} from 'scripts/SampleTest';

@inject
export class Application {
  constructor(simpletes:SampleTestt) {
   ...
  }
}
```
