### ISSUE TITLE
Question about child containers

### ISSUE THREAD

**Issue by staxmanade** [aurelia/dependency-injection#30]
Hey All,

I'm trying to use a child containers to isolate dependencies used during testing...

I want to define a `Storage` class and in the production application leverage a `PersistentStorage` instance of `Storage`, while in the tests I want my objects to use an instance of `InMemoryStorage` instead (so the tests don't pollute the persistent storage).

It seems like when I try to pull an object out of the `childContainer` that isn't explicitly registered there, it's going up to the parent container, grabbing the instance, but the dependencies of the object being pulled out of the parent container use the parent container objects and not the overriden ones in child container.

Here's a test that describes what I'm hoping to accomplish.

```

import { Container } from 'aurelia-dependency-injection';

describe.only("hmmm", function(){
    it("what do you think about this?", function(){

        class Storage{
            constructor(name) {
                this.name = name;
            }
        };
        class PersistentStorage extends Storage{
            constructor() {
                super("persistent");
            }
        };
        class InMemoryStorage extends Storage{
            constructor() {
                super("inmemory");
            }
        };

        class MyObject{
            static inject(){return [Storage];}
            constructor(storage) {
                this.storage = storage;
            }
        }

        var container = new Container();
        container.registerInstance(Storage, new PersistentStorage());

        var unitTestChildContainer = container.createChild();
        unitTestChildContainer.registerInstance(Storage, new InMemoryStorage());
        
        var myObj = unitTestChildContainer.get(MyObject);

        expect(myObj.storage.name).to.equal('inmemory');
    });
});
```

Could this be possible? Or is there a different approach to this without re-registering each object?

Thanks

**Comment by staxmanade** [comment]
For now, I'm falling back to using two separate containers and some registration helpers

```

    it("Current workaround", function(){

        class Storage{
            constructor(name) {
                this.name = name;
            }
        };
        class PersistentStorage extends Storage{
            constructor() {
                super("persistent");
            }
        };
        class InMemoryStorage extends Storage{
            constructor() {
                super("inmemory");
            }
        };

        class MyObject{
            static inject(){return [Storage];}
            constructor(storage) {
                this.storage = storage;
            }
        }

        var container = new Container();
        var testContainer = new Container();

        function registerInstance(key, obj, testObj){
            container.registerInstance(key, obj);
            testContainer.registerInstance(key, testObj || obj);
        }

        function registerTransient(item, testItem) {
            container.registerTransient(item);
            testContainer.registerTransient(testItem || item);
        }

        registerInstance(Storage, new PersistentStorage(), new InMemoryStorage());

        var myObj = testContainer.get(MyObject);

        expect(myObj.storage.name).to.equal('inmemory');
    });
```

**Comment by EisenbergEffect** [comment]
`MyObject` has to get its dependencies from the container that creates it or from a parent container, otherwise you have memory leaks and really strange runtime resolution behaviors in some cases. In your case, what you really want, I think, is for `MyObject` to be created by the child container. To accomplish this, register `MyObject` in the child container. It doesn't matter if it's also registered in the parent. One of the reasons for having child containers is to override parent services.

**Comment by staxmanade** [comment]
Thanks for clarifying...
