### ISSUE TITLE
Inject strings

### ISSUE THREAD

**Issue by akircher** [aurelia/dependency-injection#32]
My use case is PouchDB, but I assume other libraries may have this same problem.  PouchDB doesn't let me extend it (https://github.com/pouchdb/pouchdb/issues/3743).  Unfortunately this means it's very hard to both use aurelia's DI and provide it with the dbName.  If 'extends' worked I could simply do

```
export class Db extends PouchDB {
  constructor() {
    super('dbName')
  }
}
````
Seems like I should be able to inject a string directly. But this throws a typeError
```
@inject('dbName')
export PouchDB
```

For now the best option seems to be exporting a single string to solve this issue? I am okay with this but wanted to make sure...
```
// ./constants.js
export let dbName = 'dbName'

// ./db.js
import {dbName} from './constants'

@inject(dbName)
export PouchDB
```

```

**Comment by stoffeastrom** [comment]
Haven't used `PouchDB` but one thing you can do is register an instance in your `main` module file

```
export function configure(aurelia) {
  var db = new PouchDB( "MyDB" );
  aurelia.registerInstance( "MyDB", db );

  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css');

  aurelia.start().then(a => a.setRoot());
}

//Some other module
@inject( "MyDB" )
```

**Comment by riddla** [comment]
I just tried the code from @stoffeastrom, I think you need to invoke `aurelia.container.registerInstance( "MyDB", db );` instead of `aurelia.registerInstance( "MyDB", db );`?

**Comment by stoffeastrom** [comment]
Yes or just move it down

```javascript
aurelia.use
  instance( "MyDB", db );
```

**Comment by riddla** [comment]
Oh, I see. You want to update your former sample in case that others stumble on it, too?

**Comment by stoffeastrom** [comment]
Sure, done!

**Comment by mipod** [comment]
I know that this post is closed and this question may sound silly as I am just starting with Aurelia and PouchDb, but I don't seem to catch the grasp of thing. I tried the solution proposed above and it worked  but I can't understand why... And how can I use the @inject('MyDb') in another class ? Thank you for your patience.
