### ISSUE TITLE
Dependency injection depends on path to import.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/dependency-injection#34]
I have two view models and one service that is dependency injected into each of them.

ModelA
```js
import { inject } from 'aurelia-dependency-injection';
import { Foo } from 'foo';
@inject(Foo)
export class ModelA {
	constructor(foo) {
		this.foo = foo;
	}
}
```
ModelB
```js
import { inject } from 'aurelia-dependency-injection';
import { Foo } from 'services/foo';
@inject(Foo)
export class ModelB {
	constructor(foo) {
		this.foo = foo;
	}
}
```
Foo
```js
export class Foo {
}
```

In this scenario, `ModelA` and `ModelB` will get different instances of `Foo`.  This is because they import from different paths.

***IMPORTANT***: Both paths resolve to the same location at runtime!  In `config.js` (for SystemJS) there are the following mappings:
```
"paths": {
	"*": "*.js",
}
"map": {
	"Foo": "services/Foo.js"
}
```

The expectation here would be that both models would get the same instance since they are reading the same class file off disk.

**Comment by EisenbergEffect** [comment]
If this is actually happening, it's not a DI bug. It's a but with SystemJS. Please report it to them, since it's really an issue of the same module being loaded twice, resulting in different module instances.
