### ISSUE TITLE
Work with typescript?

### ISSUE THREAD

**Issue by j-walker23** [aurelia/dependency-injection#35]
Hey, i was browsing some other aurelia code. You guys have a lot of cool stuff. 
And was wondering what this lib is/ how to use it. And if it could be used with typescript?

**Comment by b091** [comment]
Hi,
Yes you can use it with TypeScritpt
Here you have some hint: https://github.com/aurelia/dependency-injection/issues/26

**Comment by j-walker23** [comment]
Thank you!
