### ISSUE TITLE
How to inject class type (not instance) with dependencies already resolved

### ISSUE THREAD

**Issue by decademoon** [aurelia/dependency-injection#38]
In Angular 1.x, we can do this:

```javascript
module.factory('MyClass', function (dep) {
  return function MyClass(arg) {
    this.arg = dep(arg);
  };
});

module.controller('MyCtrl', function (MyClass) {
  var instance = new MyClass(1234);
});
```

How can I achieve the same thing in Aurelia?

Currently I'm achieving it like this:

```javascript
class MyClass {
  constructor(dep, arg) {
    this.arg = dep(arg);
  }
}

@inject(dep)
class MyViewModel {
  constructor(dep) {
    this.myClass = new MyClass(dep, 1234);
  }
}
```

but this means I need to inject `dep` into the view model so that I can pass an instance of it to the `MyClass` constructor. Is this the correct/only way of doing it?

**Comment by EisenbergEffect** [comment]
It's possible to do this by creating a custom resolver. The resolver could inject a function that creates instances of the class. It could call the DI api to aggregate the class' dependencies with any arguments passed into the function, before invoking the constructor. Then you would specify that you want the factory.

Here's the resolver:

```
import {Resolver} from 'aurelia-framework';

export class Factory extends Resolver {
  constructor(Type){
    this.Type = Type;
  }

  get(container){
    return function(...rest){
      return container.invoke(this.Type, rest);
    };
  }

  static of(Type){
    return new Factory(Type);
  }
}
```

And use it like this:

```
@inject(Dep)
class MyClass {
  constructor(dep, arg) {
    this.dep = dep;
    this.arg = arg;
  }
}

@inject(Factory.of(MyClass))
class MyViewModel {
  constructor(factory) {
    this.myClass = factory(1234);
  }
}
```

Note: I had to add the ability to pass additional deps to the `invoke` helper on the container in order to make this possible. So, you will need to wait until tomorrow's release to implement the Factory resolver.

**Comment by jbrey** [comment]
Hi,

I've updated to aurelia-framework@0.17.0 and aurelia-dependency-injection@0.11.0.
This pattern doesn't seem to work anymore because the ...rest arguments are not taken into account in the container.invoke method. As a result MyClass instance does not receive the arguments (it only receive the injection).

Any advice ?

Thanks. JB

**Comment by EisenbergEffect** [comment]
Try this:

```
import {Resolver} from 'aurelia-framework';

export class Factory extends Resolver {
  constructor(Type){
    this.Type = Type;
  }

  get(container){
    return function(...rest){
      return container.invokeWithDynamicDependencies(this.Type, rest);
    };
  }

  static of(Type){
    return new Factory(Type);
  }
}
```

We added an explicit method for this use case, so we could fast track/optimize performance of the standard `invoke`.

**Comment by EisenbergEffect** [comment]
(Sorry I forgot this detail in the release notes.)

**Comment by jbrey** [comment]
it works well. 
Thanks for the quick answer !

**Comment by eriklieben** [comment]
For the other google visitors :-) 
This is how to get it working in 0.12.0 and up I think. (works for me in 1.0.0-beta.1.1.3).
```
@resolver
export class Factory { 
  constructor(Type){
    this.Type = Type;
  }

  get(container){
    return function(...rest){
      return container.invoke(this.Type, rest);
    };
  }

  static of(Type){
    return new Factory(Type);
}
```

**Comment by davismj** [comment]
Seems like a common use case, any plan to make a Factory resolver a default option?

**Comment by EisenbergEffect** [comment]
The following code is already part of the DI library for some time now :)

```javascript
/**
* Used to allow injecting dependencies but also passing data to the constructor.
*/
@resolver()
export class Factory {
  /**
  * Creates an instance of the Factory class.
  * @param key The key to resolve from the parent container.
  */
  constructor(key: any) {
    this._key = key;
  }

  /**
  * Called by the container to pass the dependencies to the constructor.
  * @param container The container to invoke the constructor with dependencies and other parameters.
  * @return Returns a function that can be invoked to resolve dependencies later, and the rest of the parameters.
  */
  get(container: Container): any {
    return (...rest) => container.invoke(this._key, rest);
  }

  /**
  * Creates a Factory Resolver for the supplied key.
  * @param key The key to resolve.
  * @return Returns an instance of Factory for the key.
  */
  static of(key: any): Factory {
    return new Factory(key);
  }
}
```

**Comment by danielmeza** [comment]
I´m working with that, but I note that the use of container invoke when the key is a  class type  return a object with all the dependencies and it is grate but I wonder if is necessary to pass the rest argument to the invoke function? or it work fine always when the key is a class type?
