### ISSUE TITLE
autoinject not working

### ISSUE THREAD

**Issue by dpinart** [aurelia/dependency-injection#41]
Hi

I'm working in TypeScript and using gulp/typescript plugin to traspile TS to JS ES5. Since I upgraded to latest aurelia version and run npm install and manually run jspm install for all aurelia plugins autoinject attribute stopped workig.

Thanks

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Do you know anything about this? I've heard this from several individuals but I'm not sure what the issue could be.

**Comment by cmichaelgraham** [comment]
@dpinart can you post the section of your `gulpfile.js` that does the TS compile?

**Comment by dpinart** [comment]
Hi @cmichaelgraham . Sure I can.
Below is mybuild.js gulp task:
var gulp = require('gulp');
var runSequence = require('run-sequence');
var changed = require('gulp-changed');
var plumber = require('gulp-plumber');
var sourcemaps = require('gulp-sourcemaps');
var paths = require('../paths');
var assign = Object.assign || require('object.assign');

var ts = require('gulp-typescript');

var tsProject = ts.createProject('./tsconfig.json', {
  typescript: require('typescript'),
  declarationFiles: false,
  noExternalResolve: true
});


gulp.task('build-system', function () {
  var tsResult = gulp.src([paths.source, paths.dtsSource])
    .pipe(sourcemaps.init())
    .pipe(ts(tsProject));
  return tsResult.js
    .pipe(sourcemaps.write({includeContent: false, sourceRoot: paths.sourceMapRelativePath }))
    .pipe(gulp.dest(paths.output));
});

Below, I'm pasting my tsconfig.json file so you can check typescript compiler settings:

{
    "version": "1.5.1",
    "compileOnSave": false,
    "compilerOptions": {
        "target": "es5",
        "module": "amd",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true
    },
    "filesGlob": [
        "./**/*.ts",
        "!./node_modules/**/*.ts"
    ],
    "files": [
        "./dts/Worklight/worklight.d.ts",
        "./dts/aurelia-protractor.d.ts",
        "./dts/aurelia/aurelia-animator-css.d.ts",
        "./dts/aurelia/aurelia-app-contacts.d.ts",
        "./dts/aurelia/aurelia-binding.d.ts",
        "./dts/aurelia/aurelia-bootstrapper.d.ts",
        "./dts/aurelia/aurelia-dependency-injection.d.ts",
        "./dts/aurelia/aurelia-event-aggregator.d.ts",
        "./dts/aurelia/aurelia-framework.d.ts",
        "./dts/aurelia/aurelia-history-browser.d.ts",
        "./dts/aurelia/aurelia-history.d.ts",
        "./dts/aurelia/aurelia-http-client.d.ts",
        "./dts/aurelia/aurelia-i18next.ts",
        "./dts/aurelia/aurelia-loader-default.d.ts",
        "./dts/aurelia/aurelia-loader.d.ts",
        "./dts/aurelia/aurelia-logging-console.d.ts",
        "./dts/aurelia/aurelia-logging.d.ts",
        "./dts/aurelia/aurelia-metadata.d.ts",
        "./dts/aurelia/aurelia-path.d.ts",
        "./dts/aurelia/aurelia-route-recognizer.d.ts",
        "./dts/aurelia/aurelia-router.d.ts",
        "./dts/aurelia/aurelia-skeleton-navigation.d.ts",
        "./dts/aurelia/aurelia-skeleton-plugin.d.ts",
        "./dts/aurelia/aurelia-task-queue.d.ts",
        "./dts/aurelia/aurelia-templating-binding.d.ts",
        "./dts/aurelia/aurelia-templating-resources.d.ts",
        "./dts/aurelia/aurelia-templating-router.d.ts",
        "./dts/aurelia/aurelia-templating.d.ts",
        "./dts/es6-promise.d.ts",
        "./dts/jasmine.d.ts",
        "./dts/protractor.d.ts",
        "./dts/selenium-webdriver.d.ts",
        "./jspm_packages/github/i18next/i18next@1.9.0/typescript/i18next.d.ts",
        "./jspm_packages/github/i18next/i18next@1.9.0/typescript/lib/jquery.d.ts",
        "./jspm_packages/github/i18next/i18next@1.9.0/typescript/lib/mocha.d.ts",
        "./jspm_packages/github/i18next/i18next@1.9.0/typescript/lib/sinon.d.ts",
        "./jspm_packages/github/i18next/i18next@1.9.0/typescript/tests/i18next.d.tests.ts",
        "./src/animation-main.ts",
        "./src/app.ts"
    ]
}

**Comment by EisenbergEffect** [comment]
Closing now that TS 1.5 is released.

**Comment by dpinart** [comment]
yep. It looks is working now!
