### ISSUE TITLE
Usage without Aurelia?

### ISSUE THREAD

**Issue by Globegitter** [aurelia/dependency-injection#42]
I have to say I really like this functionality that Aurelia provides (well a lot of stuff aurelia does), but I was wondering if it is possible to use this library to inject in any normal ES6 classes or is this somehow coupled to Aurelia?

**Comment by b091** [comment]
Here you go: https://github.com/aurelia/dependency-injection/issues/26

**Comment by Globegitter** [comment]
ahhh thank you that does indeed answer my question.
