### ISSUE TITLE
Bug with @autoinject and TypeScript 1.5

### ISSUE THREAD

**Issue by bchavez** [aurelia/dependency-injection#44]
Hi,

I have the following TypeScript 1.5 code:

```ts
import {autoinject,inject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";
import * as JSData from "js-data";

const baseUrl = "/api/auth";

@autoinject // BUG: store in constructor is anonymous function
export class AuthManager {

    constructor(client : HttpClient, store:JSData.DS) {
        this.http = client;
        this.store = store; //injected store is an anonymous function that returns undefined
        
        this.meDao = this.store.defineResource<Domain.Me>("me");
    }
```
The TS ES5 output is as follows:
```javascript
//NOTICE: Missing "js-data" define import.
define(["require", "exports", "aurelia-framework", "aurelia-http-client"], function (require, exports, aurelia_framework_1, aurelia_http_client_1) {
    var baseUrl = "/api/auth";
    var AuthManager = (function () {
        function AuthManager(client, store) {
            this.http = client;
            this.store = store;
            this.meDao = this.store.defineResource("me");
        }
```
First problem here is **"js-data"** is actually ***missing*** from the `define()` call. @louislewis2 helped me find a hack-ish work around that forces an import by adding `/// <amd-dependency path="js-data" />` to the top of my **.ts** file:

```ts
/// <amd-dependency path="js-data" />
import {autoinject,inject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";

const baseUrl = "/api/auth";

import * as JSData from "js-data";
@autoinject // BUG: store in constructor is anonymous function
export class AuthManager {

    constructor(client : HttpClient, store:JSData.DS) {
        this.http = client;
        this.store = store; //injected store is an anonymous function that returns undefined
        
        this.meDao = this.store.defineResource<Domain.Me>("me");
    }
```
And finally **"js-data"** is imported; however, the injected store is ***still*** an anonymous function that returns undefined.
![screen444](https://cloud.githubusercontent.com/assets/478118/9099825/425ef7ac-3b89-11e5-98a8-b73e43a3d266.png)

Ultimately, going down this road with **`@autoinject`** won't work.

----

However, if I use `@inject(HttpClient, JSData.DS)`, everything **will** work as expected (including removing `/// <amd-dependency path="js-data" />` hacky workaround).

```ts
import {autoinject,inject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";
import * as JSData from "js-data";

const baseUrl = "/api/auth";

@inject(HttpClient, JSData.DS) //Works correctly.
export class AuthManager {

    constructor(client : HttpClient, store:JSData.DS) {
        this.http = client;
        this.store = store; //works exactly as expected
        
        this.meDao = this.store.defineResource<Domain.Me>("me");
    }
```

![screen445](https://cloud.githubusercontent.com/assets/478118/9099896/08beca4e-3b8a-11e5-8419-245e5cde5a89.png)

I filed this bug report because I think the expected behavior between using `@autoinject` and `@inject(...)` should be the same (I hope).

Thanks,
Brian

PS. I've configured TS to `emitDecoratorMetadata` and the `HttpClient` is injected in both cases.

**Comment by EisenbergEffect** [comment]
I don't think this is anything that Aurelia can solve. It looks like an issue with the TS compiler since the generated code is incorrect.
