### ISSUE TITLE
add support for angular2 style constructor parameter decorators

### ISSUE THREAD

**Issue by chrisdostert** [aurelia/dependency-injection#49]
in angular 2 di you can decorate each constructor parameter individually. This is very desirable for reasons such as proximity principle, ability to export classes inline (otherwise syntax error if decorator on class), more future proof (what if constructor overloading supported someday?). It would be awesome to see this feature added to aurelia dependency-injection. 

snip from [dependency-injection-in-angular-2](http://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html):
```js
import { Inject } from 'angular2/di';

class Car {
  constructor(
    @Inject(Engine) engine,
    @Inject(Tires) tires,
    @Inject(Doors) doors
  ) {
    ...
  }
}
```

**Comment by EisenbergEffect** [comment]
Currently, I'm not sure if parameter decorators are even part of the ES7 decorators spec. Also, there's no plan, for a future version of JS, that I know of, to add constructor overloads. So, for the moment, this doesn't seem to be in line with web standards. If you are programming in TypeScript, you can supply the types themselves and decorate the class with `@autoinject` like so:

```
import { autoinject } from 'aurelia-dependency-injection;

@autoinject
class Car {
  constructor(
    engine: Engine,
    tires: Tires,
    doors: Doors
  ) {
    ...
  }
}
```

So, the co-location effect is the same. All these things as consideration, I don't think we want to implement this now.

**Comment by chrisdostert** [comment]
Good to know & thanks for the guidance. Love the autoinject
