### ISSUE TITLE
Constructor injection works only for one argument (TypeScript 1.6)

### ISSUE THREAD

**Issue by alecor191** [aurelia/dependency-injection#54]
Hi,

I'm seeing an issue where Aurelia's IOC works fine for one argument, but when I try to inject 2 arguments, I get a value for the first one, but "undefined" for the second one when an instance of my class is created. Here my scenario:

I have a simple TypeScript 1.6 class (see below). When I run this and put a breakpoint in the constructor, I see that I get an instance of "httpClient" argument, but "undefined" for "authStatus".

```typescript
import {inject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";

import {AuthStatus, AuthInfo} from "../Security/user-auth";

@inject(HttpClient)
@inject(AuthStatus)
export class QuickAdd {
    constructor(httpClient: HttpClient, authStatus: AuthStatus) {
        ...
    }

    ...
```

Here the generated JS code from the TS compiler:
```javascript
/// <reference path="../wwwroot/jspm_packages/github/aurelia/framework@0.16.0/aurelia-framework.d.ts" />
/// <reference path="../wwwroot/jspm_packages/github/aurelia/http-client@0.11.0/aurelia-http-client.d.ts" />
System.register(["aurelia-framework", "aurelia-http-client", "../Security/user-auth"], function(exports_1) {
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
        switch (arguments.length) {
            case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
            case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
            case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
        }
    };
    var aurelia_framework_1, aurelia_http_client_1, user_auth_1;
    var QuickAdd;
    return {
        setters:[
            function (aurelia_framework_1_1) {
                aurelia_framework_1 = aurelia_framework_1_1;
            },
            function (aurelia_http_client_1_1) {
                aurelia_http_client_1 = aurelia_http_client_1_1;
            },
            function (user_auth_1_1) {
                user_auth_1 = user_auth_1_1;
            }],
        execute: function() {
            QuickAdd = (function () {
                function QuickAdd(httpClient, authStatus) {
                    ...
                }
                QuickAdd = __decorate([
                    aurelia_framework_1.inject(aurelia_http_client_1.HttpClient),
                    aurelia_framework_1.inject(user_auth_1.AuthStatus)
                ], QuickAdd);
                return QuickAdd;
            })();
            exports_1("QuickAdd", QuickAdd);
        }
    }
});
```

First I thought I'm doing something wrong as HttpClient is an Aurelia FW class whereas AuthStatus is a class I implemented. But what's interesting is the following: If I remove the HttpClient argument (and the corresponding "@inject(HttpClient)" line) then I get an instance of AuthStatus for "authStatus". 
Adding the HttpClient parameter and related code back and I only get a HttpClient instance and "undefined" for AuthStatus. IOW the following works:

```typescript
import {inject} from "aurelia-framework";

import {AuthStatus, AuthInfo} from "../Security/user-auth";

@inject(AuthStatus)
export class QuickAdd {
    constructor(authStatus: AuthStatus) {
        ...
    }

    ...
```

I tried to debug it a bit and the following caught my attention (in aurelia-dependency-injection.js). I was expecting that metadata information for the QuickAdd constructor would contain an array of 2 keys (one for each argument). Instead I only see one for HttpClient.

![screenshot1](https://cloud.githubusercontent.com/assets/6270008/10418173/e301c99c-7053-11e5-8715-f68b006065a1.png)

I'm new to Aurelia and I don't really know the code base, but I thought I should mention it.

Any idea what I'm doing wrong?

__Something that may be related__: As mentioned above DI works fine if I have 1 argument. But I noticed that if I use "@autoinject()", then the constructor parameter is "undefined" (even if I only use a single argument in the constructor - no matter whether I use HttpClient or AuthStatus). If I replace "@autoinject()" with "@inject(ClassName)" for the argument I'm trying to inject into the constructor, then it works fine.

My environment:
- TypeScript 1.6
- I use JSPM with Babel
- aurelia-framework 0.16.0
- Using Chrome as browser

**Comment by EisenbergEffect** [comment]
You are using the decorator incorrectly. You should have one `inject` decorator and it should have one argument for each constructor parameter. So, like this:

```
import {inject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";
import {AuthStatus, AuthInfo} from "../Security/user-auth";

@inject(HttpClient, AuthStatus)
export class QuickAdd {
    constructor(httpClient: HttpClient, authStatus: AuthStatus) {
        ...
    }

    ...
```

However, if you are using TypeScript, then we can pick up the types from the constructor, so you can use the `autoinject` decorator instead, like this:

```
import {autoinject} from "aurelia-framework";
import {HttpClient} from "aurelia-http-client";
import {AuthStatus, AuthInfo} from "../Security/user-auth";

@autoinject()
export class QuickAdd {
    constructor(httpClient: HttpClient, authStatus: AuthStatus) {
        ...
    }

    ...
```

**Comment by alecor191** [comment]
Thanks a lot! That was the issue.
