### ISSUE TITLE
autoinject does not always work

### ISSUE THREAD

**Issue by gregoryagu** [aurelia/dependency-injection#56]
I like the concept of autoinject, and have implemented it in my app replacing inject.

And it seems to work great, most of the time.  Inject works 100% of the time.  So far is is unreproducible, however.  But I have attempted to get this working several times.  Each time, it starts out working as it should, and then at some point will stop working again. If I switch the offending code back to inject, it works until the next viewmodel uses autoinject and it will fail there. There is no error message other than the expected injections are null.

If I can nail this down better, I will but I did want to mention it in case anyone else is running into the same issue.

**Comment by EisenbergEffect** [comment]
When it fails, can you examine your source code and see if TS is writing out the `design:paramtypes` metadata? If it isn't, then the error is in the TS compiler or the compiler configuration. If it is, but we aren't getting it for DI, then the error is on our side.

**Comment by gregoryagu** [comment]
Ok, I converted back to using autoinject and so far no problems.  I will continue to monitor and if there are any more issues, I will check the `design: paramtypes` and create new issue. But for now, will close.

**Comment by gregoryagu** [comment]
Just to follow up on this. It did occur again where autoinject stopped working.

I viewed the generated code, and 'design: paramtypes` was missing from it.

The fix was to force a regenerate and it brought it back as expected.

**Comment by EisenbergEffect** [comment]
@gregoryagu Could it be that you have two different things trying to compile your code? and one is configured to emit the metadata but the other isn't?

**Comment by gregoryagu** [comment]
I am using VS 15, so it's doing all the work of compiling.  So I don't know of a second compiler in the works.
