### ISSUE TITLE
Object's lifetime clarifications

### ISSUE THREAD

**Issue by jenyayel** [aurelia/dependency-injection#59]
May be I'm missing something, but it states in [docs](http://aurelia.io/docs.html#dependency-injection): 
*By default, the DI container assumes that everything is a singleton instance; one instance for the app*

And it is exactly the opposite - any object injected by `@inject` is transient (constructor invoked each time). Now, I can change it and place `@singleton(false)` and the constructor will be invoked only once, however isn't it misleading (singleton=false means transient)?

Did I misunderstand something?

**Comment by EisenbergEffect** [comment]
Please provide a code sample that I can test to reproduce the behavior.

**Comment by EisenbergEffect** [comment]
Objects are singletons in their container. However, if a child container is created and the parent is overridden with new configuration for new instances, then new instances will be created. This is how we isolate custom elements and attributes and how the router and compose work. If you want to use a singleton with the router or compose, you would use `@singleton()` on the class.

**Comment by jenyayel** [comment]
Rob, thanks for you answer, however I'm still confused. 

1. Take a look at this very [simple service](https://github.com/Enttoi/enttoi-ui-web/blob/master/src/services/api.js). What makes it singleton (and only this) is placing the attribute `@singleton(false)`. Doesn't this mean NOT singleton? It would make sense if it was the opposite - `@singleton(true)`.
2. This service is injected into [this viewmode](https://github.com/Enttoi/enttoi-ui-web/blob/master/src/dashboard.js) via `@inject`. Each time I navigate to this view, unless `@singleton(false)` specified on service, the service recreated. So, what triggers a creation of child container in this case?

**Comment by EisenbergEffect** [comment]
Just remove the singleton from the service. You don't need it to create an app-level singleton. Providing the `singleton` decorator and passing true specifies that it's a singleton only in the child container, which is why you are seeing it re-created...because the router creates a child container to create screens within when navigating.

**Comment by jenyayel** [comment]
Removing the annotation cause the service to be recreated each time. This is why I went to this direction of decorating with `@singleton`. 

What you tell is makes a lot of sense, however this is not what I'm experiencing. May be it is version related? I'm running the latest for all packages.

**Comment by EisenbergEffect** [comment]
Tell me how to reproduce it in the skeleton-navigation app. I'll test it and fix it if there's a bug. It would be a serious bug if it was there, but I need to know how to re-create the issue in that simple app. I haven't been able to.

**Comment by jenyayel** [comment]
You are right, I cannot reproduce it in skeleton-navigation either. I'll try to figure out why it happens in my app and update if it will be relevant to Aurelia. Thank you very much for being so patient.

**Comment by zeko77** [comment]
I had a problem where i imported in 2 classes like:
import {DataRepository} from 'services/dataRepository';
and
import {DataRepository} from 'services/datarepository';

As a consequence, new object was created.
Imports are case sensitive.
When i corrected it to same case it started working as it should.

**Comment by Mikiewitch** [comment]
Might it be related to applications created by Aurelia CLI? I am experiencing the same issue.
