### ISSUE TITLE
Automatic injection of `App` does not work with the initial route module

### ISSUE THREAD

**Issue by niieani** [aurelia/dependency-injection#61]
Here's the App and its router:
```ts
export class App {
  session:AppSession = new AppSession();

  private router: RouteConfig;

  configureRouter(config:RouterConfiguration, router: RouteConfig) {
    config.title = 'one';
    config.options.pushState = true;
    config.addPipelineStep('authorize', AuthorizeStep);
    config.map([
      { route: ['', 'one'], name: 'one', moduleId: 'one', auth: true, title: 'one' },
    // ...
    ]);

    this.router = router;
  }
}
```

Here's `One`:
```ts
@inject(App)
export class One {
  // this does not work (error "trying to inject something that doesn't exist):
  constructor(app:App) {
    this.app = app;
  }
}
```

However if we replace it with this, it does work:
```ts
import {Container} from "aurelia-dependency-injection";
export class One {
  // manually getting the object from the DI:
  constructor() {
    this.app = Container.instance.get(App);
  }
}
```

I suppose the `App` instance is added to the DI store too late. I even tried `Lazy.of(App)` but for some reason that gives the same error, even after `setTimeout` of a second (why?).
I should add that if the initial route's class doesn't try to inject `App`, but the user navigates to one that does, the injection does work (so the problem should be somewhere between the router and DI).

**Comment by EisenbergEffect** [comment]
The error message you are receiving makes me think that you may have not imported App into your One module. Can you confirm?

**Comment by niieani** [comment]
I am positive App is imported. After all, the second version I provided works, plus it also works when switching from a different route. It's either a DI or a Router module problem.
I've also tried @autoinject, since I'm using TS, but same effect.

**Comment by EisenbergEffect** [comment]
If I take the navigation skeleton and simply try to inject App into the Welcome view model, will that reproduce the problem?

**Comment by niieani** [comment]
I'll try and get a working sample to you in a moment.

**Comment by niieani** [comment]
Trying to recreate the problem I seem to have found why it was occurring - my bad, the class inside the file `one.js` was not called `One`. The funny thing is, everything else was working - Aurelia was constructing the object and the view, except for the injection (how is that even possible?). Perhaps Aurelia could send a warning to the console in these sorts of cases?

**Comment by niieani** [comment]
In the end it seems to be a very, very odd TypeScript bug. Some code inside of my AuthorizeStep that wasn't even executing (?!) was somehow the culprit. I can reproduce, but can't understand what exactly is happening to cause this. Sorry for the trouble.

**Comment by EisenbergEffect** [comment]
No trouble. If you track it down and have some ideas about how we can improve things from our side, just let me know.
