### ISSUE TITLE
Injecting a third party javascript with parameters in constructor

### ISSUE THREAD

**Issue by BoudewijnvanVeen** [aurelia/dependency-injection#62]
I am trying to get Aurelia working with this [Azure AD](https://github.com/AzureAD/azure-activedirectory-library-for-js) ,but i am unable to get it working.

I modified the adal.js file a bit to be able to load it with systemjs:

```
define(['exports'], function (exports) {
    'use strict';

    exports.__esModule = true;
    exports.AuthenticationContext = function (config) { return new AuthenticationContext(config); }
     ...
     var AuthenticationContext;
     ...
     AuthenticationContext = function (config) {
     ...
```

and i try to inject like this:

```
import {inject} from "aurelia-framework";
import {AuthenticationContext} from "adal"

@inject(AuthenticationContext)
export class AdalService {    

    private authContext: AuthenticationContext;

    public adalConfig = {
        instance: 'https://login.microsoftonline.com/',
        tenant: 'xxxxx.onmicrosoft.com',
        clientId: 'xxxxxx',
        extraQueryParameter: 'nux=1',
        cacheLocation: 'localStorage',
        redirectUri: window.location.host
   }

    constructor(authenticationContext) {
        this.authContext = new authenticationContext(this.adalConfig);
    }
    ...
```

And every seems to work except that the config is never passed to the javascript. e.g. in the adal.js the parameter 'config' is always 'undefined'.

How do i get this working without modifying the third party javascript to much.

**Comment by EisenbergEffect** [comment]
You are calling the contructor in your modified code, then asking that instance to be injected...then calling it again like it is a constructor. That's not valid JavaScript. I'm not sure what the original code looked like so not sure how to advise you. You might try asking about this in the gitter channel. That's the best place for questions/hellp. gitter.im/aurelia/discuss

**Comment by StrahilKazlachev** [comment]
It doesn't work like that. What is passed to your `AdalService` constructor is an instance of the "class" passed to the `@inject` - `AuthenticationContext`. You should register in the DI a `handler` or a `resolver` for the `AuthenticationContext` so that you can have control over the instantiation.
