### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/dependency-injection#63]
For the ORM I'm building, I'm trying to create a decorator which lets you specify which Entity a particular property belongs to (association aka relation). The decorator is called `association`.

Example:

```javascript
import {association, Entity} from 'spoonx/aurelia-orm';
import LocationEntity from './location';

export default class Company extends Entity {
  constructor () {
    super(...arguments);

    this.setResource('company').enableValidation();
  }

  @association(LocationEntity)
  locations = null;
}
```

Now, when fetching a `Company` and populating the result (into entities that _do_ stuff) you get a `Company` instance, with a `locations` property which is a `Location` entity (it uses the container in the library to fetch instances). This works fine.

The problem I'm seeing, is when I try to do specify an association from both sides. The reason for this is that now, you have a circular dependency. `Location` wants to specify `Company` as an association, and `Company` wants to specify `Location` as a dependency.

It's not really a bug, but more of a problem I'm facing because of the way DI works. If DI were to be string based (e.g. define dependencies by key, and use that key to fetch dependencies) I would be able to lazy get the dependencies from the container.

Any help, tips or suggestions would be greatly appreciated.

**Comment by EisenbergEffect** [comment]
The DI can use any type of object as a key. So, you can use a string if you like.

**Comment by RWOverdijk** [comment]
But dependencies don't get resolved as strings, so how would I get that working? Would I need my own container that requires you to register your dependencies explicitly?

**Comment by EisenbergEffect** [comment]
Yes, during application startup, you would manually configure the container. Something like this:

```
container.registerSingleton('service-a', ServiceA);
container.registerTransient('service-b', ServiceB);
```
