### ISSUE TITLE
decorators on class property declarations throwing error

### ISSUE THREAD

**Issue by iamcdonald** [aurelia/dependency-injection#64]
I thought that I should be able to add a decorator to a property declaration within a class (used as a controller) and all would be fine, and it is within babel outside of aurelia. However, the following code causes an error within aurelia.

```js

const aDecorator = (t, k, d) => {
    return d;
}

export class Thing {
  
 @aDecorator
  aProp;

}
```

If I don't modify the descriptor I get 
```
TypeError: Cannot assign to read only property aProp
```

If I add a setter method i.e.
```js
const aDecorator = (t, k, d) => {
  let x;
  d.set = y => x = y;
  d.get = () => x;
  return d;
}
```
I get
```
Error: Error invoking Thing.
```

However, if I just set the descriptors writable property to be ```true``` and nothing else aurelia no longer throws an error.

Am I doing something wrong/missed something? Are decorators not allowed within aurelia unless they are sanctioned by the framework itself?

Thanks

**Comment by EisenbergEffect** [comment]
It's an issue with decorators, not Aurelia. It may be related to the version of Babel you are using. The descriptor needs to be made writable. It isn't by default...I'm not sure if that was changed at some point...so like I said, it may be dependent on the Babel version you used for your test vs. the one that you were using with Aurelia.

**Comment by iamcdonald** [comment]
Ah, yeah, that seems to be the case, just threw me that the error was bubbling up through aurelia. It seems it's fixed in v6 of babel however, I've heard that upgrading to v6 and using aurelia may prove to be an issue (certainly all the individual parts seems to rely on 5.8.34 or there abouts). Is this true or should it be relatively easy?

**Comment by EisenbergEffect** [comment]
Using Babel 6 isn't really an option just yet due to language features they have removed and some other issues. We are hopeful that it will be addressed soon.

**Comment by iamcdonald** [comment]
Ah, that's a shame. 
Guess we'll just have to work round it for now. 
Thanks.
