### ISSUE TITLE
Singleton custom element viewmodel isn't singleton

### ISSUE THREAD

**Issue by sapiens** [aurelia/dependency-injection#65]
I have a custom element (called Confirm) whose view model I want to be a singleton. Basically, the element is loaded in a view  but then its view model will be used by other custom elements and they all need to work with the same instance of the VM.

Decorating the element with `singleton()` doesn't prevent the viewmodel constructor to be called twice (once when Confirm element is loaded/rendered and once when it's injected as a dependency).

```javascript
//custom element code

@singleton()
export class Confirm {
      constructor() {
       console.log("confirm created");

   }
}

//other custom element using Custom

@autoinject
export class Delete {
       constructor(public confirm:Confirm) {

      // alternate approach, it doesn't work either
      // this.confirm = Container.instance.get("Confirm");

    }

//in the view
 <require from="./resources/confirm"></require>
    <confirm></confirm>
    <delete></delete>
```

I get "confirm created" twice. I don't know if it's a bug or it's me not knowing how to use the DI Container.

**Comment by StrahilKazlachev** [comment]
I may be wrong, and if so I hope someone corrects me, but ..., your `Confirm` may be created in views having different `Container`s. You have the root container and child containers get created from it. So `Confirm` gets created as singleton in different containers. You can try and register it yourself in the root container as singleton.
```
aurelia.use
    .instance(Confirm, confirmInstance);
```
Or you can provide an `Invoker` that always returns the same instance.

**Comment by sapiens** [comment]
Tried that, it's still invoked twice but definitely it's something related to the root/children DiC . Is there a way to force a singleton to be a global  singleton?

**Comment by sapiens** [comment]
After some tests, it's clear that the custom element model used in the view it's not the same as the one from the Container. Basically, I've registered the view model as an instance  and set its property in the view  (via binding). 

```javascript
 a.use.instance(Confirm, Confirm.instance);
```

```html
<confirm item="test"></confirm>
```
The instance available inside the Container still has the default value, while the one rendered shows "test".

**Comment by EisenbergEffect** [comment]
Custom elements can't be singletons because what would happen if you did this:

```
<confirm></confirm>
<confirm></confirm>
```

If you need to share something, I recommend that you extract a singleton service that is shared by instances of the custom element and any other consumers in the app.

**Comment by sapiens** [comment]
It would be a bug, since I need only one instance of `confirm` :P . Anyway, this is what I did, sort of, I've used a mediator.
