### ISSUE TITLE
Can't set a single instance of EventAggregator shared by services and view models

### ISSUE THREAD

**Issue by sapiens** [aurelia/dependency-injection#66]
It's me and my singletons again! I have this in my config.js

```javascript
a.use.container.registerSingleton(EventAggregator); 
```
In my root component I get the bus instance 

```javascript
this.bus = Container.instance.get(EventAggregator);
console.log(this.bus);
```
In another service I'm trying to access the same instance of the bus

```javascript
export class CachedAssets {
    constructor() {
        console.log("init cached assets");
        console.log(Container.instance.get(EventAggregator));
    }
}
```
The result is 2 different instances. Either `Container.instance` is not the global root (I've tried with makeGlobal() too, no difference) or the services root container is different than the components root container. The bottom line is I can't have a singleton for the `EventAggregator` that can be shared by all services/view models. Or I don't know how to set it up to work like that.

**Comment by EisenbergEffect** [comment]
The EA is a singleton by default. If you want a global singleton, you don't have to do anything. When you do this, you are registering a second singleton instance of the same type because Aurelia custom registers the EA.

**Comment by sapiens** [comment]
Thing is, I've done this because the normal dependency injection gave me different instances too. This was my "forced singleton" workaround. I've tried again with the 'normal' approach, with normal constructor deps and no manual container config and it's still 2 instances. 

The only way I got it to work was, having a 'real' singleton, skipping the Container all together

**Comment by EisenbergEffect** [comment]
Can you confirm that you don't have forks in your packages?

**Comment by sapiens** [comment]
My js skills including package management are pretty  basic  but it seems that I do have some

```
ok   Up to date - aurelia-framework as npm:aurelia-framework@^1.0.0-beta.1.0.3 (
1.0.0-beta.1.0.3)
     Installed Forks

                       github:aurelia/path 0.9.0 0.11.0
                               npm:core-js 0.9.18 1.2.6
```

**Comment by sapiens** [comment]
OK, I did a clean install (removed everything manually first) and it seems it works ok now. Thank you!

**Comment by EisenbergEffect** [comment]
You should definitely start by cleaning that up. That can cause all sorts of issues. Someone in the gitter channel can provide some guidance on that.
