### ISSUE TITLE
Injection in case of class extention

### ISSUE THREAD

**Issue by kdeberni** [aurelia/dependency-injection#68]
I am not sure if this is an issue at all but I would like to ask at least a question.
I have a case of extending a class like this:

 ```javascript
@autoinject
export class Child {
    constructor(instanceOfSomeClass: SomeClass) { }
}

export class Parent extends Child {

}
```

In this case if I try to inject somewhere class Parent I am reciving error 'key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?'. What I had to do is to add autoinject attribute to Parent class and repeat (or extend) it's constructor and call Child constructor. I mean something like this:

 ```javascript
@autoinject
export class Parent extends Child {
    constructor(instanceOfSomeClass: SomeClass) {
        super(instanceOfSomeClass);
    }
}
```

In earliar versions (before beta) I didn't have to do this. Is this intentional or...?

**Comment by jdanyow** [comment]
`@autoInject` / `@inject` need to appear on the derived class, not the base class.

**Comment by kdeberni** [comment]
Bottom line, this is how it should be.? Earlier it was working because it was actually a 'bug'. And the repeated constructor also have to be on Parent.
If so, then we can just close this 'issue'.

**Comment by EisenbergEffect** [comment]
Per the ES 2015 spec, you cannot inherit a class without providing the super call in the constructor. So, if it worked in the previous version, I would say it was a bug.
