### ISSUE TITLE
Can't get by name using decorator

### ISSUE THREAD

**Issue by unional** [aurelia/dependency-injection#69]
This works:
```js
        class AppX{
          foo() { console.log('foo')}
        };
        var container = new Container();
        container.registerTransient('AppX', AppX);
        var app = container.get('AppX');
        expect(app).toEqual(jasmine.any(AppX));
```

but this does not:
```js
        @transient('AppX')
        class AppX{
          foo() { console.log('foo')}
        };
        var container = new Container();
        var app = container.get('AppX');
        expect(app).toEqual(jasmine.any(AppX));
```

I understand the reason is being the container does not have a handle to `AppX` when calling `container.get('AppX')` so `autoRegister` wouldn't able to find the function and get the meta data attached to it.

I want this feature for generic rendering, i.e. the engineer would not know the type in advance.
This is the best approach because each component (`AppX`) can decorate its intent usage.

If I have to rely on `container.registerTransient(...)`, I need to find a place to do the registration where the `container` is known, and it becomes the responsibility of the consuming engineer (typically application engineer) to do the registration, not ideal.

would it work well if there is a `Conatiner.decorationContainer` that will have a hold of the references and the resolving logic will consult it at `container.get()`?

I would be happy to contribute.

**Comment by jdanyow** [comment]
@unional can you explain a little bit more about your setup?  Specifically this part:

>I want this feature for generic rendering, i.e. the engineer would not know the type in advance.

How are these classes used- what does the developer ultimately do with all the string registration ids- are they used in `@inject(..)` statements or are they calling `container.get` as you have done in the test code above?

 How do the modules containing these transient components get loaded?  (assuming if the dev doesn't know the class then they don't know the module ids either).

**Comment by unional** [comment]
For generic rendering, the engineer do not know to need or access to the class.  The appropriate class is chosen based on the data and metadata coming in, typically from database.

So there are three engineer roles here. The framework engineer, the component engineer, and the application engineer.
- The framework engineer wrote the framework.
- The component engineer design the component.
- The application engineer use the framework and component to write application.

The key part regarding responsibility is this:
The component engineer has the initial say on how the component should be used (e.g. singleton or transient, data type / structure it supports, what kind of customization is available, how extensible it is)
The application engineer can customize and extends the component, but they cannot fundamentally change some of the basic premises of the component. For example, whether the component should be used as a singleton or transient)

> are they used in @inject(..) statements or are they calling container.get

Framework engineer and component engineer uses both.
Application engineer typically don't need to use any. When they need to, it would mostly be `@inject` (for generic DI, not for UI component). They would use `container.get()` if they want to further customize or create component, but that means they step into the component engineer role.

> How do the modules containing these transient components get loaded?

The application engineer determine at the start of the application on which *module* they want to use, much like any UI framework such as `kendo` or `jquery UI`.

> if the dev doesn't know the class then they don't know the module ids either

Yes and no. When you use **any** UI library in javascript, you are relying on documentation to know what is available. e.g. for `webix`:
```js
webix.ui({
  rows:[
    { type:"header", template:"My App!" },
    { cols:[
      { view:"tree", data:tree_data, gravity:0.4, select:true },
      { view:"resizer" },
      { view:"datatable", autoConfig:true, data:grid_data }
    ]}
  ]
})
```
You need to know there are views called "tree", "resizer", and "datatable". You know the `module id` but you don't know the class.

Does it help? :tulip:

**Comment by EisenbergEffect** [comment]
You will need to register the simple itself at app startup:

```javascript
var container = new Container();
container.registerSingleton('AppX', AppX);
```

Just like with any server or other DI, if the key and the value are not the same, you need to perform configuration at application startup to tell it what is what. With the above registration, you can then do this.

```javascript
@inject('AppX')
export class SomeOtherClass {
  cosntructor(app) { ... }
}
```
