### ISSUE TITLE
jspm minified bundle throws an error with di included

### ISSUE THREAD

**Issue by djindjic** [aurelia/dependency-injection#7]
I have some strange behavior when I want to compile some project with di into minified bundle. Not-minfied bundle is doesn;t throw any error. I have posted this issue at jspm-cli [here](https://github.com/jspm/jspm-cli/issues/353) but it could be di related issue.

Also , you can see this console error in my sample project which I have exposed to gh pages:
http://djindjic.github.io/jspm-bundle/

app is pretty simple:
https://github.com/djindjic/jspm-bundle/blob/master/lib/app.js

and If I comment static annotations() there is no error

**Comment by EisenbergEffect** [comment]
Out of curiosity, can you update everything to the latest versions? We switched from amd modules over to system.register. I'm wondering if that will have any affect on things.

**Comment by djindjic** [comment]
unfortunately it seems like update hasn't fixed my bundle. Here is updated versions:

```js
System.config({
  "map": {
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.2.1",
    "github:aurelia/dependency-injection@0.2.1": {
      "aurelia-metadata": "github:aurelia/metadata@0.2.3",
      "core-js": "npm:core-js@0.4.1"
    },
    "github:jspm/nodelibs@0.0.8": {
      "Base64": "npm:Base64@0.2.1",
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.4",
      "inherits": "npm:inherits@2.0.1",
      "json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});
```

**Comment by EisenbergEffect** [comment]
sorry, you probably  need to jspm install them actually

On Wed, Jan 7, 2015 at 1:34 PM, Aleksandar Djindjic <
notifications@github.com> wrote:

> unfortunately it seems like update hasn't fixed my bundle. Here is updated
> versions:
>
> System.config({
>   "map": {
>     "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.2.1",
>     "github:aurelia/dependency-injection@0.2.1": {
>       "aurelia-metadata": "github:aurelia/metadata@0.2.3",
>       "core-js": "npm:core-js@0.4.1"
>     },
>     "github:jspm/nodelibs@0.0.8": {
>       "Base64": "npm:Base64@0.2.1",
>       "base64-js": "npm:base64-js@0.0.8",
>       "ieee754": "npm:ieee754@1.1.4",
>       "inherits": "npm:inherits@2.0.1",
>       "json": "github:systemjs/plugin-json@0.1.0"
>     }
>   }
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/dependency-injection/issues/7#issuecomment-69068105>
> .
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by djindjic** [comment]
yes, I am. Delete jspm_packages and do jspm install again. Here is jspm_pakages in my repo:
https://github.com/djindjic/jspm-bundle/tree/master/jspm_packages/github/aurelia

**Comment by EisenbergEffect** [comment]
Can you send me the minified bundles?

On Wed, Jan 7, 2015 at 1:40 PM, Aleksandar Djindjic <
notifications@github.com> wrote:

> yes, I am. Delete jspm_packages and do jspm install again. Here is
> jspm_pakages in my repo:
>
> https://github.com/djindjic/jspm-bundle/tree/master/jspm_packages/github/aurelia
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/dependency-injection/issues/7#issuecomment-69068996>
> .
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by djindjic** [comment]
Sure, here is a minified bundle in my repo:
https://github.com/djindjic/jspm-bundle/blob/master/bundle-4.js

**Comment by EisenbergEffect** [comment]
We'll handle this under out bundling work...being tracked separately.

**Comment by djindjic** [comment]
Can I track it? Have new issue opened?
