### ISSUE TITLE
container.getAll returns inconsistent type

### ISSUE THREAD

**Issue by speigg** [aurelia/dependency-injection#71]
The questionable behavior I'm seeing: 
1. If the container contains no values for a given key, `container.getAll(key)` returns an empty array.
2. If the container contains only one value for a given key, `container.getAll(key)` returns the value.
3. If the container contains more than one value for a given key, `container.getAll(key)` returns an array of values. 

Expected behavior is that `container.getAll(key)` always returns the same type (i.e, an array, containing either zero, one, or multiple values). Certainly, this is what the jsdoc and typescript annotations for `container.getAll` suggest: 
```ts
    /**
      * Resolves all instance registered under the provided key.
      * @param key The key that identifies the objects to resolve.
      * @return Returns an array of the resolved instances.
      */
    getAll(key: any): any[];
```

The issue also affects the `All.of(key)` resolver (which uses the `container.getAll` API).

**Comment by EisenbergEffect** [comment]
I'll get this fixed ASAP.
