### ISSUE TITLE
Splat import breaks @autoinject

### ISSUE THREAD

**Issue by Roustalski** [aurelia/dependency-injection#72]
I'm not sure why, but when I use a splat import the @autoinject feature breaks.

```javascript
import {autoinject} from 'aurelia-framework';
...
import * as core from '../core/module';
import * as utils from '../utils/module';
import {AppRoutes} from './module';
...
@autoinject
export class Shell {
...
    constructor(log: utils.Log, settings: core.Settings, routerConfig: AppRoutes) {
        this.logger = log;
        this.settings = settings;
        this.routerConfig = routerConfig;

        //When debugging in chrome, this variable gets succesfully created.
        //but, the settings injection is not working via @autoinject
        let blah = new core.Settings();
    }
...
}
```

For some reason, the constructor gets injected with two empty objects for log and settings. When I new out a new Settings(), I get the correct type as expected.

I created a tag so you can checkout the project/tag and gulp watch in order to debug and get the stack trace.

https://github.com/Roustalski/au-demos/blob/broke-auto-inject/modular-ts/src/client/app/layout/shell.ts#L68

**Comment by Roustalski** [comment]
By way of comparison, [I swapped out](https://github.com/Roustalski/au-demos/blob/ts_port_splat_auto_inject_broken/modular-ts/src/client/app/layout/shell.ts#L8) the @autoinject for a normal @inject and the injections worked as expected.

**Comment by EisenbergEffect** [comment]
This may be an issue with the TypeScript compiler. Take a look at the generated code and see if it has properly encoded the type information.

**Comment by Roustalski** [comment]
It looks OK to me, but I'm definitely not an expert in this area:

```
-            aurelia_framework_1.autoinject,
+            aurelia_framework_1.inject(utils.Log, core.Settings, module_1.AppRoutes),
```
[diff](https://github.com/Roustalski/au-demos/blob/ts_port_splat_auto_inject_broken/modular-ts/diff)
[generated inject](https://github.com/Roustalski/au-demos/blob/ts_port_splat_auto_inject_broken/modular-ts/sample-shell-inject.js)
[generated autoinject](https://github.com/Roustalski/au-demos/blob/ts_port_splat_auto_inject_broken/modular-ts/sample-shell-autoinject.js)

**Comment by PascalPrecht** [comment]
@Roustalski Shouldn't this be `@autoinject()` instead of `@autoinject` ?

**Comment by EisenbergEffect** [comment]
@PascalPrecht Does TS enforce the use of parens?

**Comment by PascalPrecht** [comment]
No it doesn't but it also doesn't translate/execute the decorator if there are no parens.

**Comment by EisenbergEffect** [comment]
Interesting. That's different from how Babel handles it. However, I think it's a bit more consistent the way TS is doing it.

**Comment by PascalPrecht** [comment]
Yes, Babel also doesn't support some certain type of decorators (yet), but that's a different story.

Let's see if @Roustalski can double check here :)

**Comment by EisenbergEffect** [comment]
It's all a bit rough because the whole spec is changing. With respect to Babel, I assume you are referring to param decorators. Perhaps they are waiting until after the spec update?

**Comment by PascalPrecht** [comment]
>  I assume you are referring to param decorators

Exactly.
