### ISSUE TITLE
[question] - resolve an instance of a type inside the registerHandler of the same type

### ISSUE THREAD

**Issue by eze1981** [aurelia/dependency-injection#75]
Hello,
I'm trying to register a handler to configure the container in order to resolve with a proxy of the desired type. For example, if I have the type FooService then I want to register a handler that resolves with a proxy of the FooService. 

I'm trying to implement this behavior using the **registerHandler** function but I'm generating an infinity loop during the resolution of the real FooService:

**My service class:**
```
import {inject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-fetch-client'

@inject(HttpClient)
export class FooService() {
    constructor(http) {
        //...
    }
}
```

**main.js:**
```
  aurelia
      .container
      .registerHandler(FooService, (c) => { 

          // resolves FooService
          let instance = c.get(FooService)   // --> here I'm generating an infinity loop during the container resolution

          // creates the service proxy
          let proxy = new Proxy(instance, { /* proxy handler */ })

          return proxy
      })
```

Is possible to avoid my infinity loop issue?

thanks,
Ezequiel

**Comment by EisenbergEffect** [comment]
Try `let instance = c.invoke(FooService);`

**Comment by eze1981** [comment]
Thank you for your fast response, I appreciate it.

It's working and the documentation is clear about that, I'm sorry. 

```
/**
  * Invokes a function, recursively resolving its dependencies.
  * @param fn The function to invoke with the auto-resolved dependencies.
  * @param dynamicDependencies Additional function dependencies to use during invocation.
  * @return Returns the instance resulting from calling the function.
  */
  invoke(fn: Function, dynamicDependencies?: any[]) {
     // ...
  }
```

**Comment by EisenbergEffect** [comment]
No need to apologize :) We are working on some new DI articles that will discuss things in greater detail.
