### ISSUE TITLE
Inject dependencies into properties

### ISSUE THREAD

**Issue by heruan** [aurelia/dependency-injection#84]
Would it be possible to inject dependencies not into constructors but on properties, after the instance is created? Like this:

```javascript
import { inject } from "aurelia-dependency-injection";
import { Router } from "aurelia-router";
import { Logger } from "logger";
import { Cache } from "cache";

export class Parent {

    @inject(Router)
    router;

    @inject(Logger)
    logger;

    @inject(Cache)
    cache;

    somethingNotInjected;

    constructor(somethingNotInjected) {
        this.somethingNotInjected = somethingNotInjected;
    }

}

export class Child extends Parent {

    constructor() {
        super("this can not be injected");
    }

}
```
This would permit to free constructors from being the only channel to pass dependencies and child classes to know about them, which could be a major restriction when parent classes depends on many (same behaviour occurs in Java CDI, for example).

For now, I'm using the main `Container.instance` to instantiate the properties on the parent classes, but it obviously doesn't inject the right instance when the child class is associated with a child-container (like `Router`).

**Comment by heruan** [comment]
I propose this: https://github.com/aurelia/dependency-injection/pull/85

**Comment by EisenbergEffect** [comment]
Closing this since you've got a nice plugin for it now.

**Comment by rsuter** [comment]
Can we move this into the core framework? This way we don't need to use an external package (which may not be supported in the future) and we don't have to bother with two different "@inject" decorators. Also I think in most application this feature is needed (everywhere where you have a base class for the components and which requires injected services).
