### ISSUE TITLE
Lifecycle management

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/dependency-injection#88]
I'm not sure if this is the place for it, but I'm looking for the best place to introduce lifecycle management not just for components, but for service classes as well. This is something that I'd love for the framework to be able to support.

I'm working on an application that has a number of data services that need to fetch data before they can be used. In Java EE I'd use a `@PostConstruct` annotation on an init method, which would be called by my container (blocking or not depending on the type of DI container). I'd like to be able to do initialization in my Aurelia service objects as well, and do it declaratively.

Ideally (not sure if this is workable), I'd like to write something like this:

```ts
export class AuthService {
  constructor(private http: HttpClient) {
  }

  @PostConstruct
  private init() {
    // fetch auth token over HTTP
  }
}
```

```ts
export class UserDataService {
  constructor(private authService: AuthService, private http: HttpClient) {
  }

  @PostConstruct
  private init() {
    // await auth token from auth service
    // fetch user data from backend
  }

  getUserDetails(): UserDetails {
    // give user details that may of may not have been fetched yet
  }
}
```

```ts
export class UserDetailsComponent {
  public userDetails: UserDetails;

  constructor(private userDataService: UserDataService) {
  }

  attached() {
    // somehow bind this.userDetails to this.userDataService.getUserDetails();
  }
}
```

How I'd see this work is that all three classes are instantiated without blocking, then the auth request fires. Once the auth request returns, the user data request fires. Once that returns, the VM's property updates, triggering a refresh on the associated View.

I'd be interested to know what other people think of this.

**Comment by EisenbergEffect** [comment]
I'm not sure I understand how the service could be reliably ready to use with this design.

**Comment by RomkeVdMeulen** [comment]
The service is available for injection immediately, so the application can start without blocking on the requests. However, the services aren't really "ready to use" until the requests are completed, which is the whole problem I'm hoping to solve.

Of course, if the initialization is handled declaratively, you'd need some way for the consumer of that service to be notified when that initialization is complete. I'm not sure yet what that might look like. In my first example I wrote "somehow bind to the result", but that might not be the best way to go about this. This is very much still an open problem for me.

To illustrate: if I had to implement the above example now, it'd look something like this.

```ts
export class AuthService {
  constructor(private http: HttpClient) {
  }

  getAuthToken(): Promise<AuthToken> {
    return this.http.get("authservice").then(res => mapToAuthToken(res));
  }
}

export class UserDataService {
  constructor(private authService: AuthService, private http: HttpClient) {
  }

  getUserDetails(): Promise<UserDetails> {
    return this.authService.getAuthToken().then(authToken => {
      return this.http.get("backend/userdetails?token=" + authToken.toString());
    });
  }
}

export class UserDetailsComponent {
  public userDetails: UserDetails;

  constructor(private userDataService: UserDataService) {
  }

  attached() {
    this.userDataService.getUserDetails().then(userDetails => {
      this.userDetails = userDetails;
    });
  }
}
```

And that's just in the simple case where the service is only used by one component. If multiple components are waiting for the `UserDataService` to initialize, then I have to administer the Promise I give each component to ensure that they're all notified once the data is in. Multiply that by a number of services with varying dependencies on each other, and it can quickly become a huge mess (which happened to our team when we previously built an app in Angular 1).

**Comment by EisenbergEffect** [comment]
I don't think this needs to be solved by the DI. I recommend that you consider writing a decorator based on your convention that you can use to decorate async methods to ensure that the initialization code is always run first before the actual method.

**Comment by EisenbergEffect** [comment]
The problem I see with the above hook is that it doesn't guarantee that any async code in that method has completed and there's no way to do that with our DI. Construction is synchronous.

**Comment by RomkeVdMeulen** [comment]
Exactly: construction is synchronous. I'd like to have a secondary phase that happens after the wire-up phase which ensures that the async code is run as well, in the correct order, rather than having to administer it myself.

You're right, though: neither my nor @heruan's implementation guarantees that async code has finished. What if the `afterConstructor` hook returns a Promise? Then as part of the wire up, the DI can connect each `afterConstructor` callback and promise to each other in the correct way. So if I have

```ts
class A {
  afterConstructor(): Promise;
}

@autoinject
class B {
  constructor(private a: A) {
  }

  afterConstructor(): Promise;
}

@autoinject
class C {
  constructor(private b: B) {
  }

  afterConstructor(): Promise;
}
```

the the DI container would make something like:

```ts
a.afterConstructor().then(() => b.afterConstructor()).then(() => c.afterConstructor())
```

but if I have:


```ts
class A {
  afterConstructor(): Promise;
}

class B {
  afterConstructor(): Promise;
}

@autoinject
class C {
  constructor(private a: A, private b: B) {
  }

  afterConstructor(): Promise;
}
```

then DI should make:

```ts
Promise.all([a.afterConstructor(), b.afterConstructor()]).then(() => c.afterConstructor());
```

**Comment by EisenbergEffect** [comment]
Take a look at the comment I left on the other issue. It explains how you can gain access to the invocation handler to add whatever logic you want there.

**Comment by EisenbergEffect** [comment]
We aren't going to fundamentally change the DI to be async though. That would be disastrous for complexity and performance. I don't think object creation should be async. The problem can be solved either with DI hooks or decorators, or a combination without us having to change the core DI.

**Comment by RomkeVdMeulen** [comment]
I'll look into that then. Thanks for the pointer!
