### ISSUE TITLE
Class declaration order breaks factory instantiation

### ISSUE THREAD

**Issue by zsvanderlaan** [aurelia/dependency-injection#90]
When 
  I have more than one class in a single file
  and Class A depends on Class B
  and Class A is declared before Class B
Then
  Invoking the factory fails indicating key/value cannot be null or undefined.

I have forked skeleton navigation and created a branch to expose the bug. Here is the diff for that branch: 
https://github.com/aurelia/skeleton-navigation/compare/master...zsvanderlaan:feature/FactoryBug

**Comment by EisenbergEffect** [comment]
I don't believe this has anything to do with Aurelia, but with ES2015/TypeScript. Check the transpiled output.

**Comment by zsvanderlaan** [comment]
I'll be sure to check the transpiled output before posting an issue in the future, as you are partially correct, this issue occurs after transpiling.

However, in the transpiled output it looks like the cause of this is the @autoinject() decorator. I'm not familiar with how these work, but I would imagine its possible to ensure a decorator is only applied to the class/function it decorates.
https://gist.github.com/zsvanderlaan/28986e333f7370642aa44d0e4c4272c8

**Comment by EisenbergEffect** [comment]
Yes, the issue isn't the decorator but the TS metadata output which is referencing types which are not yet defined.
