### ISSUE TITLE
Registering HttpClient in container does not work?

### ISSUE THREAD

**Issue by krostkowski** [aurelia/dependency-injection#91]
@jdanyow Hello, in #73 you used:
`container.registerHandler(ApiClient,ApiClientMock);` for registering an instance to DI.

In my typescript app I have a main.ts with:
```javascript
function configureContainer(container) {
let http = new HttpClient();
  http.configure(config => {
    config
      .useStandardConfiguration()
      .withBaseUrl('http://localhost:1234/api');
  });
  console.log('http before', http);
  container.registerInstance(HttpClient, http); .
  console.log('http after', container.get(HttpClient));
}
```

Instance logged after registration is not configured and has empty baseUrl. When used with `@inject(HttpClient)' or '@autoinject' it doesn't work either.

It works when used with `let http = container.get(HttpClient)`. Why is that? Is someting registering HttpClient earlier and I can't override it? I debugged registerInstance method and it's not invoked before.

**Comment by EisenbergEffect** [comment]
Nothing ever registers HttpClient in our code. Where is configureContainer coming from? That's not a standard hook. Can you show where you are invoking that and how you are getting the container instance?

**Comment by jdanyow** [comment]
I think he's missing:

main.ts
```js
export function configure(aurelia) {
  ...
  ...
  configureContainer(aurelia.container);
  ...
  ...
}
```

**Comment by krostkowski** [comment]
I have it in my main.ts. I've taken code from http://stackoverflow.com/questions/35140716/how-do-you-substitute-httpclient-in-aurelia (step1). 
I've tried to put``` configureContainer(aurelia.container);``` above the plugins initialization section suspecting some plugin registers it but still it doesn't work.
I will try to reproduce it on typescript skeleton fork.

**Comment by krostkowski** [comment]
Ok, I've found the problem in my code. I'm using:
```
  LogManager.addAppender(aurelia.container.get(LogAppender));
  LogManager.setLevel(LogManager.logLevel.debug);
  
  configureContainer(aurelia.container);
```
where my LogAppender is using HttpClient, so I assume container creates HttpClient instance and I can't override it later in `configureContainer`.

**Comment by EisenbergEffect** [comment]
If one has already been created and then you register one with the container, you aren't overriding it, you are actually adding a second instance. However, your service class requests a single instance of HttpClient, so it gets the first one.

You can use the `unregister` api to remove the first one, if you like. Or, you could register your http client before the logger if they can use the same convention. Another option would be to have the log appender not be created with DI and just manually construct the instances.
