### ISSUE TITLE
Bug with Factory function of class with static and dynamic dependencies

### ISSUE THREAD

**Issue by zsvanderlaan** [aurelia/dependency-injection#92]
Demo: https://github.com/zsvanderlaan/skeleton-navigation/commit/ab0026bea54b753674a54623858c3c74cb480b3e 

Issue:
a bug occurs when: 
a factory function injected by Factory.of() instantiates a class
and a dynamic dependency is provided to the factory function
and the instantiated class has the @autoinject() decorator
or the instantiated class has ANY decorator according to docs:

Source:
http://aurelia.io/docs.html#/aurelia/dependency-injection/1.0.0-beta.1.2.3/doc/article/dependency-injection-basics

"Interestingly, you don't need to use our autoinject decorator at all to get the above to work. The TypeScript compiler will emit the type metadata if any decorator is added to the class. Aurelia can read this metadata regardless of what decorator triggers TypeScript to add it. We simply provide the autoinject decorator for consistency and clarity."

Cause:
This is because function invokeWithDynamicDependencies(container, fn, staticDependencies, dynamicDependencies) is used to provide the dependencies to the instantiated class, and applies all static dependencies to the result array in addition to all dynamic dependencies, when it should stop populating the array with static dependencies once the size of the array reaches the number of constructor parameters minus the number of dynamic dependencies. Currently the number of constructor parameters is not exposed within the function.

Workaround:
There is a workaround demonstrated in the commit, which involves adopting a two parameter constructor signature as a pattern, where the first is provided by DI through the @inject decorator rather than @autoinject (this prevents us from having to add a large amount of boilerplate @inject() statements which would be strongly referenced in a class or interface refactor), and the second param is provided to a factory function as a configuration object. Unfortunately this is less than ideal as it presupposes the developer will always instantiate this class through a factory with a custom configuration object, when in fact it would make much more sense for us to follow a convention based approach where the configuration would also be injected with default values, and only rarely provided through a factory function when a custom configuration is required.

**Comment by EisenbergEffect** [comment]
The reason for this is that the `autoinject` tells the DI to automatically inject everything that is listed in the constructor. If you don't want that behavior, you need to specify `inject` instead, which allows you to explicitly indicate what should be injected by the container.
