### ISSUE TITLE
How can I use containers for test and production cases?

### ISSUE THREAD

**Issue by snortblt** [aurelia/dependency-injection#93]
In other projects with strongly typed languages (e.g. C#) I've commonly set up interfaces for stuff I wanted to mock during testing. Then I'd Inherit a class for production implementation and another for the mock. However, I've not been able to figure out how to do that with Aurelia/typescript. I've created an interface: 
`export interface BTAuthService {
	signIn(userName:string, password:string): Promise<any>;
}
`
Which is implemented by MockAuthService class.

I would expect to be able to do this:

`import {BTAuthService} from './serviceInterfaces';
import {MockAuthService} from './account/mockAuthService';

export function configure(aurelia:Aurelia) {
	aurelia.use
		.standardConfiguration()
		.developmentLogging();

	let container = aurelia.container;

	container.registerSingleton(BTAuthService, MockAuthService);
	aurelia.start().then(() => aurelia.setRoot());
}`

but I get the error "cannot find name BTAuthService."

What's the correct way to register a singleton by interface type?  
In general, I'd love to see some documentation on putting together a real-world test setup.

**Comment by EisenbergEffect** [comment]
This is because TypeScript erases the interfaces during compilation. There is no such thing as an interface in JavaScript, so there is no interface at runtime either.

Bear in mind, you don't need the interface, you can just use the original class but provide a Mock instance. JavaScript is dynamically typed, so it will work perfectly. 

```javascript
container.registerSingleton(TheConcreateType, MyMockType);
```

**Comment by snortblt** [comment]
Thanks, Rob. I just realized the same thing in a "duh" moment. Your suggestion is exactly what I went with.

**Comment by EisenbergEffect** [comment]
No problem. Sometimes with TS it's easy to forget the underlying platform's nature.
