### ISSUE TITLE
What is metadata.registration?

### ISSUE THREAD

**Issue by unional** [aurelia/dependency-injection#96]
I saw this:
https://github.com/aurelia/dependency-injection/blob/master/src/registrations.js#L9

```ts
export function registration(value: Registration): any {
  return function(target) {
    metadata.define(metadata.registration, value, target);
  };
}
```

But can't find `metadata.registration` definition on `aurelia-meta@1.0.0-beta.1.1.3`:
https://github.com/aurelia/metadata/blob/1.0.0-beta.1.1.3/dist/aurelia-metadata.d.ts

or in `aurelia-metadata@1.0.0-beta.1.2.1`:
https://github.com/aurelia/metadata/blob/1.0.0-beta.1.2.1/dist/aurelia-metadata.d.ts

Thanks

**Comment by EisenbergEffect** [comment]
It's not a public API.

**Comment by unional** [comment]
Got it. Thanks for the fast response! 🌷
