### ISSUE TITLE
@autoinject doesn't work when trying to inject DOM.Element

### ISSUE THREAD

**Issue by niieani** [aurelia/dependency-injection#97]
Probably something to do with the way TypeScript declares typeof Element.

**Comment by davismj** [comment]
If it helps, I have no problem autoinjecting `Element`s. I have not tried using autoinject with the pal's `DOM.Element`.

**Comment by EisenbergEffect** [comment]
If it's a TS issue, it's doubtful we can do anything about it.

**Comment by niieani** [comment]
I think we should leave it open to investigate (I can do this). 
I believe it was a TS bug introduced with 1.8, but that was already solved, but I'd still like to leave this open until I confirm that it works. And if it doesn't work, we should add the appropriate comment regarding it to the docs before closing.

**Comment by niieani** [comment]
I've investigated. The problem is here: https://github.com/s-panferov/awesome-typescript-loader/issues/162. Once that issue is fixed, injecting `Element` should work.

**Comment by niieani** [comment]
Once https://github.com/aurelia/dependency-injection/pull/118 is merged, the workaround would be not to use `@autoinject`, but `@inject(...)` as a constructor parameter.
