### ISSUE TITLE
No way to do a Lazy or Parent inject using @autoinject

### ISSUE THREAD

**Issue by niieani** [aurelia/dependency-injection#98]
There's currently no way to do a Lazy or Parent inject using `@autoinject`. We could solve that if these decorators had generic typings. Then we could use them like: `Lazy<HttpClient>`. The decorator would have to extract the type info - both the enclosing (e.g. Lazy) and the declared generic (HttpClient) types.

**Comment by EisenbergEffect** [comment]
Is that possible for TS to do? Also, can this be done without breaking the way that vanillla JS users use Lazy.of() today? If so, I'd love to see a PR.

**Comment by atsu85** [comment]
@niieani, @EisenbergEffect. Also keep in mind `NewInstance.of(SomeClass)` when implementing `@autoinject` for `Lazy` and `Parent` 

Instead of 
```typescript
@inject(NewInstance.of(ValidationController), HttpClient)
export class RegistrationForm {  
  constructor(public controller: ValidationController, public http: HttpClient) {
...
```
I'd like to write:
```typescript
@autoinject
export class RegistrationForm {  
  constructor(@newInstance public controller: ValidationController, public http: HttpClient) {
...
```
see [Parameter Decorators](https://www.typescriptlang.org/docs/handbook/decorators.html)

**Comment by EisenbergEffect** [comment]
That seems nice. Perhaps you can submit a PR to add parameter decorators for each of our out-of-the-box resolvers. I don't have a clue how to write those because they are not part of the Decorators spec for EcmaScript. It would be nice to have those for TS developers though.

**Comment by david-driscoll** [comment]
It may be possible to do something like...

```ts
class A {
    constructor(
        @lazy(SomeClass) someClass: () => SomeClass,
        @all(SomeClass) someClasses: SomeClass[],
        @parent parent: SomeClass,
        @newInstance instance: SomeClass,
        @optional optional?: SomeClass
    ) {}
}
```

It's not as easy as just giving the type information as a factory `() => ...` or as an array `SomeClass[]` because the compiler only gives us base level information.

**Comment by niieani** [comment]
@david-driscoll I thought the compiled did give information about generics. I'll look into that when I've got time to implement this.

**Comment by EisenbergEffect** [comment]
@niieani There's a PR linked above which adds parameter decorators for TS. Do you have time to review that?

**Comment by niieani** [comment]
Closed in https://github.com/aurelia/dependency-injection/commit/0eaba9be70a13e5f1375a32484d51f1ad191e35b.
