### ISSUE TITLE
Beta 2.0.1 is missing TypeScript definitions

### ISSUE THREAD

**Issue by MisterGoodcat** [aurelia/dependency-injection#99]
Hi,

I just wanted to set up a new app from scratch and realized that the newly published beta.2.0.1 that is pulled from NPM by JSPM by default does not contain the proper TypeScript definitions anymore (like the previously published Beta 1.2.3). This breaks development with TypeScript completely, because e.g. the autoinject decorator factory cannot be found/picked up by the compiler anymore.

**Comment by EisenbergEffect** [comment]
Please see our blog post from the other day explaining this: http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/

**Comment by MisterGoodcat** [comment]
I somehow missed that post. Thanks for the explanation.
